### ISSUE TITLE
Atom freeze when switching focus

### ISSUE THREAD

**Issue by thamurath** [atom/atom#10050]
Atom becomes unresponsive for more than 60 seconds when focus again on atom window.

Tested on: 
Windows 7 Enterprise 64 bits. 8 Gb RAM 
Nothing running but atom.
C++ project 

Tested with:
- Zip from master : Last commit 8b3c69b8b03e7210c517cfc51af561c7bd874465
-  Release 1.3.1

The problem happens with large projects using git and also with small folders with just a bunch of files ... but it is worst in the first scenario. It makes the (amazing) editor unusable ...

**Comment by annapetry** [comment]
I have the same problem on 1.3.1.  When attempting to open a file from the fuzzy search bar, Atom freezes.  I'm working with a large-ish project that uses git.

Mac OS Yosemite 10.10.5
Python project.

**Comment by benogle** [comment]
Are your repos public? Do all repos cause this? Can you link to a repo that causes it? Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by annapetry** [comment]
My repos are not public. :-1: 

I downloaded the 1.4.0 beta and that seems to have helped.  No crashers thus far.

**Comment by benogle** [comment]
Can you answer the other questions: 

* Do all repos cause this? 
* Can you try starting atom in safe mode?

**Comment by annapetry** [comment]
I am able to open Atom in safe mode. 
Not all repos cause this - I am able to open an Objective-C project with no problems, but my Python project now crashes when I try to open it with `atom .`.  Initially, it was crashing just when I attempted to open files within a project with fuzzy find.

**Comment by khrykin** [comment]
Also have freezes when code area loses focus on OS X 10.10.4  both in `atom` and `atom-beta`, safe-mode included.
`atom --version : 1.3.1`
`atom-beta --version : 1.4.0-beta0`

**Comment by mjhm** [comment]
It was hanging for me in version 1.3.1.  So I ran it with the dev tools open and hit the pause / resume buttons several times noting the stack trace and the paused code location. It appeared to be stuck in an infinite loop in [`getLongTitle`](https://github.com/atom/atom/blob/v1.3.1/src/text-editor.coffee#L615). It looks like this method has been rewritten in 1.4.0-beta0.  Upgrading to this beta version seems to have cleared up the problem for me.

**Comment by miguel250** [comment]
I have experience the Atom freezing while working on https://github.com/google/cadvisor/. I have no plugins installed and using version `1.3.1` on OSX 10.11.2.

**Comment by halverneus** [comment]
Same issue on Kubuntu 14.04 64-bit using 1.3.0 from WebUpd8 PPA.

**Comment by kileras** [comment]
Same here on latest OSX. The issue seems to happen when I focus a python file in my project, I can reproduce it quite consistently but I'm afraid I cannot share the project as its not public. I can say that is a python/js project with multiple folders in different locations open at the same time and I also use the devtools and trace the error to that getLongTitle method, which is called with this scope vars:
```
_i: undefined
_len: undefined
_ref2: undefined
directory: undefined
fileName: "BUILD"
nLevel: 9558507
paths: Array[2]
0: "/"
1: "/"
length: 2
__proto__: Array[0]
sessionPath: "/"
textEditor: undefined
this: TextEditor
title: undefined
```
I guess I'm going to try 1.4 and see if that solves the problem as it is quite annoying

**Comment by jeremyckahn** [comment]
I was having similar issues on OS X 10.11.2, Atom 1.3.2.  The issue seems to resolve itself (at least for the moment) after opening the Webkit Devtools.  Perhaps that cleared the cache, thereby fixing the issue?

**Comment by kileras** [comment]
I was able to reproduce it with the devtools open so at least for me that didn't solve the problem. I have been using 1.4 all day and so far it didn't happen again so it seems fixed in beta at least.

**Comment by fixpunkt** [comment]
I have the same problem. Deactivating the `svn` plugin fixed it for me.

**Comment by Xophe92** [comment]
I am the same problem on windows 10, I identified the situation when it happens: when I use the windows+right mouse to make atom use half of the screen. (it also happens when I move it to the right side of the screen so that windows 10 make it half the screen).

It seems that anytime it is "locked" with this windows feature, it freezes.

I hope it helps !

**Comment by 50Wliu** [comment]
Hi @Xophe92!  Your issue should be fixed in Atom 1.7.0 - you can download the beta version right now at https://atom.io/beta if you want.  Sorry for the trouble it's caused you.

**Comment by dthettich** [comment]
For me in 1.7.0-beta4 the problem of 2 sec freeze when switching focus still persists. (Win 7 enterprise)

**Comment by nitrocode** [comment]
Running 1.7.2 on Windows 8.1 Pro and see a 4 second freeze when switching focus even in safe mode. This issue makes atom painful to use. 

Is anyone else seeing the issue?

**Comment by nikolas6** [comment]
Using atom-windows 1.8.0-beta3 on Windows7 Pro.
Atom freeze for about 6-7 seconds when switching focus. Same thing happens in safe mode too.

However, I don't see atom freeze in this following scenario:
- start atom, then immediately switch to other app
- wait till atom finishes loading and shows the project (last session).
- switch back to atom, and atom focus immediately without freezing

After that initial switch, Atom will start freezing again when switching focus.

**Comment by 50Wliu** [comment]
Closing in favor of #9544 - feel free to subscribe there for updates.
