### ISSUE TITLE
Atom has strange redrawing issues on my machine

### ISSUE THREAD

**Issue by a-vasyliev** [atom/atom#10187]
Hi, 

I've issues with latest Atom release on my Dell Inspiron 7548 (4k display). I'm running Fedora 23. Please, check recorded video: https://youtu.be/ZVNVx8GezxQ.

`uname -a`
`Linux andrii 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`/sbin/lspci | grep VGA`

```
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Opal XT [Radeon R7 M265] (rev ff)
```

I don't know which information could be helpful for you, so I will add more information by your request.

**Comment by drewzh** [comment]
Exact same issue here running on Ubuntu 15.10 on Dell 9550 XPS 15 (Kernel 4.2), it's infuriating :(

I'm actually not even using the dGPU; I have it disabled. I'm solely running on i915 driver but if I switch to the propriety nvidia driver, the symptoms go away.

I actually had the same issue with Chrome Browser a few versions back and it seems to be fixed now... so I'm not sure if this is something that will be fixed when the version of Chromium gets bumped?

Anyway, just thought I'd add a +1.

**Comment by 50Wliu** [comment]
@drewzh do you remember which Chrome version fixed your problems?  Maybe 46 or 47?  If so, this should be fixed when we update to Electron 0.36.0, which will hopefully happen soon (I'm working on it right now).

**Comment by drewzh** [comment]
Unfortunately not, I can't remember the version. Curiously, I reinstalled Fedora today after playing with Ubuntu for a while and with the Intel driver I'm not seeing the same issue. I'm running on kernel 4.4rc6 ATM though which is newer than when I last tried. I just have a rendering issue in menus which is on another open ticket.

**Comment by a-vasyliev** [comment]
@50Wliu Btw, I have same/similar issues with Chrome (v.47). Today I've installed fresh and clean Fedora 23 + all available stable updates. Still the same for both apps.

**Comment by a-vasyliev** [comment]
@50Wliu Btw, I have no issues with Atom at all using another laptop (non 4k) with the same Fedora 23 with latest packages.
