### ISSUE TITLE
Multiple instances of Atom, multiple versions in Finder right-click menu

### ISSUE THREAD

**Issue by OKNoah** [atom/atom#11047]
### Description

Atom has multiple instances open. And there's two versions of atom in the Open File With... Finder context menu.
### Steps to Reproduce

Open files in Atom. I use the Dock drawer, Finder context menu and `atom` command line tool to open things in Atom.

**Expected behavior:** One instance of Atom, multiple windows.

**Actual behavior:** 2+ instances of Atom, each with own Dock icon.
### Versions

1.5.3 and 1.5.4 (apparently, according to right-click menu)

**Comment by joshaber** [comment]
@OKNoah Thanks for opening this! I'd love to know where on disk those different versions of Atom are. Right-click on each icon, select Options > Show in Finder, and that should show where the app is.

**Comment by OKNoah** [comment]
@joshaber 2 of them open to the same Atom.app in my Applications folder. The third doesn't open anything in Finder.

Actually, clicking the third one brings up a crashes version of Atom with the option to reopen or "close window". Clicking close window seems to close it, but click the dock icon again does the same thing. Also, it's not visible in Expose.

**Comment by jfi** [comment]
I've got what I think is the same issue; sometimes (especially after calling "atom" from the command line), I get two different instances open in my dock. Only one has an indicator light, but they're both open, and I can interact with them both. If I already have an instance of atom opened then run e.g. "atom ." inside a folder in Terminal, it flashes up a second dock icon and then takes it away again. Sometimes, it seems it's not taking it away and I end up with two instances.

**Comment by lee-dohm** [comment]
Atom has a system where there is only supposed to be one main process no matter how many windows are open. This means that there will only be one icon in the Dock in normal circumstances. When you launch an additional instance, the second instance passes off the launch instructions to the original instance and exits. This is why there is sometimes a second item in the Dock that then disappears. This is still normal.

Under certain circumstances, such as when Atom has updated itself but you have not yet restarted, when you launch an additional instance the second item in the Dock remains. This is because the two copies of Atom are different versions. If you exit the original copy of Atom and then launch again, everything should be unified under the new Atom instance. This is also expected behavior. (Even if sub-optimal, working around this is probably not worth the effort.)

@jfi or @OKNoah, are you encountering any behavior that does not fall in line with what I'm describing?

**Comment by OKNoah** [comment]
@lee-dohm If Atom is automatically updating in the background, then that's possible. I'm not updating it myself though.

> I've got what I think is the same issue; sometimes (especially after calling "atom" from the command line)

I also run from the terminal a lot.

**Comment by OKNoah** [comment]
@lee-dohm This happened again about 2 days ago. But a friend said to me later "geez, atom hasn't updated in a while". Sure enough I looked and it doesn't look like there was an update around that time. Moreover, the version on both said `1.8.0`. Could it be caused by the release of the `1.9.0` beta? Maybe the issue is I've signed up for the beta and forgotten about it?

**Comment by spencern** [comment]
Experienced this same issue just now with version `1.9.8` Had atom open and then opened a directory from the terminal (`atom .`) and it spawned a new process and a new dock icon. Showing in finder reveals the same application for both instances. I'll try restarting and see if that fixes.

**Comment by joerhoney** [comment]
I've had all of the same problems. Mac OS Sierra v. 10.12.1, Atom 1.12.2 (and earlier versions). I usually try to fix it by restarting Atom, but it doesn't always work. I guess Atom doesn't necessarily install any newly downloaded updates upon restart?

Anyway, yesterday I uninstalled Atom entirely, then reinstalled it, which fixed the problem for the rest of the day. This morning the problem came back. After reading the above comments I checked for updates and found that one has been downloaded (1.12.3), so maybe Atom automatically downloaded it this morning while I was using it. So I clicked "Restart and Install" and unchecked the "Automatically download updates" box, hoping this will help prevent the workflow interruptions. I'll try to remember to come back here and report whether the problem persists or not.

**Comment by joerhoney** [comment]
Weird. It happened again, but I'm not sure why. I checked the version number and it was 1.12.2. It should have been 1.12.3 as I had clicked "Restart and Install." So I quit Atom. I tried opening it from the dock newly and the version number was still 1.12.2. I quit again and tried opening a file that would prompt Atom (a .php file). Now it said 1.12.3. So apparently keeping Atom in your dock between updates can lead to this problem. Presumably than, you can avoid the issue by:

1. Turning off "Automatically download updates" so that you don't get multiple versions unexpectedly 

2. Removing it from your dock before updating

Or at least that should eliminate some of the triggers to the problem.

**Comment by NicoSa** [comment]
I am getting the same problem. Would appreciate a solution since this makes it really hard to open a working version. Most of the versions tends to throw a lot of errors in my face when I open them...
![screen shot 2017-01-13 at 11 09 05 am](https://cloud.githubusercontent.com/assets/5588696/21928108/d4e9a87e-d980-11e6-9786-3c6b07a589bc.png)

**Comment by anaber** [comment]
Same issue for me as well.
![screen shot 2017-01-13 at 1 49 35 pm](https://cloud.githubusercontent.com/assets/730989/21946883/3262dc9e-d997-11e6-8365-91e350a8a86a.png)

**Comment by jqlee85** [comment]
Me as well. Anything opened from CLI or from the GitHub GUI opens in another instance that always locks up then crashes. Has anyone figured out a fix for this?

![screenshot](https://cldup.com/K3Ty0oSdms-3000x3000.png)

**Comment by 50Wliu** [comment]
For people who are _only_ affected by the multiple versions in Finder, there are solutions in https://github.com/atom/atom/issues/1720.  Please do not comment here.

**Comment by OKNoah** [comment]
I've also run into this issue on the Github desktop app on Mac.

**Comment by tyteen4a03** [comment]
+1. Has been here for ages.

**Comment by jjingrong** [comment]
+1, it's pretty annoying - especially when opening from command line and you end up having multiple instances of Atoms open

**Comment by Aea** [comment]
@50Wliu Those are workarounds at best.

**Comment by lee-dohm** [comment]
@Aea your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is off-topic, unproductive and argumentative. You may consider this an official warning.

**Comment by JWhiteUX** [comment]
I'm experiencing the same problem.
![screen shot 2017-04-14 at 10 19 12 am](https://cloud.githubusercontent.com/assets/12961108/25050348/dc0e78ce-20fb-11e7-9694-7dacec9b48c5.png)

**Comment by 50Wliu** [comment]
@JWhiteUX please [read my comment](https://github.com/atom/atom/issues/11047#issuecomment-274192652).

**Comment by neurodynamic** [comment]
+1 on opening from the command line. Very frustrating.

**Comment by colmsjo** [comment]
+1

**Comment by blakeperdue** [comment]
Solution is documented here: https://github.com/atom/atom/issues/1720

Run this in terminal: `rm -rf ~/Library/Caches/com.github.atom.ShipIt`

It will only remove the Atom duplicates and won't force Finder to reset all other data it is on your other apps.

**Comment by SlouchingToast** [comment]
I've tried this `rm -rf ~/Library/Caches/com.github.atom.ShipIt` and this `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -seed -domain local -domain system -domain user` but still get Atom 1.19.0 and Atom 1.18.0, 1.19.0 being the bad guy.

**Comment by blakeperdue** [comment]
Did you restart Finder after removing `~/Library/Caches/com.github.atom.ShipIt` via `killall Finder` or via a reboot? I just tried and it removed the other versions of Atom on my iMac.

**Comment by vincent2021** [comment]
I had to delete the .app in the folder ~/Library/Application Support/com.github.atom.ShipIt/update to solve this problem. 

I deletes all version and did a clean install but the issue just came from the folder mentioned above in my case.

**Comment by JWhiteUX** [comment]
Kinda surprised this is still an issue…

**Comment by lee-dohm** [comment]
@JWhiteUX Given that:

1. This has zero impact other than cluttering a menu that not everyone uses
1. It only affects one platform of three
1. Until recently, the cause of it was unknown
1. Now that the cause is known, all people have to do to not be affected by it is not launch Atom from their update folders
1. It has a well-documented fix even if someone accidentally launches Atom from their update folder

There are lots of other higher-priority things for the maintainer team to be working on. Perhaps you would be willing to lend a hand and help fix the underlying problem?

**Comment by blakeperdue** [comment]
@lee-dohm what is the known cause? I have been watching this but didn't see that. My apologies if I missed it.

Also, what does `launch Atom from their update folders` mean? I downloaded the app, moved it to /Applications and have been updating it via in-app commands ever since and I experience this problem regularly. 

Can point me in the direction of the documentation you mentioned in #5. 

Oh, and thanks for making an awesome, open-source app. Often times you get more grief than thanks for all your hard work. But, seriously, thank you. Atom makes my life and job much easier!

**Comment by lee-dohm** [comment]
@blakeperdue As mentioned by @50Wliu [above](https://github.com/atom/atom/issues/11047#issuecomment-274192652), there are solutions in #1720, which point to [my comment on Discuss](https://discuss.atom.io/t/mutliple-atom-entries-in-open-with/3401/3?u=leedohm), the solution I got from [the Apple StackExchange site](https://apple.stackexchange.com/questions/77154/clear-multiple-entries-form-open-with-context-menu) long ago after a quick Google search for multiple entries in the Open With menu. (By "well documented", I meant that Atom is not the only Mac app that occasionally runs into this issue, so the solution to resetting the menu is fairly easy to find. I had found this solution before I even started working on Atom.)

> Also, what does launch Atom from their update folders mean?

Apparently, from [comments like this one](https://github.com/atom/atom/issues/11047#issuecomment-325763668) macOS is adding entries to the Open With menu for `Atom.app` not in `/Applications` but in `~/Library/Application Support/com.github.atom.ShipIt/update`. The only reason for that would be if someone launched Atom from that directory, perhaps by launching Atom from a Spotlight (or similar tool) search and picking one of multiple `Atom.app` entries.

> Oh, and thanks for making an awesome, open-source app. Often times you get more grief than thanks for all your hard work. But, seriously, thank you. Atom makes my life and job much easier!

You're welcome :grinning: I'm glad that we can help :+1:

**Comment by blakeperdue** [comment]
@lee-dohm thanks for the reply. I saw those solutions but [as I commented on #1720](https://github.com/atom/atom/issues/1720#issuecomment-300045400):

> I'd love for an easier solution than wiping all the Finder data around apps. It's taking a sledgehammer to the problem.

Next time this happens to me I'll see if I can figure out how I launched Atom (updates folder or `/Applications` folder). This is happening with other Mac apps so I would agree that closing this issue is the right move and that this solution, as much as I don't like it, is the best remedy at the moment:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder`

As noted on the [Atom Discuss site](https://discuss.atom.io/t/mutliple-atom-entries-in-open-with/3401/4), this issue will crop up again and again as new updates are released, so using a [script like @lee-dohm's](https://discuss.atom.io/t/mutliple-atom-entries-in-open-with/3401/3) or [DaveEveritt's](https://github.com/atom/atom/issues/1720#issuecomment-182578589) when the problem appears seems easy enough for now.

**Comment by flowera** [comment]
https://github.com/atom/atom/issues/1720 
I have tried all the method on this thread. 
It worked but after my update, it shows two options again. 
<img width="413" alt="screen shot 2017-09-28 at 5 40 56 pm" src="https://user-images.githubusercontent.com/27442322/30993382-6691ab1e-a474-11e7-905f-c350950dbd63.png">
Very annoying, hope somebody could help us out, it should be an open ticket, since there is no useful way to fix the problem.

**Comment by blakeperdue** [comment]
You have to use a solution after each update as each update will leave your system with two `.app` files somewhere on your system that Finder is referencing. So, each time you have the problem, you run the solution. It's not a run-once thing. It's a run after update, unfortunately.

**Comment by FutureSharks** [comment]
For the last 2 years I've had this annoying problem. Usually I use an alias to open Atom from the command line:

```
alias atom='open -a Atom'
```

And regularly it will open different version in a new window which will crash. Then I have to close the crashed version and run the command again, then it correctly opens the directory in the existing window. Generally speaking I rarely restart Atom so could have a version running for 3-4 weeks as I never restart my computer.

**Comment by SamanthaDegges** [comment]
In your home directory, you can delete the original versions of Atom in com.github.atom.ShipIt/Atom.app (It seems the new version will always be in the Applications(on macs) folder, or in Downloads if you’ve installed it from there and left it there.)

I deleted everything in com.github.atom.ShipIt and the .app there as well. This solved my problem. I imagine I will have to do this every time I update Atom.

**Comment by miglen** [comment]
I was able to remove it by locating the stale download of previous Atom version as simple as starting the older version from the context menu, locating where this is starting from (ps-fe | grep Atom --color) and deleting the .app folder.

**Comment by OKNoah** [comment]
Happy 2nd birthday to this low-priority issue.

**Comment by tonykaram1993** [comment]
I just found this page and I don't think it has been fixed yet. However I think I know why this is happening and I think I can provide steps to reproduce it.

Setting in question is: File>Settings>Core>Restore Previous Windows On Start

First let's open a few files on atom, let's say we opened: banana.txt, apple.txt, and watermelon.txt. Then we close atome.

- If option is set to NO: next time atom is launched, everything is blank. If someotherfile.txt is opened via atom, that file will be shown.
- If option is set to YES: next time atom is launched, everything is the way it was when atom was closed. If someotherfile.txt is opened via atom, that file will be shown.
-If option is set to ALWAYS: next time atom is launched, everything is the way it was when atom was closed. THIS IS WHERE THIS HAPPENS. If someotherfile.txt is opened via atom, TWO instances of atom are launched, the first containing whatever atom had open when it was last closed, and the second contains someotherfile.txt.

What I normally expect to happen is to open whatever was opened last time atom was closed and add a new file/tab for the file that was opened (in this situation someotherfile.txt).

Hope I am right about this and that I did not get things messed up. I don't think this is how it's supposed to be right?

**Comment by FutureSharks** [comment]
Any update on this?

- It's been a problem for years
- It's still happening today
- Looks to be related to ShipIt?
- Only a problem on Mac

Other references to this same problem:
https://github.com/atom/atom/issues/13299
https://github.com/atom/atom/issues/9774
https://github.com/atom/atom/issues/17387
https://discuss.atom.io/t/atom-editor-will-be-listed-multiple-times-in-macos-x-native-right-click-menu/6061/2
https://discuss.atom.io/t/mutliple-atom-entries-in-open-with/3401

Sometimes it can be resolved by running:

```
rm -rf ~/Library/Application\ Support/com.github.atom.ShipIt
```

**Comment by AbandonedCart** [comment]
https://github.com/atom/atom/issues/17387 was not an instance of this issue and was closed because support refused to properly diagnose it. In that case, the newer version was inaccessible and would crash instantly and leave the older version saying no updates were available. 

However, if you attempt to launch the newer version through a context menu and it crashes, but then launch the same file in the older version through the context menu, there is a 75% chance that the new version will install itself correctly and replace the previous version at some later point after closing the application completely (ie. right clicking the dock and selecting quit).

@FutureSharks There is a good chance your alias workaround is doing more harm than good, as it appears you are also experiencing the crash, but circumventing any chance it will correct itself.

**Comment by FutureSharks** [comment]
@AbandonedCart 

> There is a good chance your alias workaround is doing more harm than good

I have the same problem when launching via the Dock icon also.

**Comment by AbandonedCart** [comment]
@FutureSharks An alias will inherit the problems of it's target, so that is expected.

**Comment by FutureSharks** [comment]
@AbandonedCart so if I can't use the command line and I can't use a Dock icon, then how I am supposed to open an application? I have to open the finder every time?

**Comment by AbandonedCart** [comment]
@FutureSharks I don't recall saying any of that, but you go ahead and do whatever works for you. It isn't really a "functional" workaround, but every issue may be slightly different. Best of luck.

**Comment by FutureSharks** [comment]
> I don't recall saying any of that

Sorry, I meant the "doing more harm than good" part.

Anyway, I think after this long with this issue I will switch to VS Code.

**Comment by johngabe** [comment]
> I've got what I think is the same issue; sometimes (especially after calling "atom" from the command line), I get two different instances open in my dock. Only one has an indicator light, but they're both open, and I can interact with them both. If I already have an instance of atom opened then run e.g. "atom ." inside a folder in Terminal, it flashes up a second dock icon and then takes it away again. Sometimes, it seems it's not taking it away and I end up with two instances.

For me it was a Mac Issue showing "recent" applications.

Fix this with System Preferences > Dock > uncheck "Show recent applications in Dock"
