### ISSUE TITLE
Failed to delete [package]: Does not exist

### ISSUE THREAD

**Issue by UziTech** [atom/atom#11464]
### Description

When uninstalling a package  I get the error "Failed to delete [package]: Does not exist"

### Steps to Reproduce

1. Click Uninstall on a package

**Expected behavior:** 

Package gets uninstalled and the install button appears

**Actual behavior:**

Error shows up and package gets removed from the computer but Atom still thinks it is installed until Atom is restarted

### Versions

atom --version

Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm --version

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.0.windows.2
visual studio 2013

OS version: Windows 10 Build 14316.rs1_release.160402-2217

**Comment by 50Wliu** [comment]
I can confirm this, though not with an exact Atom version because it happened around a week ago.

**Comment by 50Wliu** [comment]
From https://github.com/atom/atom/issues/11476#issue-148504196:
>Both Mac and Windows.
Select a package to uninstall and following message [does not exist] displays. After restarting Atom, the message and the corresponding package is removed.

**Comment by edwinksl** [comment]
I can confirm this happens on Atom Beta 1.8 in Ubuntu 15.10.

**Comment by Nikki1993** [comment]
Can confirm similar behaviour with latest 1.9.0-dev version from master.

**Comment by Sopamo** [comment]
I can confirm this (except I didn't uninstall the package). The package just stopped working (it did work yesterday) and I can't uninstall it.

Running on OSX 10.11.3

atom --version
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.1

**Comment by Nikki1993** [comment]
@Sopamo open up a different issue. If you are experiencing packaging problems unrelated to aforementioned problem, it's safe to assume you might be dealing with different bug here. Search for issues already posted and if nobody mentioned what you are describing, open up a new one.

**Comment by UziTech** [comment]
Here is the error in the console that I get when uninstalling a package
```
C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:721 Uninstalling package emmet-snippets-compatibility failed Error: Uninstalling “emmet-snippets-compatibility” failed.
    at C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:504:21
    at exit (C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) Failed to delete emmet-snippets-compatibility: Does not exist
(anonymous function)	@	C:\Users\tjbrix\AppData\Local\atom\app-1.7.1\res
```

**Comment by UziTech** [comment]
I narrowed it down to the `apm uninstall --hard [package]` command that is called.

It looks like the `--hard` option removes the package from `~/.atom/packages` and `~/.atom/dev/packages`

The package is removed from  `~/.atom/packages` but fails when it doesn't find the package in `~/.atom/dev/packages`

**Comment by UziTech** [comment]
https://github.com/atom/apm/commit/dfdfc73d5e5144d156ce2f896157a5033b655466

This commit to apm added a throw statement on `--hard` when the package is not found in the dev folder

Not sure if apm should only throw this error on `--dev` and not on `--hard` or if atom should check dev folder before using `--hard` options

**Comment by jbhannah** [comment]
This also prevents `onDidUnloadPackage` callbacks from executing. Seconding @UziTech, looks to me too like atom/apm#539 should fix this.

**Comment by AndreAmo** [comment]
Also happens on:

OS X :  10.11.4 (15E65)

`atom --version`
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

`app --version`
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4

**Comment by JoeNoPhoto** [comment]
> OS X : 10.11.4 (15E65)
> 
> atom --version
> Atom : 1.7.2
> Electron: 0.36.8
> Chrome : 47.0.2526.110
> Node : 5.1.1
> 
> app --version
> apm 1.9.2
> npm 2.13.3
> node 0.10.40
> python 2.7.10
> git 2.6.4

+1  same specs as above

**Comment by DaanWaardenburg** [comment]
I seem to have the same problem...

Also OS X: 10.11.4 (15E65)
and atom 1.7.2

atm I feel like atom is leaving forgotten files around my computer this sucks....

**Comment by ahmetabdi** [comment]
Same here

`Atom    : 1.7.2`
`Electron: 0.36.8`
`Chrome  : 47.0.2526.110`
`Node    : 5.1.1`
`Mac : 10.11.1`

**Comment by Filisko** [comment]
Happens to me when I try uninstall any package, and It actually uninstalls it, because it dissapears from the **packages** directory. So, I restart Atom to make the package dissapear from the installed packages list.

```
$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by jonatasleon** [comment]
Happens here
```
$ uname -mrs
Linux 3.13.0-85-generic x86_64

Description:	Ubuntu 14.04.4 LTS

$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 2.8.1
```

**Comment by dade80vr** [comment]
Same here, Atom 1.7.2 on Mac OSX 10.11.4

**Comment by puranjayjain** [comment]
Happens with me on:
Atom: v1.7.2 and 1.8.0-beta2
Windows 10 (x64) Enterprise and Pro

First happened when trying to uninstall a disabled package.
Happens now for all the packages.

**Comment by VladShcherbin** [comment]
Same here, Atom 1.7.2, Mac OS

**Comment by unclejustin** [comment]
Ditto Atom 1.7.2, Mac OS

**Comment by lee-dohm** [comment]
Fixed on `master` via apm v1.9.3. This should be released with v1.9.x of Atom.

**Comment by mitchellnemitz** [comment]
How long until we see a stable v1.9.x release? Is there a way to patch the latest stable (v1.7.3 at the time of this writing) or are we stuck waiting? Constantly running `window: reload` is getting really old.

**Comment by Nikki1993** [comment]
@mitchellnemitz download atom from github, make local changes and build latest stable release tag yourself. Otherwise, wait patiently.

**Comment by ivanwolf15** [comment]
Same problem here
```
atom -v
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
running on mac OSX

**Comment by mitchellnemitz** [comment]
@Nikki1993 One of the core features of the editor (package install / uninstall) is glitched. I would have assumed that Github would be a bit more excited to get a release out, considering new users are going to hit this snag pretty much instantly. I'm more than capable of building myself, but are converts from Sublime really going to see this kind of bug and want make the switch? That's more what I'm worried about.

**Comment by Nikki1993** [comment]
@mitchellnemitz I do not disagree, however a really good pic to explain bug fixes 

https://imgur.com/HTisMpC 

Simple fix may introduce loads of regressions/other issues. It took > 1 month to release a fix for Linux distributions. Atom **didn't even work**. Here you have quite a minor regression (package deletion itself works fine, it's just not aware of the actual process) so on a large scale it's not a priority (again, speaking totally from my perspective, I am in no way associated with atom team).

Again, I feel you and agree with you on release time, however such a large code base is hard to maintain and **any change** may break other things.

**Comment by Aventura5** [comment]
@UziTech is right I think, here's apm's output:

````
>>> apm uninstall --hard git-plus
Uninstalling git-plus failed
Failed to delete git-plus: Does not exist
````

I'm going to open an issue on the apm repo.

**Comment by Winseven4lyf** [comment]
In my case, script_runner was stuck. I used ` apm clean ` and it worked.

**Comment by melzareix** [comment]
@Winseven4lyf That did the trick for me too!

**Comment by Aventura5** [comment]
@Winseven4lyf Sadly that didn't fix mine, I keep getting

    Failed to delete package-name: Does not exist

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.9.0.  Just reload the Atom window in the meantime to work around this.

**Comment by pedzed** [comment]
> This has been fixed in Atom 1.9.0

Can this be moved to 1.8.0? It's quite an important bug...

> Just reload the Atom window in the meantime to work around this.

What does that mean?

**Comment by mitchellnemitz** [comment]
@pedzed open the command pallette and run `window:reload`

**Comment by 50Wliu** [comment]
Ctrl+Alt+R on Windows/Linux, Cmd+Ctrl+Alt+L (I believe) on OS X.

I'll talk with the team about moving this to 1.8.0.

**Comment by lee-dohm** [comment]
> Can this be moved to 1.8.0? It's quite an important bug...

This is a fairly visible bug :point_up: that has almost no negative effect 👇 and has a simple and low-impact workaround 👇. These factors already make the priority of getting the fix pushed out fairly low. Another factor reducing the priority is that it does not affect the command line experience.

Given that our team is understaffed currently with two developers out on parental leave and others out for speaking engagements and conferences, we feel the risk here outweighs the rewards. We're going to leave this on track for v1.9.x as I said in my original response.

**Comment by brandonk3nt** [comment]
While it does have no negative affect and a low-impact workaround, it makes Atom look clunky and unpolished. I was showing Atom to some buddies @ work (because I love it and am constantly evangelizing) and how easy package management was, and they saw the bug and are going to be using VS Code instead of Atom as a result :(

**Comment by OJFord** [comment]
I too am very surprised this is being held off for v1.9 - this isn't an important feature or something, it's a fix for a bug that to be honest never should have made it to the stable branch anyway.

**Comment by UziTech** [comment]
Can someone explain why this would be more difficult to implement in v1.8 then v1.9

**Comment by mitchellnemitz** [comment]
FYI you can checkout `v1.7.4` (current stable at the time of this writing) and update the version of `apm` to `v1.10.0` in `apm/packages.json` and [build it yourself](https://github.com/atom/atom#building) to "fix" this bug. I've been using it for just over a week and so far no issues.

Really a shame that such a clunky bug has been with us for over a month and likely won't be fixed for a few more. C'est la vie I suppose.

**Comment by mitchellnemitz** [comment]
@UziTech it's not difficult, it's already fixed in master, Atom devs just don't want to deal with a possible cascade of bugs as they're short staffed at the moment.

FYI you can checkout `v1.7.4` (current stable at the time of this writing) and update the version of `apm` to `v1.10.0` in `apm/packages.json` and [build it yourself](https://github.com/atom/atom#building) to "fix" this bug. I've been using it for just over a week and so far no issues.

Really a shame that such a clunky bug has been with us for over a month and likely won't be fixed for a few more. C'est la vie I suppose.

**Comment by mitchellnemitz** [comment]
@UziTech It's not, but the dev team is a skeleton crew and they want to avoid possible cascading bugs.

If you want to fix it yourself, follow [the build guide for your system](https://github.com/atom/atom#building) but after checking out current stable (`v1.7.4` at this writing) edit `apm/packages.json` and update the version to `v1.10.0`. I ran `v1.7.3` for ~2 weeks this way and had no issues, but YMMV.

Really a shame that such a visible bug will be open for months before getting fixed for the general public.

**Comment by VladShcherbin** [comment]
This bug has to be top priority as it is one of the basic core features and almost all developers will see it.

It's a surprise, how it got into stable build and is not fixed since April.

**Comment by UziTech** [comment]
>  that has almost no negative effect

I would argue that new people checking out atom for the first time, many of which will see this bug before being invested in keeping Atom as their new IDE and, arguably, decide to go with another IDE that is less buggy is a pretty **BIG** negative effect

**Comment by oslaustin** [comment]
after upgrading to 1.7.4, the issue happened

**Comment by cbstodd** [comment]
Same

**Comment by smddzcy** [comment]
Same here, it says **it couldn't delete the package** it but it actually deletes.

**Comment by 50Wliu** [comment]
As this has already been fixed in Atom 1.9.0 I'm locking this issue.
