### ISSUE TITLE
Atom 1.9.8 Crashes in Ubuntu in VirtualBox

### ISSUE THREAD

**Issue by tmcothran** [atom/atom#12461]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I'm running Ubuntu Mate 16.04.01 in Virtualbox. When opening atom 1.9.8, I simply get a black screen. Here's what it looks like: [image](https://cdn-business.discourse.org/uploads/github_atom/optimized/3X/3/6/36164a2679a068687216c84493199d75f3df10e5_1_690x336.png)

I've run in safe mode, I've followed the steps in the debugging guide, I've reinstalled Atom. I even installed a brand new OS instance of Ubuntu (again in VirtualBox) and have the same problem.

I [brought this up](https://discuss.atom.io/t/atom-wont-open-on-ubuntu-16-04-1/32026) on the atom support forums, and it appears a number of other users are having the same issue. I also rebuilt from source with the same problem.

### Steps to Reproduce

1. [First Step]
Install Atom in VirtualBox running Ubuntu 16.04.1
2. [Second Step]
Open Atom

**Expected behavior:** [What you expected to happen]
Atom opens
**Actual behavior:** [What actually happened]
Atom crashes with [this screen](https://cdn-business.discourse.org/uploads/github_atom/optimized/3X/3/6/36164a2679a068687216c84493199d75f3df10e5_1_690x336.png)
Sometimes I get this [error screen](http://imgur.com/a/7YYWv). If somebody points me to where these logs are stored, I'll post them.

### Versions
Atom 1.9.8, Ubuntu 16.04.1, running the Mate desktop environment.

**Comment by tmcothran** [comment]
On the Atom forum, [flippybird points out](https://discuss.atom.io/t/atom-wont-open-on-ubuntu-16-04-1/32026/13?u=tmcothran) this problem only shows up if 3d acceleration is turned on in the VirtualBox settings. I think this is an Atom problem, since nothing else on my system seems to be affected, but perhaps it will turn out to be a VirtualBox issue.

**Comment by lee-dohm** [comment]
Can you try running Atom on some other virtualization system other than VirtualBox? If this problem only reproduces on VirtualBox, then I would have to conclude that it is a VirtualBox issue.

**Comment by lee-dohm** [comment]
According to someone else on the [original Discuss topic](https://discuss.atom.io/t/atom-wont-open-on-ubuntu-16-04-1/32026/17?u=leedohm), this may be fixed in a recent VirtualBox update. @tmcothran, can you confirm?

**Comment by lee-dohm** [comment]
Since it sounds like this is resolved. I'm going to close it. Let us know if that isn't the case!

**Comment by tmcothran** [comment]
Sorry @lee-dohm , I've been buried and haven't been able to try to load this in another vm. I think you're right that it's VirtualBox though, because it seems to be affected by updates and settings in VirtualBox. If I get some breathing room, I'll install VMWare and see if I can reproduce it there.

**Comment by hellt** [comment]
Still happens with VirtualBox 5.1.8 and atom 1.12.2
atom --disable-gpu helps, but this is not a convenient way

**Comment by rubinsh** [comment]
Still happens with VirtualBox 5.1.8 and atom 1.12.2
atom --disable-gpu - works but it is not a real solution in my mind.
when running: 
```
/usr/lib/nux/unity_support_test -p 
OpenGL vendor string:   Humper
OpenGL renderer string: Chromium
OpenGL version string:  2.1 Chromium 1.9

Not software rendered:    yes
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       yes

```

atom won't display correctly without the --disable-gpu flag
when I disable the GPU (working with software rendering) in my Ubuntu VM atom runs fine without the flag.

**Comment by jpolo** [comment]
Confirmed in vbox 5.1.14 and atom 1.14.4

**Comment by lee-dohm** [comment]
This isn't something that we're going to be working on. Since Atom works both unvirtualized and using other virtualization systems, we believe that this is a problem for VirtualBox to solve. For now the workaround we recommend for this VirtualBox bug is to use `--disable-gpu`.

**Comment by JellePetersHAN** [comment]
@rubinsh Any idea which version of VirtualBox introduced this problem? I recall having used Atom in the past in a virtual machine, that was accelerated by an nVidia graphics card, and it didn't cause any problem.

**Comment by rubinsh** [comment]
The problem has been around for quite some time now. I guess since version 1.2 if I recall correctly, but I'm really not sure... 
Come to thing if it, I think the problem started when I upgraded to virtualbox 5.0.16 and that this issue is related more to virtualbox than to atom.

**Comment by 50Wliu** [comment]
@rubinsh You're close.  The issue is specifically with Guest Additions versions greater than 5.0.16.  You can read #11574 for more details.

**Comment by kabartay** [comment]
atom --disable-gpu helps

thanks to all, you saved my time

**Comment by EppO** [comment]
Last Atom version seems to fix the issue:
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Virtualbox: 5.1.26 r117224 (Qt5.6.2) with Virtualbox additions (5.1.26 r117224)

Before Atom 1.19.0, I had to run Atom without GPU acceleration like this:
```
# atom --disable-gpu                                                                                                                                        # ps ax | grep atom                                                                                                                                         
32306 pts/5    S      0:00 /bin/bash /usr/bin/atom --disable-gpu
32309 pts/5    Sl     0:01 /opt/atom/atom --executed-from=/home/florent --pid=32288 --disable-gpu
32319 pts/5    S      0:00 /opt/atom/atom --type=zygote --no-sandbox
32396 pts/5    Sl     0:02 /opt/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=A3C2D3B9F1F9B329749D837437C8E994 --lang=en-US --app-path=/opt/atom/resources/app --node-integration=true --disable-blink-features=Auxclick --hidden-page --e
32441 pts/5    Sl     0:00 /opt/atom/atom /opt/atom/resources/app/src/task-bootstrap.js /home/florent/.atom/compile-cache /opt/atom/resources/app/node_modules/spell-check/lib/spell-check-handler.js
32458 pts/5    S      0:00 /bin/bash /opt/atom/resources/app/apm/bin/apm outdated --json --compatible 1.19.0 --no-color
32482 pts/5    Sl     0:00 /opt/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=C4896AFFE1F3F136D5DD3CD1F4B662AD --lang=en-US --app-path=/opt/atom/resources/app --node-integration=true --hidden-page --enable-pinch --num-raster-threads=1
32543 pts/5    S+     0:00 grep --color=auto atom
```
Now with Atom 1.19.0, with GPU acceleration, it still works
```
# atom                                                                                                                                                      
# ps aux | grep atom                                                                                                                                        
 1122 pts/5    S      0:00 /bin/bash /usr/bin/atom
 1128 pts/5    Sl     0:01 /opt/atom/atom --executed-from=/home/florent --pid=1111
 1144 pts/5    S      0:00 /opt/atom/atom --type=zygote --no-sandbox
 1225 pts/5    Sl     0:02 /opt/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=FB245BB85C91E29DB00A924133D267CD --lang=en-US --app-path=/opt/atom/resources/app --node-integration=true --disable-blink-features=Auxclick --hidden-page --e
 1272 pts/5    Sl     0:00 /opt/atom/atom /opt/atom/resources/app/src/task-bootstrap.js /home/florent/.atom/compile-cache /opt/atom/resources/app/node_modules/spell-check/lib/spell-check-handler.js
 1288 pts/5    S      0:00 /bin/bash /opt/atom/resources/app/apm/bin/apm outdated --json --compatible 1.19.0 --no-color
 1331 pts/5    Sl     0:00 /opt/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=41216248EB1970AB70BAEC0CD655EED6 --lang=en-US --app-path=/opt/atom/resources/app --node-integration=true --hidden-page --enable-pinch --num-raster-threads=1
```
