### ISSUE TITLE
Atom GUI corrupted when run in VirtualBox within LinuxMint guest

### ISSUE THREAD

**Issue by james-noaa** [atom/atom#12570]
Should be simple to reproduce:

- Create LinuxMint 17.3 (tried KDE) or 18 (tried Cinnamon) guest in VirtualBox (v.5.1.4)
- Make sure equal version of VirtualBox guest additions are installed
- Install any version of Atom greater than 1.8 (1.8 does not exhibit the error), including 1.11.0-beta0
- Start Atom

You should see the mostly-blank/corrupted GUI upon startup.
This also happens in safe mode.

**Comment by 50Wliu** [comment]
This is a bug in VirtualBox.  You have a couple of options here:
1. Disable 3D acceleration
2. Downgrade Guest Additions to 5.0.16
3. Set `LIBGL_ALWAYS_SOFTWARE=1` within the VM

**Comment by james-noaa** [comment]
Thanks for the quick response and options.
Can you point me to some bug details that I can pass on to the VirtualBox folks, so we can pester them to fix whatever it is?

**Comment by 50Wliu** [comment]
So I took those tips from a similar issue where Atom would always stay on top no matter what and extrapolated it to this one, as we've seen a few cases of UI corruption when running Atom in VirtualBox that were fixed the same way.

Here's the issue if you want to look at it: #11574

(In addition, here's an already-open bug report for the always-on-top bug: https://www.virtualbox.org/ticket/12738)

**Comment by james-noaa** [comment]
Thanks. FYI:
I tried prefixing my Atom shortcut like so:
env LIBGL_ALWAYS_SOFTWARE=1 /usr/share/atom/atom %U
and alternatively set that env variable for my KDE session by creating a file ~/.kde/env/3d.sh containing:
export LIBGL_ALWAYS_SOFTWARE=1
and alternatively set it in /etc/environment
mostly based on [this](http://superuser.com/questions/106056/force-software-based-opengl-rendering) and none had any effect on the problem.

Unfortunately, regressing to a previous minor version of VB guest additions is obviously going to cause other issues, and only more so over time.

However, I did try disabling 3D acceleration in the VM (VirtualBox) config, and that _did_ return Atom's GUI to it's normal appearance. So there's that. :)

**Comment by trainerbill** [comment]
So whats up with this?  I am on vbox 5.1.6 and can't downgrade to 5.0.16 guest additions.  I updated to ubuntu 16.04 and latest atom and still have this issue.  Literally cannot do anything and may have to switch to a new IDE.  disabling 3d acceleration makes the entire VM slow to a crawl.

**Comment by bryantrobbins** [comment]
@trainerbill , was there something other than the VirtualBox version that was keeping you from trying the 5.0.16 Guest Additions?

The ISO for 5.0.16 Additions is here:
http://download.virtualbox.org/virtualbox/5.0.16/VBoxGuestAdditions_5.0.16.iso

Just installed these into a CentOS guest on VirtualBox 5.1.8 with no issue, and can confirm as well that it fixes the Atom-related issues while keeping 3D acceleration enabled.
