### ISSUE TITLE
Constant Crash on Ubuntu, reproducable

### ISSUE THREAD

**Issue by cyphunk** [atom/atom#12832]
_Update: reproduction steps described below. problem appears related to the hover bubble over files  in the file tree._

After some time of running `atom --safe` (1.10.2) it crashes. The nature of the crash is that the window remains open but when I resize the window the canvas does not update. I am no longer able to scroll in the tabs open or do anything with atom other than forcefully quit it. The system I am running on in Ubuntu 14.04.4LTS with Gnome 3.12.2.

I've had this issue consistently through various atom versions. Because atom does an okay job in recovering the previous open state, and because most of my projects involve git which means I'm saving a lot, it doesn't bother me too much. But often I'll get frustrated and update my atom (compiling from latest stable) in hopes it is fixed. 

I would love to figure out how to reproduce this but I haven't found it yet. It seems to happen only when I'm working on a tree of files, and have a few tabs open at least. Then after about 10 or 15 minutes I will be scrolling and it will lock up.

**Comment by 50Wliu** [comment]
In the future, please **completely** fill out the provided issue template - it's there for a reason.

Some questions for you:
* What is the output of `atom --version`?
* Would you say that the "crash" is more of a "Atom stops responding" issue?
* Has the freezeup only happened while you were scrolling, or has it happened at other times as well?

**Comment by cyphunk** [comment]
Thanks for the response

Output of atom --version
```
Atom: 1.10.2
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
```

Today while keeping a close eye on it, it appears to only happen while scrolling. Just now I was able to crash by scrolling the file tree up and down, then right clicking on a file, then scrolling up and down again. It then crashed. Not sure if this is reproducable. I suspect the application needs to be open for a while for this to happen. Will report back again

**Comment by cyphunk** [comment]
actually i restarted with --safe now and it happened again. Perhaps one clue is that when it crashes I see a odd change in the file tree part... I suspect what you see here is the leftovers of a lost tool tip or file information tip that shows up on mouse over of file names.

![selection_083](https://cloud.githubusercontent.com/assets/119662/19006302/214ecb0a-875f-11e6-9dac-88a01e75d1e4.png)

**Comment by cyphunk** [comment]
Another clue: Normally on mouse over of a file name on my gnome setup the background of the is brown. When it locks up the background is black, as shown in the image. I'm now almost certain that the file info hover has something to do with the crash. This could be an issue in gnome? though this doesn't happen in other applications. Yet, who knows if I use many/any applications in gnome that also have a file list as that used in atom.

**Comment by cyphunk** [comment]
I can now reproduce this consistently.


1. open a directory in atom that has enough files or files in directories to require scrolling in the file tree
2. open as many of the sub directories up so their tries are in view
3. move with the mouse over some of the file names so that the name appears in a hover bubble for each as you move the mouse over them
4. with one file name still having it's name shown in a hover bubble over it, then scrill the whole tree 

this consistently causes atom --safe to crash on my system

**Comment by cyphunk** [comment]
could someone remove the "needs-reproduction" tag now that I've detailed how to reproduce? Or, does removing the tag require a core member check this? If the latter then ignore this request

**Comment by 50Wliu** [comment]
> Or, does removing the tag require a core member check this?

Correct.  I haven't been able to reproduce this on Windows.

**Comment by Ceda-EI** [comment]
Can you post your system specifications? What is the RAM consumption by the system? It may be due to a **slow system** or **little available RAM.**

**Comment by cyphunk** [comment]
It is definitely something with the Gnome window manager. (version 3.12) I have since switched to using a different window manager for a while (awseomwm) and the bug with atom io has not appeared.

**Comment by Ceda-EI** [comment]
I was unable to reproduce the issue. I however have a bit different versions `gnome - 3.18.5` `Atom 1.11.2`. Rest are same.

**Comment by Ceda-EI** [comment]
Did you try updating to newer versions of `gnome-shell` and `atom`? Does the problem exist with the latest version also?

**Comment by cyphunk** [comment]
I'm on latest atom. The problem has gotten worse with each new atom release over the years. Typically when I would get tired of the bug I would update atom only to find it is worse.

There is no newer version of gnome-shell for ubuntu 14.04lts. I started down the road of attempting to compile latest gnome for this distro but now two days later, it's clear if gnome is the issue it will be easier to backup and move over to a different distro with later gnome.

**Comment by cyphunk** [comment]
This bug from Chrome relating to gnome 3.12+ubuntu 14.04 seems pretty much the same: https://bugs.chromium.org/p/chromium/issues/detail?id=381732#c14

**Comment by cyphunk** [comment]
@Ceda-EI upgraded the host to 16.04. Indeed the bug does not occur there (with gnome 3.18). Wouldn't recommend this solution to anyone though. 14.04lts to 16.04lts has issues. 

@50Wliu thanks

**Comment by Ceda-EI** [comment]
Since the issue is solved, it should be closed.

**Comment by 50Wliu** [comment]
It's not solved yet per-say as other users on Ubuntu 14.04 will still run into this issue.  This issue will be closed when the aforementioned Electron PR is merged.
