### ISSUE TITLE
Race between type-specific settings and third-party packages that update settings dynamically

### ISSUE THREAD

**Issue by danfuzz** [atom/atom#13141]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

This bug is about a bad interaction between Atom core and a third-party package, <https://github.com/jtokoph/auto-detect-indentation>. I've already filed a bug on the package, <https://github.com/jtokoph/auto-detect-indentation/issues/23>, but it occurs to me that a proper fix for this might involve changing Atom core as well, hence this report!

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The core code which manages per-type editor settings races with third-party code that also tries to manage editor settings. This can lead to surprising / counterintuitive results.

I ran into this with the `auto-detect-indentation` package, which tries to manage the settings of `softTabs` and `tabLength`. The steps-to-repro below are with respect to that package, and you can refer to the bug I mentioned above for a description of what I'd expect to be the interaction between the core's idea of per-type settings and what the package is trying to achieve.

I _think_ the problem boils down to the fact that <https://github.com/atom/atom/blob/master/src/text-editor-registry.js#L333-L343> often (always?) ends up running _after_ third-party packages are `activate`d (or something along those lines). In addition, it may make sense to distinguish the act of calling `editor.update` as "action taken by the core" vs. other reasons. In this case, the package in question might want to behave differently in these different cases. (But please take this all with a big grain of salt, as I'm not super-familiar with the Atom codebase.)

### Steps to Reproduce

1. Install the package `auto-detect-indentation`.
2. Put the following in your `config.cson`:
   
   ```
   ".js.source":
    editor:
      tabLength: 8
      tabType: "hard"
   ```

3. Open up a `.js` file with blatant two-space indentation.

**Expected behavior:**

The editor is set to two-space indentation.

**Actual behavior:**

The editor is set to eight-space hard tab indentation. If you watch carefully, you can sometimes see the indentation status briefly flash "2 Spaces" before getting thwacked to "Tabs (8 wide)".

### Versions

```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.3.8
```

macOS 10.11.6

**Comment by 50Wliu** [comment]
This has been fixed in the 1.12 betas.

**Comment by danfuzz** [comment]
I just got 1.12, and near as I can tell the problem still exists.

**Comment by danfuzz** [comment]
Here's a screencap to show you what I'm talking about. Look at the "8 Spaces" bit of status as the files get selected.

![fighting-tabs](https://cloud.githubusercontent.com/assets/1090235/20161139/3a0f480c-a6a1-11e6-8007-0482dda53933.gif)

**Comment by 50Wliu** [comment]
The issue that was fixed in Atom was the scoped setting not being respected and being changed back to the default value.  If you're still experiencing an issue then I'd say it's entirely the community package's fault.

**Comment by danfuzz** [comment]
First and foremost, thanks for the reply.

I really do think that in order for the community package to work properly, it needs a modicum of support from the core. Please see the original description, but to recap: It looks like the community package is doing what it should to change the tab/indent settings, and the core is overriding it. That is, if you use per-type settings (a core feature), then I think it is impossible to _also_ have a community package that tries to do anything with those settings.

In this case, my expectation is that the per-type settings would provide a default, and the community package in question might selectively override them. However, what is happening in practice is that the community package _tries_ to override the settings, and the core thwacks them back.

**Comment by tofof** [comment]
+1

**Comment by 50Wliu** [comment]
Tentatively reopening.
