### ISSUE TITLE
RPM Install: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Yajo** [atom/atom#13176]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Updated Atom by official RPM.

### Steps to Reproduce

1. Open Atom.

**Expected behavior:** Atom opens

**Actual behavior:** `/usr/share/atom/atom: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

### Versions

`atom --version` returns nothing.

```
$ rpm -q atom
atom-1.12.0-0.1.x86_64

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
```

Fedora 24 Linux 4.8.4-200.fc24.x86_64 #1 SMP Tue Oct 25 13:06:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Workaround

```
$ pkcon install libXScrnSaver
```

... so, it seems this dependency is missing in last RPM.

**Comment by r17n** [comment]
I was able to reproduce this bug in my environment.
Running Fedora 24.1.2 in a VM. Fresh VM install. 
The workaround worked.

**Comment by r04r** [comment]
Experiencing this on CentOS 7 as well. Running `yum install libXScrnSaver` works there as a workaround.

**Comment by victormln** [comment]
Perfect. Problem solved with `pkcon install libXScrnSaver` in Fedora 24 64bits.

**Comment by thomaskuntzz** [comment]
Same problem with a fresh atom install in a fresh [solus](https://solus-project.com/).
Solved with `eopkg install libxscrnsaver`.

**Comment by carguello** [comment]
Yeah, that was mentioned in Solus Telegram group

**Comment by friendOfOurs** [comment]
On Fedora 25 it doesn't work even after installing libXScrnSaver. Still getting the message:
error: Failed dependencies: libXss.so.1 is needed by atom-1.13.1-0.1.x86_64

**Comment by Philipp-Borchert-ISH** [comment]
On CentOS 7.3 x86_64 I was able to solve it by installing both "libXScrnSaver" and "libXScrnSaver.i686" packages. Might also help for Fedora 25?

**Comment by tolisp** [comment]
@Philipp-Borchert-ISH I confirm that i was able to install atom 1.13.1 in Fedora 25 KDE using your workaround (adding libXScrnSaver.i686 did the trick)

**Comment by DarkMatterMatt** [comment]
For those finding this thread via Google (like I did), the Crouton/Debian fix is `sudo apt-get install libxss1`. There are no packages matching the glob `*XScrnSaver*`.

**Comment by InnovativeInventor** [comment]
Just as a note - this is still a problem and I had to fix it by following DarkMatterMatt's recommendation.

**Comment by Arcanemagus** [comment]
This was already fixed in RPM based distributions in https://github.com/atom/atom/pull/13289, and was fixed in Debian based distributions like Ubuntu in https://github.com/atom/atom/pull/16812, which is included in Atom v1.26.0-beta0 😉.

**Comment by ptc-trbiggs** [comment]
This is still a problem on Amazon Linux.  There are no packages called libXScrnSaver, libXScrnSaver.i686, or libxss1 to install.  Anyone know how I can fix this?

**Comment by deeptgoyal** [comment]
Try this:
dnf remove libXScrnSaver

dnf install libXScrnSaver

it worked for me.

**Comment by michel-t-86** [comment]
Removing libXScrnSaver and readding it worked for me.
