### ISSUE TITLE
Mac OS X: Restart and Install Update fails 1.11.2 -> 1.12.1

### ISSUE THREAD

**Issue by jheasly** [atom/atom#13188]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Update gets downloaded, but when "Restart and Install Update" is selected, the restart doesn't happen.

### Steps to Reproduce

1. Start Atom
2. Wait for update to download.
3. Select "Atom" -> "Restart and Install Update"

**Expected behavior:** Restart and installation of update

**Actual behavior:** No restart

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 1.8.0
Mac OS X 10.9.5

Error log lines:
![screenshot 2016-11-10 15 42 46](https://cloud.githubusercontent.com/assets/96007/20199451/58d9e6d4-a75f-11e6-97e6-fbed2857a2c9.png)

**Comment by killuaDev** [comment]
This also happens for me

**Comment by jheasly** [comment]
@killuaDev A workaround: Copying the Atom.app from `../com.github.atom.ShipIt/update.[id]/` to my `Applications` directory worked.

**Comment by killuaDev** [comment]
thanks

**Comment by iamed2** [comment]
This happened for me as well.

**Comment by amyrlam** [comment]
Same issue, 1.11.2 to 1.12.5.

Update gets downloaded, but when "Restart and Install Update" is selected, the restart doesn't happen. The update doesn't happen. 

Followed debugging guide with no luck.

//

@jheasly Could you clarify your copying Atom.app workaround...where is the source from?

**Comment by jheasly** [comment]
@amyrlam Look in `/Users/[yourusername]/Library/Caches/com.github.atom.ShipIt/update.[7-character ID]/` and there should be an `atom-mac.zip` in there. Drag that to your `/Applications` directory.

**Comment by jheasly** [comment]
Worked when updating from 1.12.4 -> 1.12.5. Closing.

**Comment by amyrlam** [comment]
@jheasly thanks, I don't have the file there, only this directory with no zips inside: `/Users/[myusername]/Library/Caches/com.github.atom` Not sure what to do, if you have any other ideas lmk, otherwise will open a new issue.

**Comment by jheasly** [comment]
Ah! Okay. Left out the part where you have to go to the `Atom` menu and there should be option about `Download Update` or somesuch if the `atom-mac.zip` hasn't yet been downloaded. Select it and then once the option changes to `Restart and Install Update` then go look in that location. It should be there then.

**Comment by amyrlam** [comment]
Yeah just tried re-downloading the update, nothing is there...it's strange that I have the `com.github.atom` directory but not `com.github.atom.ShipIt/`. Anyways, thanks for trying!

**Comment by jheasly** [comment]
@amyrlam One last(?) idea. Okay, so the restart isn't happening, right? After it doesn't restart, open up the Console app in your Utilities directory then in the upper, righthand corner, type "Atom" in the Filter window and you'll see just the Atom-related log messages. Some will have the path that the upgrade was downloaded to and failed to get moved from. Give that a shot.

**Comment by amyrlam** [comment]
@jheasly thanks didn't know about that. Didn't give me any info re: the zip file location but ... I'll try the instructions for full atom uninstall / reinstall.

**Comment by jheasly** [comment]
@amyrlam It seems fixed in 1.12.5 so hopefully the re-install will fix.

**Comment by amyrlam** [comment]
@jheasly sorry for the delayed response, I [completely uninstalled](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084) then reinstalled Atom, and things seem ok now. Thank you again!

**Comment by yusufhm** [comment]
For anyone still having the issue or stumbling on this after looking up on Google, I found the downloaded Atom zip file at this location: `~/Library/Application Support/com.github.atom.ShipIt`.
