### ISSUE TITLE
Atoms locks CPU when started from command line.

### ISSUE THREAD

**Issue by hickscorp** [atom/atom#13208]
~**Update** I think this is the same problem as https://github.com/atom/atom/issues/13192. I didn't initially see it, but using different keywords to search showed it.~

### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Since yesterday, whenever I start Atom using my `atom` command, it locks the CPU and doesn't start.
When `top`ing, I can see a process `zsh -ilc command env` running 100% CPU. Once I kill this process, Atom starts.

- It is worth noting that `atom --version` or other command line flags that wouldn't start Atom's UI don't show that issue.
- It might also be worth mentioning: if atom is already running, running `atom somefile` works, and it opens the file in the running instance.
- When an instance is already running, running `atom somedirectory` opens a new atom window without problem as well.

I tried deleting the whole `~/.atom` folder. The problem persists. Tried disabling packages, same thing.

### Versions

I'm on Xubuntu 16.10. I remember some updates to my system yesterday... Might be related?

```
Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

```
#> lsb_release --release --codename --version
No LSB modules are available.
Release:	16.10
Codename:	yakkety

#> cat /etc/issue
Ubuntu 16.10 \n \l
```

**Comment by nicolargo** [comment]
Same issue for me.

**Description**

If i start Atom from my terminal, it pick 100% of my CPU and Atom did not starts:

![selection_269](https://cloud.githubusercontent.com/assets/776747/20239158/2e7b2c1c-a8fa-11e6-96b8-e5ff7fb51432.png)

If i kill this bash process, Atom starts...

Additional note: if i start Atom from my Gnome menu, no issue...

**Version**

I'm on Ubuntu 16.04.

Atom: 1.12.1

**Comment by nicolargo** [comment]
Nervermind: corrected by updating to 1.12.2

**Comment by Ben3eeE** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/13084 which has been fixed in Atom 1.12.2.

**Comment by hickscorp** [comment]
@Ben3eeE I'm sorry, but this is still happening in 1.12.3, with a slight twist: instead of not letting Atom start, that same pesky CPU locking routine is still running but in the background, so it was unnoticed.

This please reopen this issue.

**Comment by 50Wliu** [comment]
@hickscorp If you are using the webud8 PPA please uninstall Atom and reinstall from https://atom.io. The webupd8 distribution is unofficial and is messing with Atom's launch scripts, which is why you're still seeing this.

See https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md for more information

If you are not, then please open a new issue.  Thanks!

**Comment by Proberts** [comment]
Using @50Wliu suggestion, this fixed the problem for me under Mint 17.2 (thanks)

just noting: 

- Exiting atom doesn't kill the shells (one per physical core?) using 100% CPU. You must explicitly kill the shells by pid or exit the shell from which you originally started atom.
- webupd8's atom package did not cleanly uninstall from the Software Manager GUI (hung at 99%) - it did uninstall with apt-get remove.
