### ISSUE TITLE
Running atom in Ubuntu (x86), after build + install,  throws 'Syntax error: Unterminated quoted string'

### ISSUE THREAD

**Issue by nelson6e65** [atom/atom#13226]
### Description

I build atom from sources **1.10.0**, **1.12.1**, and **1.12.2**. Build .deb and the install via package manager in Ubuntu.

Then, after successful installation, I run `atom .` and I get this error:
```
nmartell@oficina-desktop:~$ atom .
nmartell@oficina-desktop:~$ /usr/share/atom/atom: 1: /usr/share/atom/atom: ELF: not found
/usr/share/atom/atom: 1: /usr/share/atom/atom: Syntax error: Unterminated quoted string
```

Version `1.10.0` was previously installed, then I build `v1.12.2` to upgrade, but I got that problems. Now I can't even install the `v1.10.0`. :cry: 

### Steps to Reproduce

1. Run `script/build ----create-debian-package` in order to build atom.
2. Install the resulting *.deb
3. Run `atom .` to open editor.

**Expected behavior:** Open Atom Editor

**Actual behavior:** Throws this error: `/usr/share/atom/atom: 1: /usr/share/atom/atom: ELF: not found
/usr/share/atom/atom: 1: /usr/share/atom/atom: Syntax error: Unterminated quoted string`

### Versions

```
nmartell@oficina-desktop:~$ atom --version
nmartell@oficina-desktop:~$ 
```

> (Yes, nothing)

```
nmartell@oficina-desktop:~$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3
```

```
nmartell@oficina-desktop:~$ node --version
v4.6.2
```

```
npm --version
3.10.9
```

**Comment by Ben3eeE** [comment]
There was a problem with building Atom for 32bit Linux that was fixed in https://github.com/atom/atom/pull/13001. I believe this fix is currently only in beta. Try either building beta or build Atom with this PR. Sorry for the inconvenience.

**Comment by nelson6e65** [comment]
I manual remove 'atom' references after uninstall ( #2195) and then I was able to install old version `v1.10.0` for the meantime.

Thanks, @Ben3eeE I'll wait to upgrade in the next `v1.13.0` release.

**Comment by nelson6e65** [comment]
I'm still not able to run in x86 for atom `1.12.7`. u.u

This time from Fedora 24:
![screenfetch-building-atom-1 12 7](https://cloud.githubusercontent.com/assets/9272498/21272645/85009336-c396-11e6-9101-8ea254de76e5.png)

**`script/build --create-rpm-package`**:

```sh
Node:	v4.7.0
Npm:	v4.0.5
Installing script dependencies
Installing apm
../deps/libgit2/deps/zlib/inflate.c: En la función ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: aviso: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
../deps/libgit2/deps/zlib/inflate.c: En la función ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: aviso: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.52.0 ✓
Installing atom-light-syntax@0.28.0 ✓
# . . .
Installing language-yaml@0.27.1 ✓
Wrote Dependencies Fingerprint: /home/nmartell/src/atom-1.12.7/node_modules/.dependencies-fingerprint a9bde3eb677ce25a725e258539ffdd1af43f7481
Copying assets to /home/nmartell/src/atom-1.12.7/out/app
Transpiling Babel paths in /home/nmartell/src/atom-1.12.7/out/app
Transpiling CoffeeScript paths in /home/nmartell/src/atom-1.12.7/out/app
Transpiling CSON paths in /home/nmartell/src/atom-1.12.7/out/app
Transpiling PEG.js paths in /home/nmartell/src/atom-1.12.7/out/app
Generating module cache for /home/nmartell/src/atom-1.12.7/out/app
Generating pre-built less cache in /home/nmartell/src/atom-1.12.7/out/app/less-compile-cache
Generating metadata for /home/nmartell/src/atom-1.12.7/out/app/package.json
Generating API docs at /home/nmartell/src/atom-1.12.7/docs/output/atom-api.json
Skipping Chromedriver download because it is used only on macOS
Dumping symbols in /home/nmartell/src/atom-1.12.7/out/symbols
Running electron-packager on /home/nmartell/src/atom-1.12.7/out/app with app name "atom"
Downloading electron-v1.3.13-linux-x64.zip
[============================================>] 100.0% of 42.63 MB (33.37 kB/s)
Packaging app for platform linux x64 using electron v1.3.13
Changing permissions for node files in /home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386
Copying non-ASAR resources to /home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386/resources
Writing LICENSE.md to /home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386/resources
Application bundle created at /home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386
Skipping creating debian package. Specify the --create-debian-package option to create it.
Creating rpm package for "/home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386"
Creating rpm package directory structure at "/home/nmartell/rpmbuild"
Copying "/home/nmartell/src/atom-1.12.7/out/atom-1.12.7-i386" to "/home/nmartell/rpmbuild/BUILD/Atom"
Copying icons into "/home/nmartell/rpmbuild/BUILD/icons"
Writing rpm package spec file into "/home/nmartell/rpmbuild/SPECS"
Writing desktop entry file into "/home/nmartell/rpmbuild/BUILD"
Copying atom.sh into "/home/nmartell/rpmbuild/BUILD"
Generating .rpm package from "/home/nmartell/rpmbuild"
Copying "/home/nmartell/rpmbuild/RPMS/i686/atom-1.12.7-0.1.fc24.i686.rpm" into "/home/nmartell/src/atom-1.12.7/out/atom.i686.rpm"
```


Why Downloading `electron-v1.3.13-linux-x64**.zip` (**x64**)?

**Comment by Ben3eeE** [comment]
The PR you referenced should fix the issue of downloading the incorrect Electron version but I believe it is only available in Atom 1.13.0 still only in beta and you are building Atom 1.12.7. Did you try to build with the changes in that PR?

**Comment by nelson6e65** [comment]
No. I'll try with `1.13.0-beta8`. Thanks.

**Comment by nelson6e65** [comment]
It works `atom-beta` 1.13.0.

**Comment by Ben3eeE** [comment]
Great to hear that it's working for you 🙂
