### ISSUE TITLE
Code folds are not restored after closing Atom

### ISSUE THREAD

**Issue by david02871** [atom/atom#13258]
I am finding that after closing Atom and re-opening my session and tabs are restored by code folds are not.

I am writing a lot of functions and I do not need to see all of my code all the time so I depend on code folding to make things manageable.

Code folding does not make things easier for me if I have to go through and re-close every function each time I open Atom before I can begin.

Should folds be remembered? I can't see any mention of this in the documentation so I am not sure if it is a bug or a missing feature.

I am aware of the remember-folds package but this only saves folds when opening and closing tabs - not closing and restoring Atom.

**Comment by Ben3eeE** [comment]
I can reproduce this on `Atom 1.14.0-dev-9c73ae0 Electron 1.4 branch`, Windows 10 anniversary x64. See gif where I have some folds reload Atom and none of them are restored. Then I add three others and switch tabs before reloading and 2 of them are restored.

![code folds 2](https://cloud.githubusercontent.com/assets/1058982/20444885/2bcb8a6a-add3-11e6-8e9d-3f52cc877bf6.gif)

**Comment by Quilljou** [comment]
Same issue on mac os sierra, Atom 1.12.5.
I have unchecked the option 'open empty editor on start', and I found the `storage/application.json` will be empty after you closed atom, even though there are some folder is opened;

**Comment by adsfgg** [comment]
I can also confirm that this happens on Atom 1.12.6.

**Comment by muchweb** [comment]
Duplicate of #247?

**Comment by Kycko** [comment]
I have the same issue on Archlinux and Atom 1.17.2

**Comment by carmelocatalfamo** [comment]
Same issue on Mac OS Sierra 10.12.6, Atom version 1.20.1

**Comment by Arcanemagus** [comment]
This is fixed for me in v1.24.0-beta0.

**Comment by 50Wliu** [comment]
Yup looks like this is fixed in Atom 1.24 :tada:.

**Comment by jrial** [comment]
Has this been un-fixed in 1.25? Because that's the one I'm running, and I'm still hitting this.

**Comment by jrial** [comment]
OK, definitely still happening in 1.25. See animation below.

1. At the start, lookup_requester_email is folded, nothing else is.
2. I then also fold the first two functions.
3. I close Atom with CTRL+Q
4. I launch Atom again. Note that it starts with the folded functions neatly folded, so it does remember the folding.
5. For some inexplicable reason, it then unfolds everything, even the one method that was initially folded.

No idea what's going on. Instinct tells me it's some package interfering, but it doesn't _always_ do this.

![output](https://user-images.githubusercontent.com/570247/37715111-78371ce8-2d1b-11e8-810d-5c71961d2169.gif)

**Comment by Arcanemagus** [comment]
Can you try with [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) to ensure it isn't a community package interfering?

I notice that you have `linter` installed, my _guess_ would be that one of your providers is running an automated fix on the code (which would re-write the contents, invalidating the folds).

**Comment by jrial** [comment]
It is indeed a community package, [Hydrogen](https://atom.io/packages/hydrogen). I'll check their issues list, and create a new issue if necessary.

**Comment by jrial** [comment]
OK, after some more testing, turns out it wasn't Hydrogen after all. But I'm having a hard time figuring out what's going on, and was wondering if anyone had some pointers.

I'm now able to reproduce it simply by disabling/enabling certain community packages:
1. I fold some blocks
2. I disable and re-enable the package in question
3. I switch back to the editor, and find my code unfolded again.

The odd thing is, these packages shouldn't _do_ anything. The packages in question are [atom-django](https://atom.io/packages/atom-django) and [language-django](https://atom.io/packages/language-django). I don't understand why these would cause the folds to unfold, since they're simple Textmate bundle converions which merely contain snippets and grammars.

Animation:

![output](https://user-images.githubusercontent.com/570247/37775018-0bb4e0b0-2de2-11e8-81f5-cb6d1b999ac1.gif)

**Comment by jrial** [comment]
Seems you're onto something, Arcanemagus. I just reproduced this with language-python, which is a core package. And which also happens to be a Textmate bundle conversion (not sure that matters, but it's another common data point).

Whether I restart Atom between disabling and re-enabling language-python or not has no effect: in both cases the code gets unfolded.

Repeatedly restarting with only language-python enabled preserves the folds though. It's only when I throw another language package that operates on the same files in the mix that it behaves erratically. It doesn't _always_ unfold, but most of the time it does. Enabling/disabling tree sitter parsers also has no effect.
