### ISSUE TITLE
Indent width is set to 4 when atom is started or sometimes when file is just opened, but switching to another tab and back sets it back to 2

### ISSUE THREAD

**Issue by Goury** [atom/atom#13428]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

So I set my indents for my python to be tabs with width of 2.
So far it worked fine (I was on 0.9–1.2) and then I decided to update to 1.12 and boom! When I start Atom, all the tabs in the active file are 4 things wide. And some times when I open some file.
But, once I click some other tab and back, tabs are shrunk back to width of 2, as it should.

This is a little annoying.

### Steps to Reproduce

0. Set tab width for python to 2 and set it to always use tabs and never use spaces for indentation
1. Have some python file opened before closing Atom
2. Close Atom
3. Start Atom again
4. ...
5. Profit!

**Expected behavior:** tabs width to be always 2

**Actual behavior:** tabs width is 4 for a moment, then it becomes 2

### Versions

Tried with Atoms of 1.12.6, 1.12.7 and 1.13.0-beta8
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
Up-to-date Ubuntu 16.04 with Unity 7

**Comment by Goury** [comment]
Yes, python file is properly indented with tabs, of course.

**Comment by 50Wliu** [comment]
I believe this has been fixed in Atom 1.13.

**Comment by Goury** [comment]
Okay, I'll try it some day, thanks

**Comment by Goury** [comment]
So I tried 1.13.0-beta8
Nope, bug is still present

@50Wliu 
Seems you have to open this issue back

**Comment by 50Wliu** [comment]
What is the output of `atom --version`?

**Comment by Goury** [comment]
atom --version says:
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

atom-beta --version says:
```
Atom    : 1.13.0-beta8
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by AndreaGriffiths11** [comment]
@50Wliu Did you have a chance to take a look at this?

**Comment by 50Wliu** [comment]
I didn't attempt to reproduce.

**Comment by Goury** [comment]
Still present in 1.14.3

```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by parasyte** [comment]
This looks like a duplicate of #13141 which was mentioned on https://github.com/jtokoph/auto-detect-indentation/issues/25

**Comment by Goury** [comment]
@50Wliu I can confirm opposite.
I don't see auto-detect-indentation in Edit→Preferences→Packages
nor do I remember ever installing it.
