### ISSUE TITLE
Atom can't save over hidden files

### ISSUE THREAD

**Issue by HUN73R13** [atom/atom#13538]
### Info
**OS:** Windows 10 64-bit
**Atom Version:** 1.12.8

### Description
Atom can't save over hidden files

I have some hidden files (.js .css etc..) I'm able to open and edit them but once I try to save changes I get a message saying: **"Unable to save file <path to my file> - EPERM: operation not permitted, open  <path to my file>"**

the files are just hidden and NOT set to "Read-only", once I unhide the file I can save it just fine.

is this a bug or is it an expected behavior and if so, why?

**Comment by npoirey** [comment]
Same problem, can only save when the file is not hidden
windows 10 pro 64bits build 14393.693 (fresh install)
atom 1.13.0 ia32

**Comment by lee-dohm** [comment]
@50Wliu Would you mind adding some steps to reproduce the problem here?

**Comment by MaherFa** [comment]
added steps to reproduce

**Comment by settenop** [comment]
I can reproduce it.
I've also tried to write on a file from the node's terminal and I can't.
The bug seems to be related to node js.
> fs.writeFile(".\\\visible.txt", "Hello world!")
undefined
> fs.writeFile(".\\\hidden.txt", "Hello cruel world!")
undefined
> Error: EPERM: operation not permitted, open 'C:\Users\sette\Desktop\BUGWORKING\hidden.txt'
    at Error (native)

atom --version
Atom    : 1.16.0-dev-c4abeba
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by MaherFa** [comment]
nice find @settenop!
possible solution (without waiting for node js' fix) is to check attributes of the destination file before writing and changing them to fit the writeFile than change them back.

Notepad++ does this optionally with "read-only" files, it saves an extra step and doesn't interrupt the workflow.

**Comment by southbanksoftwaredeveloper** [comment]
Please fix this. So annoying

**Comment by guiguan** [comment]
Please fix this. So annoying

**Comment by hmaarrfk** [comment]
Still a bug. I guess I just changed the file from hidden to not hidden.

**Comment by naefp** [comment]
I have the same problem. Please allow to write to hidden .gitignore file.

**Comment by gosukiwi** [comment]
@sadick254 I think this might be related to [TextBuffer's `saveAs`](https://github.com/atom/text-buffer/blob/cface8833b12d1922b0919ab1002dd7b42763627/src/text-buffer.js#L1899)? Maybe it should check for hidden files and do like @MaherFa suggested, changing the attributes while writing, and then swapping them back.

If that's the case I can give it a shot and see if I can add a fix there.

**Comment by sadick254** [comment]
Hey @gosukiwi . Thanks for showing interest in this. I think the solution @MaherFa is suggesting is workable. Give it a shot I will be happy to review the PR.

**Comment by gosukiwi** [comment]
Huh, I'm really at a block here. I'm certain [TextEditor#save](https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/text-editor.js#L1330) gets called (I was able to debug it), and `this.buffer` in that line is a `TextBuffer`, yet when I clone the `text-buffer` package and add a `console.log` in the `save` method, it doesn't show up. I tried even adding a `console.log` in the constructor, and still doesn't work. The funny thing is I added a `console.log` outside the class and that one does show up.

I'm not sure what I'm doing wrong. I cloned the repo and linked it with `apm link -d`. By the way, I also had to run `apm install` every time I made a change so Atom in dev mode would pick them up. Maybe I'm doing something wrong here.

By the way @sadick254, looks like checking if a file is hidden or not is not trivial, particularly in Windows. Would you be willing to add the [hidefile](https://www.npmjs.com/package/hidefile) dependency?

**Comment by Aerijo** [comment]
> particularly in Windows

Only in Windows. Linux and macOS don't have hidden files in the first place. It is only convention to treat files with a leading `.` as hidden.

> I clone the text-buffer package

Are you referring to the [text-buffer repo](https://github.com/atom/text-buffer)? I don't think it's a package. You'd have better luck replacing the dependency in  Atom's [`package.json`](https://github.com/atom/atom/blob/b4a530c23eab32424cd1ef7e610eb099146f52e0/package.json#L160) with your local copy. Because of the snapshot creation and possibly other things you may need to rebuild Atom each time you want to test a change. I haven't looked into it much though (and are you saying it does actually work to link with `apm` when you run `apm install`?).

**Comment by gosukiwi** [comment]
> Only in Windows. Linux and macOS don't have hidden files in the first place. It is only convention to treat files with a leading . as hidden.

Ahh I see, thanks for clarifying that

> Are you referring to the text-buffer repo? I don't think it's a package. You'd have better luck replacing the dependency in Atom's package.json with your local copy

Oh I'll give that a shot. I tried linking it and it was kind of working, at least it displayed the text when it was loaded up, but I don't think that code was being used. I'll try again updating the `package.json` :) Thanks!

**Comment by gosukiwi** [comment]
Thanks guys! After some struggle, I was able to make [a PR](https://github.com/atom/text-buffer/pull/331) to fix this issue.

**Comment by gosukiwi** [comment]
Should we close this now that it has been addressed by https://github.com/atom/text-buffer/pull/331?

**Comment by sadick254** [comment]
@gosukiwi we should wait until we pull in `text-buffer` version `13.18.0`

**Comment by languagedan** [comment]
Hi everyone,

Thanks for the effort to resolve this issue.

Brief intro: I'm a non-developer who uses Atom for writing, not for coding.

I am writing to report that as of today, Atom is still unable to save Hidden files on my machine. I'm using a brand new laptop running Windows 10 with very little software installed. Downloaded Atom a few days ago only. After lots of trial-and-error, I found that Atom's inability to save certain files was due to those files being Hidden. 

If I unhide the file, saving works fine. If I change the property on the file to Hidden, Atom refuses to save the file. Simple as that.

I'm migrating my team to Atom as we intend to version control our content. Hope this issue can be resolved. 

Thank you

**Comment by N1KN1M** [comment]
I notice that this is only an issue now when running atom via the provided shortcut, and not if we run atom from command line.

@languagedan for the time being, could you try launching atom from command prompt and see if you're able to save on hidden files? The command should be just 'atom'
