### ISSUE TITLE
When pending a restart for a new version install, the About page needs to indicate this

### ISSUE THREAD

**Issue by pydolan** [atom/atom#13996]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * **Note: DID NOT VERIFY (not sure how to reproduce):** Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

At certain times when Atom indicates a new version is available (via blue squirrel icon), the hover message on this icon is, *"An update will be installed the next time Atom is launched. Click the squirrel icon for more information."*  

But when I click the icon, the About page has no indication about a new version being installed on update.  Instead, this page should include the same message as shown in the squirrel icon hover.  As is, I did not notice the hover at first, clicked the icon, and just saw "Atom is up to date!", which is the opposite of what the squirrel icon is trying to convey.

Another related annoyance in this situation is that clicking the "Check now" for updates button reports that my outdated version is the latest version (e.g., "Version 1.14.4 is the latest version.")

### Steps to Reproduce

I'm not sure on how to reproduce consistently. At what point does Atom download the new version? Was that automatic?

**Expected behavior:** When Atom is pending a restart to install an update, indicate on the About page that this is the case, and provide a "Restart" button for easy restarting/installing.  Also, clicking the "Check now" for updates button should not say my outdated version is up to date.

**Actual behavior:** Atom's About page simply says, "Atom is up to date!" Clicking the "Check now" button says an outdated version is up to date.

**Reproduces how often:** Not sure

### Versions

```
$ atom --version
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.11
git 2.10.1

MacOS version 10.12.3
```

### Additional Information
n/a

**Comment by 50Wliu** [comment]
As I indicated on Slack (sorry for the late response), both of the issues should be fixed starting with Atom 1.16.0.  If they aren't, then please open new issues on [atom/about](https://github.com/atom/about).  Thanks!

**Comment by Ben3eeE** [comment]
This sounds like a duplicate of https://github.com/atom/atom/issues/8265 and this issue was not fixed when I tested the recent changes to the about package.
