### ISSUE TITLE
Atom not appearing on Start Menu (or anywhere) on Windows 10 after first install.

### ISSUE THREAD

**Issue by mjpierce7590** [atom/atom#14020]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom not appearing on Start Menu on Windows 10 after first install. Atom.exe does not exist anywhere on my system. The program, however, can be uninstalled through the control panel.

### Steps to Reproduce

1. Download and install Atom
2. Acknowledge and close the welcome window
3. Go to start menu and wonder why Atom is not there
5. Go to C:\users\me\.atom\ and wonder why atom.exe is not there
6. Go to C:\Program Files (x86)\ and wonder why atom.exe is not there
7. Go to Control Panel >> uninstall a program, and wonder why atom.exe is there
8. Restart computer
9. Repeat steps 3 through 7

**Expected behavior:** Atom in start menu.

**Actual behavior:** Atom not in start menu.

**Reproduces how often:** 100%

### Versions

atom does not work on command line. Latest version of Atom installed on 15 March 2017.

### Additional Information

I'm using a 2 month old laptop with minimal bloatware. The machine seems to be in pretty good shape.

**Comment by mjpierce7590** [comment]
I appreciate any help here. Thank you.

PS I really want to move over from Sublime Text 👍

**Comment by 50Wliu** [comment]
> Download and install Atom

Can you elaborate on this step?  In other words, can you walk me through what website you went to and what buttons you clicked to download and install Atom?

**Comment by mjpierce7590** [comment]
I went here: https://atom.io/
And clicked the "Download Windows 64-bit Installer" button.
(my computer is in fact 64-bit)

**Comment by 50Wliu** [comment]
Awesome, thanks.  Does the `%LOCALAPPDATA%\Atom x64` folder exist, and if so, does `app-1.15.0\atom.exe` exist?

**Comment by larduino** [comment]
Same issue here - loaded on windows 10 64 bit from Atom page . Now can't find a way or any sign on program. I reloaded it and still no sign of a way to start it or if it exists on computer. Did a search for atom.exe and came up with nothing.

**Comment by 50Wliu** [comment]
@larduino It would help if you could answer my questions above.

**Comment by larduino** [comment]
Okay - I found the atom.exe file here 
C:\Users\my user name \AppData\Local\atom\app-1.15.0\atom.exe
and I made a shortcut so I can start it up now. 
Thanks

**Comment by mjpierce7590** [comment]
Thanks to @larduino , that's exactly where my atom.exe is as well.

**Comment by damieng** [comment]
That is the expected location for Atom but it is supposed to have added a shortcut to your desktop and to your start menu.

Does your username have any unusual characters or spaces in it?

**Comment by mjpierce7590** [comment]
nothing unusual about my username

**Comment by eTorAken** [comment]
Hi,

I got the same problem. It could be related to my username (Clément) which needs UTF-8 recognition.

Hope this helps.

**Comment by damieng** [comment]
That could be part of it - we shell out to Squirrel's update.exe - it's possible some utf-8 encoding is getting mangled through the process.

**Comment by Vylcas** [comment]
Personally have had no problems. Just reinstalled it today and it's fine for me. You could always search the file directory for the launcher, right click, and select "create shortcut". It typically ask to go on the desktop but if not just grab the copy of the shortcut and drag+drop it to the desktop. @larduino seems to have done this so if you haven't yourself you can do so. Pretty simple but if you're still having problems let me know.

**Comment by wschwab** [comment]
I did just have the same issue with a standard, one-word username, though at least I could get past it with the above help (though I had to figure out that the version is now 1.17.0, not 1.15.0).

**Comment by corydeppen** [comment]
I'm having the same issue - Atom gets installed into `%localappdata%\atom` but no shortcuts are created anywhere. After uninstalling and reinstalling, a `app-1.18.0-beta2` folder gets created. My username is 6 alphanumeric characters, so that shouldn't be an issue. While it's confusing to know which `atom.exe` needs to run and what the target should be for a shortcut to the application (i.e. should it include any switches, etc), Atom starts after running `%localappdata%\atom\atom.exe`. It's just an annoyance to manually create shortcuts and I think it indicates the installer is still problematic since this doesn't happen with other apps. In fact, this appears to be similar to #12124 that was reported almost a year ago on Win7.

**Comment by ssimo3lsuhsc** [comment]
I am having the same problem on Windows 7. My username is all alphanumeric.

**Comment by kb1lqc** [comment]
I have this problem too. Atom was installed to `%localappdata%\atom` but nothing in start menu, program folder, etc.

**Comment by kb1lqc** [comment]
Somewhat of a workaround here is to add `%LOCALAPPDATA%\Atom` to the PATH environmental variable and then you can at least search for atom.exe in the start menu. Then I just pinned it to the start menu.

It would be awesome if this was cleaned up for a better user experience on Windows. Hopefully this helps!

**Comment by AllanKoaikJunior** [comment]
I'm also facing the same problem. I've uninstalled it and reinstalled a couples of times now still can't find it anywhere on my computer accept for the atom.exe which is located in my user folder.

**Comment by piyawill** [comment]
I also have this issue. I was able to find atom.exe in C:\Users\my user name \AppData\Local\atom\app-[version]\atom.exe

FYI

**Comment by Downes** [comment]
Just so you know. I also have this issue. I was able to find atom.exe in C:\Users\my user name \AppData\Local\atom\app-[version]\atom.exe

**Comment by damieng** [comment]
There is definitely a bug here but without Squirrel adding more detailed logging we will not be able to get the bottom of it. 

There is no need for any more people to simply report they are also having this issue.

**Comment by carkod** [comment]
@mjpierce7590  It is not located in the Program Files (x86) because you installed the x64 version, it should be in Program Files (without x86)

**Comment by manuel-hoelzl** [comment]
<h1>Found a solution to this problem!</h1>

Step 1: Go to "<b>C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Github, Inc</b>"
Step 2: Copy the Atom shortcut in there
Step 3: Paste it in "<b>C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs</b>"

Now Atom should be appearing in the start menu.
This worked for me using the x64 version and Windows 10.

**Comment by Samuelez99** [comment]
For me the step 1 was different, because I found the file in another place:

Step 1: Go to "C:\Users\USERNAME\AppData\Local\atom"
            Create a shortcut of atom.exe, that you find in that folder, and cut it.
Step 2: Go to "C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"
            Paste the shortcut in here. Now Atom will appear in the Start Menu.

I understand that it is a bug, so writing how we solved is a temporary solution, they have to solve it via code.

**Comment by Sant268** [comment]
A different problem,very similar to this one.
I installed atom,and the welcome page instantly opened.
I wrote programs for abt 2 hrs,and then I shut down my pc(i saved my files on atom).

After another startup,it disappeared,it shows atom in Change or Remove programs list,but no .exe file in APPDATA.Just an update file.,i clicked on it but nothing happens.
After reinstalling ,it's the same,
Opens first time and then disappears

**Comment by FranOz** [comment]
Same issue here. I have installed atom but I could not find it. I can't execute from cmd also.

**Comment by tazboyz16** [comment]
Im having same issues with not having any shortcuts to Atom Editor after Windows 10 x64 installer from the atom.io site. Version I have installed is 1.19.3 no trace of atom.exe in AppData folder. I was able to find its install files under C:\ProgramData vs installed in the Program files

**Comment by ni7in** [comment]
what if I move this to a new location.

**Comment by Glowmex** [comment]
I had the same issue, look for the exe file everywhere without luck. I tried to uninstall, but it was not showing in the control panel either. I use Revo Uninstaller most of the time, and when I tried, there it was, so from Revo I right clicked and looked for the install location and viola, there it was! Followed the path: C:\Users\USERNAME\AppData\Local\atom. From there made a shortcut in my desktop. Hope this helps!

**Comment by Hyvjan** [comment]
I had the same problem and windows search didn't find atom.exe from any directory. I found kind of workaround:

When I installed atom again and it opened I attached it to the taskbar. Now the icon stays on the taskbar and I am able to launch atom. Not good solution but works. Hope somebody else saves few hours of time while trying to figure this out.

**Comment by jkeithowens** [comment]
I had this same issue today, the info in replies above worked.  I think the reason that you can't find the .exe file in a search is because the folder is hidden (at least it was on my computer).  Once I made the folder "C:\Users\USERNAME\AppData" un-hidden, I could find the file in a search.

**Comment by AngiePeraza** [comment]
I had the same issue, previous replies worked but now Atom doesn't load, it tries to open but it doesn't and it doesn't show any error message neither. 

I reinstalled and now I have the shorcut but Atom still doesn't open.

**Comment by AlessiaBaka** [comment]
I have resolved by doing a research in all my :C partition.
Found it in here: "C:\Users\*****\AppData\Local\atom"
Shortcut on desktop and voilà!

Hope it helps!

**Comment by Baronsindo** [comment]
i can see atom any where in my computer, in this place C:\Users\ ***** \AppData\Local\atom i only see an update.exe

**Comment by wjgeorge** [comment]
happened to me with latest installer, got the shortcut, but not found on the CMD prompt line. I ended up adding %LOCALAPPDATA%/atom/bin to my PATH

**Comment by NaijaProgrammer** [comment]
@wjgeorge thanks for the path info. I did that too. I have to point out something, though. I am using atom 1.18.0 64-bit on a Windows 10 machine. The LOCALAPPDATA/atom does not contain a /bin folder. I just used the %LOCALAPPDATA%\atom, and it works for me. Also not the "\", as Windows does not allow the "/" as path separator.

**Comment by murdakah** [comment]
These are all workarounds and not an actual solution to the problem. What exactly is causing the directory and shortcuts to not be created? (Also the splash screen when installing is very small, but that's unrelated methinks) 
My username is also quite ordinary with no strange characters.

**Comment by damieng** [comment]
If we knew what caused it or how to reproduce it we could fix it.  Unfortunately nobody seems to have come up with repro steps that work on other people's systems.

It could be permissions, folder length, disk space, unicode characters, group policies, anti-virus...

**Comment by murdakah** [comment]
@damieng 
Actually, I've installed it on 3 different windows 10 machines, all 64bit, all acting the same way. Atom installs, but no start menu shortcut. To reproduce you simply need to install atom.

It's also strange that it doesn't install to Program Files, but I suspect that was a conscious decision.

**Comment by damieng** [comment]
@murdakah Unfortunately the repro is not that simple or this thread would have hundreds of users. My own dev platform is also Windows 10 64-bit so I would have experienced it too.

It's interesting however that it happens on all three of your systems.  Can you provide more information on what is common between them?  Some thoughts;

- username on all
- connected to a corporate domain
- running additional security software

etc.

**Comment by murdakah** [comment]
Fair enough. 

2 systems are intel based, other one is a amd ryzen, so that rules out processor dependence, if that was even a thing. All are in fact running Malwarebytes and Avast. Usernames are all standard characters, all 3 different usernames through, so I doubt it is that.

**Comment by damieng** [comment]
Could you try temporarily disabling avast on one while you reinstall Atom on it (then re-enable after) and see if you get the icon this time.

**Comment by murdakah** [comment]
No difference. Neither disabling Malwarebytes nor Avast  and both at the same time had any effect. Atom simply installed and launched with no start menu directory created.

**Comment by miajohannes** [comment]
I also have the same issue. No issue with my user name. Windows 10 32-bit. It got installed here: %localappdata%\atom. I pinned it to the taskbar from there.

**Comment by KBPsystem777** [comment]
Same case here before. But I followed the instructions above. I found the **Atom.exe** on `C:\Users\USERNAME\AppData\Local\atom`

**Comment by mrcycling** [comment]
I am having the same issues, installed Atom a couple of times without it appearing in the start menu.

After the second install, I did find a shortcut on the desktop (it may have been there the first time without me noticing it).  It was a generic windows icon, but I was able to right click it and change it to the Atom icon.

**Comment by jimmybigbaws** [comment]
And......
I'm having the same problems as above on the win64 installer but as above ive no way of opening it. I cant find the exe files. I know theyre hidden but dunno how to unhide them which is simply yet another google search i need to do.
I want this programme so i can learn programming, just didn't know i needed to be an expert before getting it to even work.
I understand this is open source (which I'm all for) but when writing your instructions for things like the installation you guys need to recognise there are people like me who don't know python or how every bloody nut and bolt of every programme works.
This entire process has been nothing but frustration because the info available to me is above my understanding for both atom and platformIO.
Rant over... the short time i had the editor open i actually liked atom and found it straightforward i just wish you guys n gals had put as much effort into the installation side of things as they need serious work unless youre an expert in python

**Comment by damieng** [comment]
@jimmybigbaws There should be an icon in the start menu.  It doesn't appear for some people and we've never been able to find out why as we can't reproduce it here.

You should be able to find the atom.exe by hand by using Windows Explorer and navigating to `C:\Users\<your user name>\AppData\Local\Atom x64`  Right-drag this to your desktop and choose 'Create Shortcut' to give it an icon.

**Comment by GordanBlake** [comment]
Same problem here on Windows 10 64bit creators update.

**Comment by CharlieSWLondon** [comment]
Likewise, I have managed to find the folder in AppData/Roaming but the .exe file is not there...

**Comment by damieng** [comment]
@CharlieSWLondon It's in the local folder, not the Roaming one. See my response two comments above yours.

**Comment by CharlieSWLondon** [comment]
I could not access the AppData file without using Roaming though?  It did not appear on my directory?

**Comment by CharlieSWLondon** [comment]
I managed to find the local folder in the end (not easily) however every atom file I clicked did not work and then disappeared.  One error message was thrown up though - "The code execution cannot proceed because ffmpeg.dll was not found.  Reinstalling the program may fix this problem

**Comment by CharlieSWLondon** [comment]
I have managed to sort it (I think) by following the instructions below to make the AppData/local/atom folder 'visible'.  I could then pin atom.exe to my taskbar before it disappeared.

https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_files-insiderplat_pc/windows-10-roaming-folder/6c99ffdc-90d5-4d1d-8ab1-b4f448ecc8ee

**Comment by Tarun22Sahu** [comment]
I found the folder atom in %localappdata% but i  could not find atom.exe in it . there are one folder named packages and a application file named update.exe. I could not find ,  I have reinstalled it and again after installing found the same problem.

**Comment by Nastyman9** [comment]
Just installed on my Win10-x64-v1607 system and had the same shortcuts issue. Found the executable in %localappdata%\atom and manually created my desired shortcuts. I certainly was a bit confused after I closed it for the first time and couldn't re-open it before I found this thread.

**Comment by Tarun22Sahu** [comment]
Oh I got a better solution. when installed first time and open first time pin it into the task-bar by right clicking on the icon in the task-bar. it will be there for the life time until you remove it.

**Comment by emmanndesign** [comment]
I got till today the same error, but by far, pin it in task-bar, is one the best solution for me.

**Comment by m1anas** [comment]
Same problem here in Windows 10(64-bit). Found the Atom.exe file in C:\Users\My User Name\AppData\Local\atom

**Comment by KBPsystem777** [comment]
This issue needs a closure. 
`atom.exe` can be found on this location: **C:\Users\USERNAME\AppData\Local\atom**

**Comment by zhongxiang117** [comment]
@KBPsystem777 No, we are talking the different thing. The folder %LOCALAPPDATA%\Atom is the default atom installed folder, however, the thing is it doesn't create an icon on the start menu, I have the same issue. My system is Windows 7 (64-bit),  Atom version is 64-bit, 1.28.1.0

**Comment by zhongxiang117** [comment]
I have an update. I checked the Atom log file named **SquirrelSetup.log** under **%LOCALAPPDATA%\atom** folder, I found some lines:

```
2018-07-13 15:26:26> Program: Starting Squirrel Updater: --createShortcut atom.exe -l Desktop,StartMenu
2018-07-13 15:26:26> ApplyReleasesImpl: About to create shortcuts for atom.exe, rootAppDir C:\Users\NAME\AppData\Local\atom
2018-07-13 15:26:32> ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk
2018-07-13 15:26:32> ApplyReleasesImpl: About to save shortcut: C:\Users\NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk (target C:\Users\NAME\AppData\Local\atom\atom.exe, workingDir C:\Users\NAME\AppData\Local\atom\app-1.28.1, args , toastActivatorCSLID f859ea73-8d1d-59d0-89d7-06ee420a371f)
```
Then I realized that the Atom shortcut was successfully created, but under the folder **GitHub, Inc**, and in this folder I do find that icon!

**Comment by WE012** [comment]
I do not know if it's helpful, but I want to contribute ... (translated by google, I do not know much of English).

https://www.adslzone.net/windows-10/ocultar-archivos-y-carpetas-resultados-busqueda/

![indizacion-454x500](https://user-images.githubusercontent.com/20592543/43105852-67e5d7f4-8ea4-11e8-8c3b-68a85ab83452.jpg)

**Comment by Njengah** [comment]
The same issue with a fresh install on Windows 10 .. I found it in the C:\Users\user-name\AppData\Local\atom and moved the shortcut to the Roaming folder

**Comment by JuanGaray93** [comment]
I had the same issue. Fresh install, version 1.28.2 x64 on Windows 10. Had to fetch the exe and manually create shortcuts.

**Comment by gbmcd** [comment]
Same issue with fresh install on Windows 10 x64 with v1.30 Atom, with an exception.  There was no C:\Users\user-name\AppData\Local\Atom\bin directory.  There was a C:\Users\user-name\.atom directory.  I created the bin directory in C:\Users\user-name\AppData\Local\Atom\ and moved the data in the .atom directory into the bin directory.  Atom was then able to start with that move.  Hope this helps.

**Comment by damieng** [comment]
The %username%\.atom folder should only contain the data for the application (configuration, settings, installed packaged) - not the application itself.

Are you saying you had an atom.exe in that folder or a sub-directory within it?

**Comment by Cydrux** [comment]
Well, it was solved after i installed it with RUN as administrator 
and Bingo, the icon is on the desktop and start menu

**Comment by mskadu** [comment]
19 months after the problem was reported, here I am confirming that it still exists.

My suggestion:

* Use the time-tested approach of asking the user where he/she wants the software installed
* Fix this particular problem

I am on the latest version of Windows 10 (all patches and updates installed as of today morning)

**Comment by rcpao-enmotus** [comment]
Win10 1809: Desktop shortcut exists and works; however, there is no Start Menu shortcut.

[SquirrelSetup.log](https://github.com/atom/atom/files/2567043/SquirrelSetup.log)

2018-11-06 12:02:49> Program: Starting Squirrel Updater: --createShortcut atom.exe -l Desktop,StartMenu
2018-11-06 12:02:49> ApplyReleasesImpl: About to create shortcuts for atom.exe, rootAppDir C:\Users\rcpao\AppData\Local\atom
2018-11-06 12:02:50> ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\rcpao\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: About to save shortcut: C:\Users\rcpao\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk (target C:\Users\rcpao\AppData\Local\atom\atom.exe, workingDir C:\Users\rcpao\AppData\Local\atom\app-1.32.1, args , toastActivatorCSLID f859ea73-8d1d-59d0-89d7-06ee420a371f)
2018-11-06 12:02:50> ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\rcpao\Desktop\Atom.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: About to save shortcut: C:\Users\rcpao\Desktop\Atom.lnk (target C:\Users\rcpao\AppData\Local\atom\atom.exe, workingDir C:\Users\rcpao\AppData\Local\atom\app-1.32.1, args , toastActivatorCSLID f859ea73-8d1d-59d0-89d7-06ee420a371f)
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: Firefox.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: Notepad++.lnk
2018-11-06 12:02:50> ApplyReleasesImpl: Examining Pin: VMware Workstation Pro.lnk
2018-11-06 12:02:52> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.32.1
2018-11-06 12:02:52> Program: Fetching update information, downloading from https://atom.io/api/updates-x64?version=1.32.1
2018-11-06 12:02:52> SingleGlobalInstance: **Failed to grab lockfile**, will retry: C:\Users\rcpao\AppData\Local\Temp\.squirrel-lock-B765A3C0E469AA514EAA9271029185D8FE3903E4: System.IO.IOException: The process cannot access the file 'C:\Users\rcpao\AppData\Local\Temp\.squirrel-lock-B765A3C0E469AA514EAA9271029185D8FE3903E4' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2018-11-06 12:02:53> SingleGlobalInstance: **Failed to grab lockfile**, will retry: C:\Users\rcpao\AppData\Local\Temp\.squirrel-lock-B765A3C0E469AA514EAA9271029185D8FE3903E4: System.IO.IOException: The process cannot access the file 'C:\Users\rcpao\AppData\Local\Temp\.squirrel-lock-B765A3C0E469AA514EAA9271029185D8FE3903E4' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)

**Comment by CrackerKSR** [comment]
> I appreciate any help here. Thank you.
> 
> PS I really want to move over from Sublime Text 👍

Go to C:\Users\[username]\AppData\Local\atom
Do not forget to Pin it to start menu :D

**Comment by CrackerKSR** [comment]
### C:\Users\KSR\AppData\Local\atom

**Comment by CrackerKSR** [comment]
### ### ### C:\Users[username]\AppData\Local\atom

**Comment by CrackerKSR** [comment]
### Atom is located in C:\Users[username]\AppData\Local\atom

**Comment by SACHINKUMARHACKER** [comment]
# You can use the zip folder of atom. Extract the files and there you go.

**Comment by skywalker201090** [comment]
I installed atom through pip, also added path to environment variable,how can I run it now?? I checked it's installed but doesn't have .exe file or bin folder!

**Comment by Aerijo** [comment]
@skywalker201090 
> I installed atom through pip

If you are referring to the Python package manager, I believe you installed [this](https://pypi.org/project/atom/), decidedly not Atom (the text editor). The only supported install process for Atom is from [official page](https://atom.io/). Other package managers like Snap may provide Atom, but they tend to be out of date and / or modified.

**Comment by UtkarshMalviya11** [comment]
In Some Windows pc, the AppData folder is hidden due to which content inside of it is hidden. So the Atom icon does not appear, but if we unhide it from the control panel and create a shortcut to the desktop it functions properly, I do not know how installation work but I think the problem can be resolved around it.
Once I learn it, I would resolve it myself. Thanks for creating this beautiful text editor.

**Comment by iswaq** [comment]
If you have just installed the Atom Editor, just load the Task Manager, right click the atom.exe and goto file location. Otherwise follow the file location : C:\Users\Username\AppData\Local\atom\app-1.34.0 (whatever version).

**Comment by bdalina54** [comment]
It happens when the computer has multiple user accounts, it will be installed on the administrator account, and not showing in other account.
Ex. my admin pc user is  C:\users\pcx_admin\

What I did was to logon the administrator account and it show in the start up, in the desktop, etc. so I just copy the shortcut link to the pc user I want.  

C:\users\bdalina\Desktop    ->i paste the shortcut there

Then I log to the account bdalina, hooray its there and it runs!

**Comment by Sanidhya-Tyagi** [comment]
Atom will be found in appdata in your User/(this is your username)/Appdata/atom/atom.exe

but enable hidden folders...

**Comment by skywalker201090** [comment]
Its resolved thank you.

**Comment by garynobles** [comment]
Same issue as the original post, downloaded Atom x64 from the official site today, %LOCALAPPDATA%\Atom x64 locates the exe file, but is not showing up in the windows start menu/programs.

**Comment by netwards** [comment]
> 
> 
> Okay - I found the atom.exe file here
> C:\Users\my user name \AppData\Local\atom\app-1.15.0\atom.exe
> and I made a shortcut so I can start it up now.
> Thanks

**Comment by EyesX** [comment]
Ridicules issue that has been around for years. Never happens with other programs, just Atom. Fix it!

**Comment by sylekta** [comment]
Still an issue, it doesnt auto add to path or create shortcuts

**Comment by sherwoodhughes** [comment]
I have the same problem but all I could was this folder C:\Users\[username here]\AppData\Roaming\Atom\ but there was not Atom.exe in the folder. Any ideas on where to fin d it?

**Comment by sherwoodhughes** [comment]
> I have the same problem but all I could was this folder C:\Users[username here]\AppData\Roaming\Atom\ but there was not Atom.exe in the folder. Any ideas on where to fin d it?

Should have also said that I did a search of the hard drive and found no atom.exe file. Like others I installed this directly from the atom.io website.

**Comment by shafiq-dev** [comment]
hi all
** I found  a Global  solution **
1. just  go  to this  link 
https://atom.io/packages/preview
2. click on install 
3. click on run with atom only  
4. atom opened  
5. rignt  click on atom  icon on the  bar then attach it 
voila :)

**Comment by jsldeleon** [comment]
I don't seem to have AppData folder in  " C:\Users[username here]\AppData\Roaming\Atom\ " . I can see .atom folder, but no atom.exe inside it. What I did is I pinned the running atom program into my taskbar, but it sure is better to have a desktop shortcut. And no worries to reinstall again and again

**Comment by inemesitaffia** [comment]
So, this is a *long* standing issue that has gone unfixed

**Comment by JosueEstrada** [comment]
i install this and some packages, next day i dont have the .exe and only have the atom carpet in roaming, :S

**Comment by jefieldv** [comment]
issue happened to me today

**Comment by 42mix** [comment]
This issue still exists, it seems to have started happening when I uninstalled and installed Atom again

**Comment by admin4life** [comment]
I have used atom on my computer for several projects (windows 10). I go to load it up again today and there is no trace of it anywhere. I have searched in prg files, appdata, start menu. It has vanished from my computer. I last used it about 2 months ago. I did not uninstall it. WTF is going on.

**Comment by Sanidhya-Tyagi** [comment]
Preferably this issue is solved

**Comment by Sanidhya-Tyagi** [comment]
i am still using atom and it is still in app data

**Comment by Sanidhya-Tyagi** [comment]
Uninstall atom completely by deleting app data /atom and try again

**Comment by Sanidhya-Tyagi** [comment]
Please close this issue

**Comment by ninjaasmoke** [comment]
I got the exact same issue 
My workaround was to create shortcut of the atom.exe found in

`C:\Users\[username]\AppData\Local\atom\app-[version]`

Then, cut and paste the shortcut to the desktop

**Comment by pixelbly** [comment]
Happen to in 2020.

**Comment by shivaramayysola** [comment]
> Okay - I found the atom.exe file here
> C:\Users\my user name \AppData\Local\atom\app-1.15.0\atom.exe
> and I made a shortcut so I can start it up now.
> Thanks

Thanks dude

**Comment by Deepak0-01** [comment]
Easiest way to create shortcut for atom :)
After installing atom when it opens
1) click on file ->open file
It will automatically redirect you to atom.exe
Right click on atom and then create desktop shortcut 
Cheers :)

**Comment by akanksha1901** [comment]
Okay, i tried everything. still couldn't find it. 
Here is the HACK that worked for me: (_for creating a desktop shortcut_ )
_right click>new>shortcut_
type atom (and select "**atom://welcome/welcome**" or you can maybe type this)
give your shortcut a name. (eg: atom)
viola!!

The new shortcut opens the welcome window, but it was better than other things.

or when you open atom for the first time, click its icon on the taskbar, and **pin it to the taskbar**. You can access it from there.

(I really hope this helps, please let me know)

**Comment by inemesitaffia** [comment]
why can the atom devs do this?

**Comment by oak-sw** [comment]
each time i have to run Atom again. any solution?

**Comment by Git-071** [comment]
> # Found a solution to this problem!
> Step 1: Go to "C:\Users<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Github, Inc"
> Step 2: Copy the Atom shortcut in there
> Step 3: Paste it in "C:\Users<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"
> 
> Now Atom should be appearing in the start menu.
> This worked for me using the x64 version and Windows 10.

Thank you so much, the only thing is, you need to run Windows Explorer with administrator rights.
> Go to "C:\Windows\explorer.exe"
> Right-click on "explorer.exe"
> From the context menu, select "Run as Administrator"

And from there you can follow the steps as outlined above.

**Comment by dot-com-bubble** [comment]
I have tried all of these solutions but none of them worked for me. I am using windows 10, 64 bit. Atom is the newest version and 64-bit too.

**Comment by theClubHopper** [comment]
Am also using Windows 10 (64-bit), just installed Atom for the first time, and after closing its first run, was at a loss for how to open the app again. The installer hadn't added Atom to my Start menu and Atom isn't findable via a typed search in the Windows Search (on the taskbar). If users can't locate a way to run a program they've installed (without having to Google it), that ought to be considered a **serious** problem and corrected immediately!

Despite the fact that 3 individuals have posted above that they have found "a solution", only workarounds have been posted - and so now, **some 3.5 years after the bug was first opened, there appears to have been no progress in resolving the real issue at hand: Atom's Windows installer fails to add the program to the Windows Start Menu of the Windows user profile in use at the time of installation.**

_Note: bdalina54's comment on Feb 27 2019 suggests the issue occurs when there are multiple user profiles in Windows and that Atom is getting installed to the admin profile - yet in my case, my profile *is* the admin profile and Atom in absent from my Start Menu, or from any profile's Start Menu on my computer.

Secondary to the main issue is that Atom's current installer is non standard and fails to do things expected of Windows installers. So to summarize the issues with the current Atom installer:

1. The installer does not add Atom to the logged-in user's Start Up folder.
2. The installer installs Atom to a non-standard file location; as the Atom webpage indicates that the download is for 64-bit versions of Windows, the standard(/expected) default install path should be "C:\Program Files"; it is not.
3. Moreover, the installer installs Atom into what is by default (in Windows) a hidden subdirectory; in my case it's "C:\Users\[profile]\AppData\local\"
4. The installer does not provide the user with any information about the application's actual install path - helpful info so that for future reference, the application can be manually located, if need be.
5. The installer does not offer the user the option of selecting & using a custom install path; it is a non-interactive and essentially silent install.

My suggestion is that if the current Windows installer be replaced by an entirely different installer, one that follows standard, expected Windows install protocol.

**Comment by AidyYT** [comment]
> Awesome, thanks. Does the `%LOCALAPPDATA%\Atom x64` folder exist, and if so, does `app-1.15.0\atom.exe` exist?

Works. THANKSSSSS

**Comment by achjailani** [comment]
If you're using windows 10, than do this:
* open your cmd 
* if you're in C:\Users\`%your username%` directory, just run:  `cd AppData\Local\atom` 
* than run : `atom --squirrel-updated`
* wait a few seconds, it will appear in your start menu

Note: the atom file is in `C:\Users\Lnxsr\AppData\Local\atom\atom.exe`

**Comment by ananyo141** [comment]
> I have this problem too. Atom was installed to `%localappdata%\atom` but nothing in start menu, program folder, etc.
> 
> **Windows 7 Professional SP1**
> 
> Can confirm @50Wliu @damieng I re-installed with my anti-virus turned off and still had this problem. Username contains only normal letters.
> 
> Program is located at `C:\Users\<USERNAME>\AppData\Local\atom`
> 
> ![image](https://user-images.githubusercontent.com/331540/27795406-ddd099e6-5fba-11e7-8310-2f085b972291.png)

Thanks @achjailani for the input. It worked! The address you provided was successful to get me to the install directory of atom.

**Comment by ajfitz4905** [comment]
The fact that this seemingly simple issue has gone unaddressed for 4 years causes me to lose much faith in the app.  It was suggested that I try either atom or VS code as I learn full stack, and I'm really tempted to download VS before i waste any more time getting familiar with atom.

**Comment by cybervigilante** [comment]
Simple fix. Remove Atom. Never liked it. Why Julia foists it on people is beyond me.

**Comment by icecream17** [comment]
The problem is that only a few people are volunteering to work on Atom - and even then not much is happening. That's why this issue is open for so long.

https://github.com/atom/atom/issues/14020#issuecomment-730079755 is quite helpful. Thanks
I added it to my todo list, but I'm not an expert with creating installers, or whatever I have to do. Blah blah blah, don't expect this to be done very soon.

**Comment by tonymongare** [comment]
I have been using atom for some time now I like it so much. Now run into the same issue any solution yet

**Comment by icecream17** [comment]
check `C:\Users\<User>\AppData\Local\atom`

AppData is a hidden folder by default

**Comment by icecream17** [comment]
I can't figure out why atom is installed in the hidden folder

https://github.com/atom/atom/blob/master/script/lib/create-windows-installer.js

**Comment by tonymongare** [comment]
Great !, thank you

**Comment by LFuxdesign** [comment]
> WIN+R: %LOCALAPPDATA%

**Comment by ah526** [comment]
@

> For me the step 1 was different, because I found the file in another place:
> 
> Step 1: Go to "C:\Users\USERNAME\AppData\Local\atom" Create a shortcut of atom.exe, that you find in that folder, and cut it. Step 2: Go to "C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs" Paste the shortcut in here. Now Atom will appear in the Start Menu.
> 
> I understand that it is a bug, so writing how we solved is a temporary solution, they have to solve it via code.

Thanks a lot.

**Comment by ah526** [comment]
> 

`strong` You should create a notepad, then edit it with Atom, `/strong` **don't create one from Atom.**

**Comment by ah526** [comment]
> A different problem,very similar to this one. I installed atom,and the welcome page instantly opened. I wrote programs for abt 2 hrs,and then I shut down my pc(i saved my files on atom).
> 
> After another startup,it disappeared,it shows atom in Change or Remove programs list,but no .exe file in APPDATA.Just an update file.,i clicked on it but nothing happens. After reinstalling ,it's the same, Opens first time and then disappears
### You should create first a notepad, then edit it  with Atom, **not creating one from Atom**

**Comment by lukawizman** [comment]
I had the same issue today and nothing from above helped me (couldn't find atom.exe) But I was able to find a work around....Installed atom and then within atom went to: settings>system>Checked all 3 boxes "register as file handler", "show in file context menus" , "show in folder context menus" and closed the program
Then instead of looking for Atom, I would just right click on any .py file and choose the option "open with atom"

**Comment by ghost** [comment]
> I had the same issue today and nothing from above helped me (couldn't find atom.exe) But I was able to find a work around....Installed atom and then within atom went to: settings>system>Checked all 3 boxes "register as file handler", "show in file context menus" , "show in folder context menus" and closed the program Then instead of looking for Atom, I would just right click on any .py file and choose the option "open with atom"
### You cannot open .py files with atom. **Atom is only for web developing.** Try installing Python and Eclipse IDE and do this: https://www.bouraspage.com/repository/articles-python/how-to-set-up-eclipse-for-python
