### ISSUE TITLE
Save / Save As dialog opens in the background

### ISSUE THREAD

**Issue by peteruithoven** [atom/atom#14139]
### Description

The Save / Save As dialog opens in the background. 
Also mentioned here: https://github.com/atom/atom/issues/13978#issuecomment-286096819

### Steps to Reproduce

1. Open atom in safe mode
2. Create new file
3. Press File  > Save / Save As... or ctrl + s / ctrl + shift + s
4. Save dialog is opened in foreground
5. Close dialog
6. Press File  > Save / Save As... or ctrl + s / ctrl + shift + s

**Expected behavior:**
Dialog to open in foreground.

**Actual behavior:**
Dialog opens in background from then on.

### Versions
```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4
```

I'm running Elementary OS 0.4 Loki (based on Ubuntu 16.04 LTS).

**Comment by rsese** [comment]
I can reproduce this behavior on Ubuntu but do you know if this was also fixed by https://github.com/atom/atom/pull/14119 @unbg?  It was mentioned in https://github.com/atom/atom/issues/13978#issuecomment-286096819 like @peteruithoven noted, but that issue was mainly about which directory `Save as` would drop you in.

**Comment by ungb** [comment]
I tried off master and this looks fixed on ubuntu.  I was able to verify on 1.15.0 and on beta that this issue still occurs.  I'm going to close this issue out since it's fixed by #14119

**Comment by peteruithoven** [comment]
Thanks for verifying! :)

**Comment by fergusincoronato** [comment]
Still not working for me on Ubuntu 16.04 LTS

```
$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

**Comment by ungb** [comment]
Looking.

**Comment by ungb** [comment]
@fergusincoronato, I tried on `Ubuntu 16.04 LTS` with Atom 1.18.0 and was able to see that this issue is fixed, Can you please open another issue with repro steps on what you're seeing?  

See Gif of issue that is fixed on 1.18.0.
![works](https://user-images.githubusercontent.com/5624870/28757031-9a11e518-752f-11e7-8efe-b0a26d7beb52.gif)

**Comment by peteruithoven** [comment]
For me this is also fixed, although it doesn't have focus, I can't start typing the filename or press the <kbd>esc</kbd> to close the window for example. But I guess that's a seperate issue.

**Comment by umpirsky** [comment]
It does not have focus. On Linux to get focus you must press `Ctrl + ``.

This is major UX problem for people that are using keyboard as their primary input device. Should we open separate issue for this?

**Comment by Ben3eeE** [comment]
@umpirsky Please open a new issue if one does not already exist.
