### ISSUE TITLE
Previous automatically-saved project state detected popups every time I'm opening a folder

### ISSUE THREAD

**Issue by jarrodek** [atom/atom#14968]
Ive removed default content because it's not like a technical issue.

Because I'm using polymer-ide I have to open each component in different window (can't add another folder to current project). Every time I'm opening a folder I'm seeing this:
![image](https://user-images.githubusercontent.com/3320020/27925925-69acc730-627e-11e7-8102-1e27ea4f521e.png)

Is there's a way to avoid this popup? I really don't care at which state it will open.
And this is happening on MacOs only.

**Comment by lee-dohm** [comment]
Can you reproduce this in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by jarrodek** [comment]
I can check later at work but so far it happens only on MacOs.

**Comment by jarrodek** [comment]
Yup, the same bahavior:

![image](https://user-images.githubusercontent.com/3320020/28467001-2b2721aa-6e26-11e7-8128-a0ca961b5413.png)

**Comment by lee-dohm** [comment]
And what happens when you click the option to discard the state when running in Safe Mode?

**Comment by jarrodek** [comment]
Just opens the folder as it should in the first place:

![image](https://user-images.githubusercontent.com/3320020/28467323-76bb78cc-6e27-11e7-9033-e2081c24070e.png)

**Comment by lee-dohm** [comment]
@BinaryMuse any ideas?

**Comment by zhanwenchen** [comment]
Also started having this problem ever since installing ESLint

**Comment by jarrodek** [comment]
I'm not experiencing it in beta version anymore.

**Comment by zhanwenchen** [comment]
I updated eslint to linter-eslint@8.3.2, which solved this issue.

**Comment by Ben3eeE** [comment]
@jarrodek @zhanwenchen Thank you for reporting back that it is working for you again 🙇 I am going to close this out since it looks like it has been fixed but don't hesitate to reach out if you experience this issue again and we will be happy to reopen ✨

**Comment by zhanwenchen** [comment]
Actually this has not been fixed for me. It still shows when I open a new project folder in a new window. I wonder how to find the Atom "state" information?

**Comment by Ben3eeE** [comment]
@zhanwenchen This dialog is expected when the Atom window you opened has any changes.

* Did you do anything in the new window before opening a project folder?
* Did you try the applicable steps in the [flight-manual debugging section](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? Clearing saved state, testing in safe mode and resetting to factory defaults.
