### ISSUE TITLE
Gutter decoration regression in v1.19.0

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15062]
### Prerequisites
_Note: As only custom gutter decorations are affected, this is unable (?) to be tested in safe mode._

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The positioning of gutter decorations has regressed between Atom v1.18.0 and Atom v1.19.0-betaX (confirmed on -beta3). It seems that they are being shoved to the right ~50 pixels... and as their Z-index is below the editor's this effectively makes them invisible.

### Steps to Reproduce

1. Have a package installed that creates a custom gutter. (ex. `linter-ui-default`)
2. Get that package to decorate a line.
3. Note that the gutter decorations aren't showing visibly.

#### Expected behavior:

Custom gutter icons show as they did in Atom v1.18.0.

Linter UI gutter on right in Atom v1.18.0:
![atom_2017-07-19_15-42-31](https://user-images.githubusercontent.com/427137/28393440-9f830d02-6c9b-11e7-9606-2022bde8283c.png)

Linter UI gutter on left in Atom v1.18.0:
![atom_2017-07-19_15-42-58](https://user-images.githubusercontent.com/427137/28393446-aefaf542-6c9b-11e7-951d-2cb46219944a.png)

#### Actual behavior:

Custom gutter icons are shifted to the right by a constant value (~50 px?), and background highlights don't show.

Linter UI gutter on right in Atom v1.19.0-beta3:
![atom_2017-07-19_15-49-17](https://user-images.githubusercontent.com/427137/28393471-c4c60448-6c9b-11e7-914d-6df2990ec239.png)

Linter UI gutter on left in Atom v1.19.0-beta3:
![atom_2017-07-19_15-48-58](https://user-images.githubusercontent.com/427137/28393474-c80f7b98-6c9b-11e7-8bde-4e27f5491ad0.png)

#### Reproduces how often:

100% of the time.

### Versions

```
OS: Windows 10 Enterprise x64
Atom    : 1.19.0-beta4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.3.windows.1
visual studio 2015
```

### Additional Information

The gutter decorations were first reported by @ooJerryLeeoo in https://github.com/steelbrain/linter-ui-default/issues/359, with the background highlighting pointed out by @50Wliu in https://github.com/steelbrain/linter-ui-default/pull/190#issuecomment-316501642 and elaborated on in https://github.com/steelbrain/linter-ui-default/issues/385.

**Comment by rsese** [comment]
I can reproduce as described with https://atom.io/packages/linter-jshint and left gutter highlight in 1.19.0-beta5:

![gutter-highlight](https://github-slack.s3.amazonaws.com/monosnap/test.js__workjs-excercises_2017-07-25_02-16-17.png)

**Comment by dsandstrom** [comment]
Some workarounds that may need tweaking:
```less
atom-text-editor .linter-highlight.linter-warning.linter-gutter {
  // show linter icon
  position: absolute;
  right: 6px;
}

atom-text-editor .gutter[gutter-name='linter-ui-default'] .cursor-line {
  // fix cursor line background
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
}
```

**Comment by Arcanemagus** [comment]
@dsandstrom The bigger question is what broke between Atom v1.18.0 and v1.19.0 that changed these gutter decorations to stop working? And is it something that should be fixed in `linter-ui-default` (and any other package affected), or here in Atom?

Thanks for posting a workaround though for people coming to this issue! @steelbrain if Atom v1.19.0 gets released before this is fixed you'll need to implement something like that in `linter-ui-default`.

**Comment by nathansobo** [comment]
We'll fix this before 1.19 is released. Thanks for the reports and sorry for the trouble.

**Comment by dsandstrom** [comment]
Thanks @nathansobo and @jasonrudolph, beta6 makes the gutter icon show again.  However, the current line background is still not working.  I will bring it up in linter-ui-default.

**Comment by nathansobo** [comment]
@jasonrudolph It sounds like we still have an issue with this background color. @dsandstrom can you post a screenshot?

**Comment by Arcanemagus** [comment]
@nathansobo It's a little bit hard to see, but my screenshots already posted here are showing the issue already.

**Comment by Arcanemagus** [comment]
It looks like it's implemented as a _single_ `<div><span>` combo per block of highlight, instead of one per line, is that what's causing the issue?

**Comment by jasonrudolph** [comment]
>>> beta6 makes the gutter icon show again. However, the current line background is still not working.
>>>
>> @dsandstrom can you post a screenshot?
>>
> It's a little bit hard to see, but my screenshots already posted here are showing the issue already.

@Arcanemagus @dsandstrom: I looked at the screenshots in the issue body, but I'm having a hard time seeing the line background issue. (Sorry.) Would you mind posting a screenshot that shows the difference between Atom 1.18 and Atom 1.19-beta and annotate the screenshot to point out the line background differences? :pray: That would be a big help.

**Comment by 50Wliu** [comment]
GIF of it working:
![linter-gutter-cursor-highlight](https://cloud.githubusercontent.com/assets/4278113/23975302/a1ea4468-0a01-11e7-8e11-b2dc7a333951.gif)

Currently not working:
![image](https://user-images.githubusercontent.com/2766036/28881106-11f26412-7775-11e7-8f28-80558481dfa3.png)

**Comment by steelbrain** [comment]
Responsible code: [link](https://github.com/steelbrain/linter-ui-default/blob/c25519bb828e630b200c52cd6e368a6b224d7c8d/lib/editor/index.js#L99-L149)

**Comment by Arcanemagus** [comment]
@jasonrudolph If @50Wliu's images aren't enough I can replicate the original ones in a light theme that makes the line highlights obvious.

**Comment by jasonrudolph** [comment]
@dsandstrom @Arcanemagus @50Wliu @steelbrain: Thanks for the help. :bow: 

We believe that https://github.com/atom/atom/pull/15147 should address the issue seen in https://github.com/atom/atom/issues/15062#issuecomment-319706393. We hope publish a new 1.19 beta release with that fix in it this week.
