### ISSUE TITLE
Test spec progress got very slow from v1.17.0-beta0.

### ISSUE THREAD

**Issue by t9md** [atom/atom#15177]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As far as I noticed, from Atom v1.17.0-beta0, test spec take very long time compare to previous version.

This is comparison when I run same `it` clause with `null` body 1000 times by loop.

- v1.16.0: 35.48s
- v1.17.0-beta0: 149.73s <== slow
- v1.19.0-beta7: 134.54s <== still slow

I noticed this issue while I investigating following `vim-mode-plus's spec take very long time from v1.17` issue.
I thought it's vim-mode-plus's issue and postponed investigation till now since I didn't see noticeable problem in daily Atom use..
https://github.com/t9md/atom-vim-mode-plus/issues/754

### Steps to Reproduce

1. create sample `test-spec.coffee` under `spec` dir(whichever package is OK) and run spec by `Window: Run Package Specs`.

```coffeescript
fdescribe "slow down", ->
  for n in [1..1000]
    it "case-a", -> null
```

2. See progress of spec to pass gradually slow down.

## Result of 1000 empty spec run.

- v1.16.0: 35.48s
- v1.17.0-beta0: 149.73s
- v1.19.0-beta7: 134.54s

**Expected behavior:** [What you expect to happen]

Progression of test doesn't slow down.

**Actual behavior:** [What actually happens]

Progression of test doesn't slow down gradually.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

- v1.16.0: No problem

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

- v1.17.0-beta0: First version I noticed this slow down

```
Atom    : 1.17.0-beta0
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

- v1.19.0-beta7: Latest beta I can still see slow down issue.

```
Atom    : 1.19.0-beta7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
@t9md I tried this on mac and wasn't able to see this issue. For me the test finish between 85-90 seconds.  I've tried 1.16.0, 1.17.0, 1.19.0, and 1.21.1

**Comment by t9md** [comment]
I still see big difference like following.

- 1.16.0(`38.7`s) test spec progress constantly
- 1.18.0(`1.23.78`s) gradually slow down as it progress
- 1.22.0-beta1(`79.28`s) slow down  too, but better than 1.18.0.

But as I can see 1.122.0 is getting faster again(maybe because of editor rendering overhaul?).
I use vim-mode-plus pkg to place sample `test-spec.coffee`, although I believe pkg is not related to just run focused test-spec, I want to try with pkg you tried.

Also I checked with `test-spec.js` and result was not different(still slow down).

```js
fdescribe("slow down", () => {
  for (let i = 0; i < 1000; i++) {
    it("case-a", () => {
      null
    })
  }
})
```

**Comment by maxbrunsfeld** [comment]
Sorry for not addressing this for so long. It may have been fixed by https://github.com/atom/atom/commit/12875c19395224da980485e7dc2581a60b57ef76.

**Comment by t9md** [comment]
Thanks! Then I will close this.

**Comment by t9md** [comment]
For clarity, I recently checked to see this slow down still happens in atom-v1.31.0-beta1.
Unfortunately, it still happens.
So original issue has not been solved yet.

But I will keep close this issue since I have no idea to progress this issue.
And will open a new issue in case I found something new to solve this issue in the future.
