### ISSUE TITLE
Weird when editing text which is partial selected. (with required Prerequisites)

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#15217]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Select a part of a string and type a letter, the selection should disappear but not move to the right part of the string, this is a DEMO

![demo](https://user-images.githubusercontent.com/2340296/29136116-cede213e-7d6e-11e7-89b6-916e08ab2999.gif)

### Steps to Reproduce

1. File -> New File;
2. Input a string `aaaaabbbbbccccc`;
3. Select the middle part of the string `bbbbb`;
4. While still holding down the mouse button. Type a letter `x`;

**Expected behavior:** The text becomes `aaaaaxccccc` and no charcters are selected.

**Actual behavior:** The text becomes `aaaaaxccccc` but the middle 4 `c` are selected.

**Reproduces how often:** 100% reproduce.

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

MacOS Sierra 10.12.6 

### Additional Information
I did the steps more than 10 times, every time it reproduce. But it will not reproduce when you use undo to get the selection back after type the letter `x`, like typing `cmd-z`.

Another problem is when I select some strings and hit backspace, the selected strings are deleted but strings next to the deleted one are automatically selected.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14911. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

Duplicate of https://github.com/atom/atom/issues/14911

**Comment by yubaoquan** [comment]
This issue talks totally different thing with #14911, please read it again.

**Comment by Ben3eeE** [comment]
This happens because you are still holding down the mouse button when changing the selected text. Atom 1.18 did not update the selection if you held down the mouse button after changing selected text.

**Comment by yubaoquan** [comment]
Oh thank you very much! I found the reason of this problem. I am using Mac trackpad, and enabled three finger drag. When after drag I take my hand off the trackpad, it seems that the trackpad reacts a bit delay.
Your answer is very helpful! Thank you again. @Ben3eeE

**Comment by Ben3eeE** [comment]
Going to reopen this because I am not sure if it is a bug or a new expected behavior. I don't know what the expected behavior is using these steps and since there is a difference between Atom 1.18 and 1.19 that I can't find documentation of I will bring it up for discussion with the Atom team.

**Comment by ethancfchen** [comment]
Same problem here, I'm using macOS Sierra 10.12.6 with trackpad

**Expected behavior:**

![8 -22-2017 13-41-48](https://user-images.githubusercontent.com/5051791/29550308-b038e86a-873f-11e7-9b8c-c6e44cd50ae6.gif)

**Actual behavior:**

![8 -22-2017 13-26-27](https://user-images.githubusercontent.com/5051791/29550130-b43ec7c8-873e-11e7-95ba-b0ddb474aa33.gif)

And by typing:

![8 -22-2017 13-27-56](https://user-images.githubusercontent.com/5051791/29550407-26b8ec92-8740-11e7-8ecc-a47b1800a758.gif)

Key input: `[select]` and typed `123456789`
it only shows `456789`.

**Comment by Ben3eeE** [comment]
I tweaked the steps to reproduce in the body of the issue to triage and label this as a regression. It seems like this behavior causes problems for users with a trackpad.

/cc: @as-cii I checked Sublime Text 3 and vscode 1.15. Neither of them update the selection if you hold down the mouse button when editing text after selecting with the mouse.

**Comment by lee-dohm** [comment]
> I tweaked the steps to reproduce in the body of the issue to triage and label this as a regression.

Did this work as expected in previous versions of Atom?

**Comment by Ben3eeE** [comment]
> Did this work as expected in previous versions of Atom?

Yes. I commented about it working differently in Atom 1.18 here https://github.com/atom/atom/issues/15217#issuecomment-321890961. I also found https://github.com/atom/atom/pull/8627 where the same issue was fixed. The test and fix for the issue got lost in the editor rendering rewrite. See the PR for more information: https://github.com/atom/atom/pull/15407

**Comment by yubaoquan** [comment]
Updated to 1.20.0-beta4, this problem still can reproduce, normal mode and safe mode. Is that means the mechanism of left mouse button and trackpad are different? @Ben3eeE

**Comment by 50Wliu** [comment]
@yubaoquan this hasn't been released yet.

**Comment by nathansobo** [comment]
This will go out with 1.19.4 and 1.20.0-beta5 either this afternoon or tomorrow.

**Comment by iolsen** [comment]
One of our build providers is having CDN connectivity issues preventing us from getting a green build for this release. This is currently scheduled for the next hotfix release, but unfortunately there's a good chance it won't ship today.
