### ISSUE TITLE
Uncaught (in promise) Error: EOVERFLOW, Unknown error

### ISSUE THREAD

**Issue by pyromanci** [atom/atom#15236]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I want to be clear I have not been able to reproduce after I solved the problem. Been trying for 2 days now. But was such a strange problem and behavior I felt i should report it. 

I closed atom 2 nights ago and when I reopened it the following morning. No tabs were showing. It was just the menu. Not git browser, project tree, ect. just about everything in the menus didn't respond.  The program wasn't locked up as I could open and close the menus, but it wouldn't open the settings, packages, or even reopen my project. This is what it looked like: https://prnt.sc/g6s8yo

So I started working through the debug steps. I check to ensure i was on the latest version (1.19). 
I then closed it out and reopened it in safe mode. The problem was still there. I then closed it and cleared the save state and reopened it normal mode and cleared the saved state and reopened in safe mode. The problem was still there. I then closed it and moved the <user>\.atom folder. repeating again opening in normal and safe mode. Problem continued. I checked for links and there were none. I had to skip the "Check Atom and Package Settings" because I was unable to open the settings or packages sections inside of atom. 

I restored my original <user>\.atom folder again to check for font rendering issues. I noticed a error count in the developer window. So when I switch to the console. I saw:
Uncaught (in promise) Error: EOVERFLOW, Unknown error
C:\wamp64\www\influxproject\html\application\helpers\myform_helper.php

Curious i closed Atom and reset to factory again and cleared saved state. When I open it back up and reopened the developer console. again I saw the same error. It made no since that point as to how and why it knew about that file after clearing the save state and restoring to factory default. I opened the file up in Notepad++ and turned on all symbols. I skimmed through the file looking for anything that seemed like it might not belong. I couldn't find anything. 

So I closed atom and moved the file to someplace else. When i reopened atom everything was back to normal. Thinking it might just be the file it's self still. I closed atom moved the file back to where it was and reopened atom. Yet when it opened Atom was acting normally like there wasn't even a problem. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10 Pro x64

### Additional Information
Attached is the crash log which apears to contain no real info of note, but included just in case. 
[operation_log.txt](https://github.com/atom/atom/files/1215029/operation_log.txt)

---

See https://github.com/atom/atom/issues/15236#issuecomment-322099135

**Comment by rsese** [comment]
Thanks so much for the detailed notes @pyromanci and thanks for working through the debugging steps :bow:

Not sure if we'll be able to figure out what happened since it's not reproducible (and a quick search didn't find any other Atom issues with `EOVERFLOW`) but before you closed Atom 2 night ago, do you happen to remember what you were doing before closing Atom?  Just working on a file and saved it, installing a package, etc?

In any case, we can leave this open for a bit in case someone else runs into the same error.

**Comment by pyromanci** [comment]
Ya. Since i couldn't reproduce it I felt is should include as much info as I could. All I was doing 2 nights ago was working on that myform_helper.php file and a few other php files all in the same project. I did use a few packages (Atom Beautify and SASS Autocompile), but did not install any.

**Comment by pjknkda** [comment]
I've experienced the same issue. When I try to open any file in the drive from sshfs, it throws the exception "Uncaught (in promise) Error: EOVERFLOW, Unknown error". Other text editors such like notepad++ or sublime text work as usual on that files.

It only occurs in atom 1.19.0 version and does not occur in atom 1.18.0.  Thus, I suspect https://github.com/atom/atom/pull/14435 may be related to this issue.

I'm using Windows 10 Pro x64 and the test was done with fresh install without any 3rd party packages.

**Comment by rsese** [comment]
Thanks @pjknkda - can you share the full stack trace?

**Comment by pjknkda** [comment]
I can only get exception with no stack trace when I use Chrome dev tools,

![image](https://user-images.githubusercontent.com/4986524/29302478-741ef7a0-81bf-11e7-87e7-269138698049.png)

Is there any way to get more detailed stack trace?

**Comment by rsese** [comment]
Thanks for checking, I was wondering if there was more details than just "Uncaught (in promise) Error: EOVERFLOW, Unknown error" and your screenshot shows a bit more info 👍

**Comment by 50Wliu** [comment]
@pjknkda how large is that README file?

**Comment by pjknkda** [comment]
It was 342 bytes. I also tested on a large file (~100MB) and the same exception has occurred.

**Comment by maxbrunsfeld** [comment]
@pyromanci @pjknkda I believe I have fixed this, but it would be great if you could help verify the fix.  [Here](https://ci.appveyor.com/project/Atom/atom/build/7859/job/hun1mdm9bs08th11/artifacts) is a page containing downloads for a version of Atom with the fix.

We will publish Atom 1.19.4 soon, and it will have the fix, but if you're interested you could try these downloads right away.

**Comment by pjknkda** [comment]
@maxbrunsfeld Thank you for the fix, however, I still have the same exception.

![image](https://user-images.githubusercontent.com/4986524/29706765-edcb9422-89bd-11e7-9778-6ddd33e399ca.png)

```
Uncaught (in promise) Error: EOVERFLOW, Unknown error 'V:\elice\elice-api\README.md'
Promise.reject (async)
step @ <embedded>:25580
Promise.reject (async)
completionCallback @ C:\Users\JK\AppData\Local\atom\app-1.19.4\resources\app\node_modules\superstring\index.js:73
```

(I've installed "AtomSetup.exe" file in your link.)

FYI, I'm using sshfs software (http://www.sftpnetdrive.com/) and I guess it may be correlated to its network drive implementation...

**Comment by maxbrunsfeld** [comment]
Wow, really sorry about that @pjknkda. Unfortunately, I haven't figured out what's happening yet, but this is still high priority for me. The next patch release of Atom will at least improve the error message slightly, which will help me determine why this `EOVERFLOW` error is happening.

**Comment by maxbrunsfeld** [comment]
Ok, Atom 1.19.4 is out. I don't think it will fix this bug but it will improve the error message slightly so that I can tell what system call is causing the error. If you get a chance, could you test again after upgrading? Thank you!

**Comment by pjknkda** [comment]
![image](https://user-images.githubusercontent.com/4986524/29803768-1c69b31a-8cb9-11e7-8261-26cfaf729adf.png)

@maxbrunsfeld Here is the log from the newest atom version. I've used "AtomSetup-x64.exe" installer file. Thank you!

**Comment by maxbrunsfeld** [comment]
Thanks so much for going through this @pjknkda, that's really helpful. Working on a fix now.

**Comment by maxbrunsfeld** [comment]
@pjknkda Atom 1.19.5 is out, and the code that was producing this error has been reworked. When you get a chance, please let me know whether this problem is fixed. Thanks!

**Comment by pjknkda** [comment]
I've just installed Atom 1.19.5 and it works perfectly! Thank you so much!

**Comment by maxbrunsfeld** [comment]
Thank *you* so much for reporting back to me so many times. I'm really sorry this was broken for so long.
