### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by robertung** [atom/atom#15263]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\sarr\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2173

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2171:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1509:43)
```

### Commands

```
     -1:18.7.0 core:save (input.hidden-input)
     -1:14.6.0 tree-view:duplicate (span.name.icon.icon-file-text)
  2x -1:13.8.0 core:move-right (input.hidden-input)
     -1:11.6.0 core:confirm (input.hidden-input)
     -1:10.6.0 core:close (input.hidden-input)
     -1:10 core:select-all (input.hidden-input)
     -1:09.6.0 core:paste (input.hidden-input)
     -1:09.2.0 core:save (input.hidden-input)
  2x -0:54.4.0 core:backspace (input.hidden-input)
     -0:53.2.0 core:save (input.hidden-input)
     -0:47.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:47 core:move-right (input.hidden-input)
  9x -0:46.3.0 core:move-down (input.hidden-input)
     -0:44.5.0 core:move-up (input.hidden-input)
  2x -0:40.7.0 core:undo (input.hidden-input)
     -0:30.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-css-comb 3.3.1 
language-postcss 1.3.1 
language-vue 0.23.0 
monokai-dark 1.3.0 
seti-ui 1.9.0 
```

**Comment by Ben3eeE** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by sys-error** [comment]
Hey there, I got the same error on  atom for macos just now. here is my stacktrace

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /Applications/Atom 2.app/Contents/Resources/app/src/text-editor-component.js:2173

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom 2.app/Contents/Resources/app/src/text-editor-component.js:2171:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom 2.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom 2.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom 2.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom 2.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom 2.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  2x -0:49.3.0 core:select-up (input.hidden-input)
     -0:31.5.0 window:save-all (input.hidden-input)
```

### Non-Core Packages

```
chester-atom-syntax 0.2.1 
chester-atom-syntax 0.2.1 
```

**Comment by celine-m-s** [comment]
Hey!

I just got the same error. I was typing on a long text using GitHub Markdown. 


**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2173

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2171:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:37.4.0 intentions:highlight (input.hidden-input)
  6x -1:37.3.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -1:36 editor:move-to-end-of-word (input.hidden-input)
     -1:35.1.0 intentions:highlight (input.hidden-input)
     -1:35 editor:move-to-beginning-of-word (input.hidden-input)
     -1:34.6.0 core:move-left (input.hidden-input)
  2x -1:34.3.0 core:backspace (input.hidden-input)
     -1:31.1.0 core:move-right (input.hidden-input)
     -1:30.8.0 core:move-down (input.hidden-input)
  2x -1:25.3.0 editor:select-to-beginning-of-word (input.hidden-input)
  3x -1:13.8.0 core:backspace (input.hidden-input)
  2x -1:00.6.0 editor:newline (input.hidden-input)
  2x -0:58.8.0 core:backspace (input.hidden-input)
  2x -0:58.2.0 core:move-down (input.hidden-input)
  2x -0:57.4.0 editor:newline (input.hidden-input)
  2x -0:56.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-pylint 2.1.0 
linter-ui-default 1.2.4 
```

**Comment by rsese** [comment]
Thanks @sys-error @celine-m-s - @sys-error can you answer the same questions from https://github.com/atom/atom/issues/15263#issuecomment-321928302?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

@celine-m-s can you reproduce the error you saw in safe mode when typing a long line of text in Markdown?

**Comment by sys-error** [comment]
Hi there. I had a project open with five tabs, and after being idle for
about seventy minutes, i noticed the active line with the cursor was wrong.
When i triwd to correct it the errors popped up. All the same error till i
killed the app.

The active tab had well over 4000 lines in it.

**Comment by celine-m-s** [comment]
Hello!

I'm sorry, I closed the app and now I can't reproduce the error. I kept having it until I close the app yesterday.

Promess, if I see the error again I'll launch into safe mode and see if I can reproduce the error.

Cheers!

**Comment by iolsen** [comment]
Potentially fixed by https://github.com/atom/atom/pull/15270.

/cc @nathansobo @as-cii

**Comment by Ben3eeE** [comment]
@iolsen There is one report of this happening in Atom 1.19.2 which is after that PR was hotfixed. /cc: https://github.com/atom/atom/issues/15390

**Comment by nathansobo** [comment]
@as-cii I have stared at this for over an hour and am still having a hard time understanding what could be happening here.

To get this exception, we must have a screen line in the `renderedScreenLines` or `extraRenderedScreenLines` that does not correspond to a DOM node on screen. From what I can tell, whenever we update either of these pieces of state, we always proceed to synchronously update the DOM based on their contents. There should never be a gap in time where either of these pieces of state don't match what's on the DOM.

This makes me wonder whether there's a subtle bug in our line update logic where we are sometimes not actually rendering a line that's in one of these two structures. It's pretty difficult to tell. Worse, I'm not seeing any of these exception in bugsnag. Does everyone that's reporting it have metrics disabled?

**Comment by cyee88** [comment]
I am experiencing the same issue. To answer the questions:

what were you doing at the time of the error?  [cyee88] I was adding a line return to create a new paragraph?
is the error is reproducible? [cyee88] Yes.
if reproducible, do you see the error in safe mode (atom --safe)? [cyee88] Yes.

Here's the stack trace:

Uncaught Error: Requested measurement of a line that is not currently rendered

C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\text-editor-component.js:2244
Hide Stack Trace
Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\text-editor-component.js:2242:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\text-editor-component.js:2235:45)
    at TextEditorComponent.measureContentDuringUpdateSync (C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\text-editor-component.js:398:16)
    at scheduler.readDocument (C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\text-editor-component.js:280:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\view-registry.js:191:15)
    at C:\Users\cyee\AppData\Local\atom\app-1.19.5\resources\app\src\view-registry.js:3:65

**Comment by 50Wliu** [comment]
Two more reports.
```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2272

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2261:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2254:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1468:18)
    at TextEditorComponent.didAttach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1435:20)
    at HTMLElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:138:24)
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:146:16)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:232:25)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:197:27)
    at /Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:240:30
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:939:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:650:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```
and
```
At C:\Users\Dallin.Green\AppData\Local\atom\app-1.20.0\resources\app\src\text-editor-component.js:2272

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:2261:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:2254:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:1561:59)
```

No repro steps.  Neither had any community packages installed.

**Comment by smayton** [comment]
This happened when i used the Pane Layout package and moved the divider between panes. I resolved it by: Preferences > Editor and unchecking Word Wrap.

**Comment by Ben3eeE** [comment]
@smayton Can you reproduce the error consistently with that package? Can you link to the package you were using? Thank you :bowing_man:

**Comment by smayton** [comment]
I can reproduce it consistently with Atom 1.20.0 and 1.20.1 (I updated to 1.20.1 to see if this specific bug was fixed) with Preferences > Editor: Soft Wrap enabled.

Package that produced the error: https://atom.io/packages/pane-layout-plus (0.7.3)

**Comment by Ben3eeE** [comment]
@smayton Thank you for the additional information 🙇 I tried to reproduce using that package but it doesn't seem to happen for me.

* Can you record a screen capture of reproducing the issue?
* Does it happen with any file? Is the file you have open in a public repo so we can try with that file?
* Can you paste the output of `apm list --installed` ?

**Comment by rsese** [comment]
After chatting about this more, we're going to close this one again since the error itself can be triggered in multiple ways and the wave of reports we saw before 1.26 has slowed down quite a bit since the fix.
