### ISSUE TITLE
Atom gives a quick white blink/flickering when you do something

### ISSUE THREAD

**Issue by gusbemacbe** [atom/atom#15323]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you type and open the snippets, or when you save, or when you scroll quickly the page, Atom always gives a quick white blink. 

### Steps to Reproduce

1. Type or type a snippet or save or scroll quickly the page, while see with attention
2. You'll see the quick white blink

**Expected behavior:** 
The quick white blink always repeats or appears when you do these things

**Actual behavior:** 
After the quick white blink, nothings happened, it was all normal, but the quick white blink will appear or repeat.

**Reproduces how often:**
Millseconds

### Versions

**Atom         :** 1.19.0
**Electron    :** 1.6.9
**Chrome    :** 56.0.2924.87
**Node        :** 7.4.0

apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.3

macOS Sierra X 10.12.6
Mac mini Mid 2011 Core i5 8GB RAM

**Comment by rsese** [comment]
I'm unable to reproduce (or my eyes just aren't catching it) - can you confirm if this behavior is new for you as of 1.19.0 and you didn't see it in 1.18.0?

**Comment by gusbemacbe** [comment]
I tested, nothing happened in Windows. I think it happens only on Mac.

**Comment by rsese** [comment]
> If your eyes are not catching, because the white blink is too much quick or maybe you are not a Mac user.

Yep I tested on macOS 10.12.6 but maybe it's too quick for me?  My laptop is a newer Macbook Pro so maybe that's part of it too.

Do you think it's still so quick that a screencast or GIF wouldn't capture the behavior?

**Comment by gusbemacbe** [comment]
I updated to Atom 1.19.2 and I'm going to see if this behaviour still happens.

**Comment by gusbemacbe** [comment]
I have just tested, I caught a quick white blink in Atom 1.19.2. The problem is that it will take a lot to catch the quick white blin during the record. Therefore, I have to cut the video.

**Comment by rsese** [comment]
Another report in https://github.com/atom/atom/issues/15648, also mentioned that it wasn't an issue in 1.18.0 - I'll ask the team to take a look.

**Comment by gusbemacbe** [comment]
Great, I tried to record a white flash, but it took much time to catch the white flash red-flagged. So I gave up and I had to get used with the white flash.

**Comment by burabure** [comment]
here's the gif on this happening for convenience

![untitled 1](https://user-images.githubusercontent.com/3132298/30411480-82e18d0e-98e7-11e7-9a6e-51d4815faa51.gif)

```
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by gusbemacbe** [comment]
Observe that it is still present in Atom Beta 1.21 too.

**Comment by VulumeCode** [comment]
I have the same issue on Xenial since a few versions ago. 

I have the same issue with Chromium, but way less often. Maybe only when it's under heavy load, definitely when developing Ember apps.

**Comment by burabure** [comment]
@VulumeCode I tested to see if heavy loads were related but it doesn't seem to be the case, I just think it's an issue with the new rendering architecture introduced in 1.9

**Comment by rsese** [comment]
Just wanted to mention that I asked the team about this and we'd like to wait and see if an Electron upgrade tentatively planned for sometime in October fixes this issue.

**Comment by Kay2dan** [comment]
Happening on both of my Ubuntu 16.04 machines as well.

**Comment by olivierlambert** [comment]
Happening on Fedora 26 with latest Atom stable too.

**Comment by marshallford** [comment]
Happening on Arch Gnome 3 and latest Atom stable.

**Comment by flamein** [comment]
definitely related to load. With ansible linters on a huge playbook, you'll quickly know if you're epileptic.

**Comment by burabure** [comment]
@flamein check if it happens on safe mode

**Comment by flamein** [comment]
opening a load of stuff files, it doesn't.
It might be related to a single package then, or just the load of adding several packages.

**Comment by burabure** [comment]
@flamein yours might be a different issue then, for me it happens on safe mode without any package or load.

**Comment by flamein** [comment]
hmm yes, looks more like: https://github.com/atom/atom/issues/15032
Although they might be related

**Comment by mishaone** [comment]
+1 on Fedora 26 with Atom 1.22

**Comment by gusbemacbe** [comment]
Unfortunately Atom Beta 1.23.0-beta1 still has this problem, @rsese.

**Comment by tvld** [comment]
Upgraded today to 1.22.1 and this problem was introduced (Ubuntu 16.04)

**Comment by pascalduez** [comment]
Same issue on Atom 1.22.1 on both Ubuntu and Arch Linux, starts to flicker several times as soon as an action is launched (save, lint, format, upgrade package, etc...)

**Comment by gusbemacbe** [comment]
After three months, this problem is unsolved. How unhelpful!

**Comment by tvld** [comment]
To me it seem using F11, full screen, solves a bit but not all… But maybe I am just overly optimistic ;)

**Comment by burabure** [comment]
gave up on atom because of this, moved on to Visual code and I'm loving it. much faster and less buggy.

**Comment by rsese** [comment]
Sorry everyone - the Electron upgrade hasn't happened yet but we'll post back in here when it does happen so folks can confirm if that resolves this issue.

**Comment by ddon** [comment]
Flashing in 1.22.1 on MacOS...  Very annoying...

**Comment by tvld** [comment]
@ddon - working in Fullscreen works for Ubuntu...

**Comment by gusbemacbe** [comment]
@burabure, I hate Visual Studio, because it was too difficult to set PHP server, and phpcs expected me to install pear for installing PHP Codesniffer, and Pear destroyed my macOS and PHP, causing one of extensions to disappear – v8js. I tried to repair for more than 5 hours. I uninstalled and reinstalled Homebrew, and did a small clean, and the error continues the same. Then I had to a clean install of macOS.

Visual Studio Code and php are worse for PHP developers and programmers who use macOS. They give me headache. 

I prefer Atom, because too easy and simple to set PHP, and I didn't have to install the damned Pear, I installed only Homebrew and composer via Homebrew.

**Comment by gusbemacbe** [comment]
@burabure, I didn't need to make a clean install of macOS, I had an idea and I found a solution… I removed v8js extension from `php.ini`s and removed e`xt-v8.ini`. I brew-uninstalled and reinstalled `php` with `httpd` and no errors finally. I adapted myself quickly to Visual Studio Code. I just will avoid `pear`, so Pear is the Perses, a god of destruction.

**Comment by marshallford** [comment]
This issue is driving me nuts!

**Comment by tvld** [comment]
@marshallford does full screen work for you? F11 in Ubuntu?

**Comment by marshallford** [comment]
@tvld unfortunately no.

**Comment by tvld** [comment]
It's weird. On my desktop, Ubuntu 16.04, i have the issue, but not in full screen mode. 

On laptop with Ubuntu 17.04 all is fine all the time...

**Comment by tbenst** [comment]
This issue persists on 1.23.1 on Ubuntu 16.04. I upgraded from 1.18, where this did not happen.

**Comment by lorendias** [comment]
Is this the same as the white flash when resizing?

![screencast from 01-07-2018 10_38_24 pm](https://user-images.githubusercontent.com/29697326/34661182-d196d97a-f3fc-11e7-862b-2183e0a12b62.gif)

**Comment by mihirsam** [comment]
Any fix yet, I hate this!

**Comment by awilkins** [comment]
Just got this again today on a laptop I've not seen it on before because I switched to the Intel GPU instead of the nvidia trying to save battery.

Anyone experiencing this who

* Doesn't have an Intel Skylake processor
* Isn't using the internal GPU

?

Those using Skylake GPUs may want to try the recommendations in the last comment in this thread over on the Arch BBS.

https://bbs.archlinux.org/viewtopic.php?id=208299

**Comment by flamein** [comment]
I have a kaby lake and have these issues.
Arch linux workaround mentioned there is for Xorg, i use Wayland on Fedora 27.

the atom --disable-gpu seems to work though, but it's a dirty workaround. (which fails when restarting atom from within atom for updates)

**Comment by carlvdm** [comment]
Can confirm that I'm seeing these issues appearing regularly on: Ubuntu 16.04.3 LTS

**Comment by tvld** [comment]
I upgraded from 17.04 to 17.10 today. Now I also have the white blink :-( ...
Might it be a Wayland thing?

**Comment by rsese** [comment]
The Electron upgrade is available in master right now so will be available to try in the next beta I believe, 1.25.  If anyone who's hitting this issue on a Mac wants to give it a try now, you can download a macOS build with the Electron upgrade here:

https://6815-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip

**Comment by pascalduez** [comment]
`1.25.0-beta0` on Ubuntu 16.04 LTS, still flashing like crazy...

**Comment by awilkins** [comment]
There sure is something not good about the combination of Atom (or Electron) on these Intel integrated graphics sets.

e.g. My benchmark for whether the white flickering is present is installing `atom-beautify` because this is a big package with lots of deps.

If you do this via apm at the command line it's relatively quick. Do it from the UI on one of these iGPUs on Linux and...

* Atom now has 3 processes between them consuming between 200-300% of CPU time
* Plus `apm` consuming 100% of a CPU
* Install takes something like 5x longer

Objectively the only thing that a GUI install is doing that CLI `apm install` isn't is displaying the stripey throbber on the install button (and presumably also processing the STDOUT of apm or something so it knows when it finished).

My white flickers have gone though. Not sure if this is because I've moved that laptop to Fedora (but fairly sure it flickered) ; I'll switch to the Intel GPU on my Ubuntu laptop and give it a go.

**Comment by marshallford** [comment]
I haven't had a chance to experiment with the new 1.24 and 1.25 builds, anyone have any _good_ luck?

**Comment by gilbertohasnofb** [comment]
I had read somewhere that the issue could have been caused by the linter package, so I disabled the packages `linter`, `linter-pylama`, and `linter-ui-default` with Atom 1.23.3. This seem to have done the trick on my side, as I haven't noticed any more flickering since then.

**Comment by gusbemacbe** [comment]
@gilbertohasnofb, and with `atom-beautify` enabled?

**Comment by gusbemacbe** [comment]
@awilkins, the problem is that, I use a Mac and you use Linux. Do I have to compile the repository?

**Comment by flamein** [comment]
From what I've seen so far it's not just one package. More like when
anything does heavy work and needs to draw something on screen.

**Comment by gilbertohasnofb** [comment]
@gusbemacbe Yes, I do have `atom-beautify` enabled. And I am on Linux if that matters at all.

**Comment by rsese** [comment]
The 1.25 beta has the Electron upgrade - can anyone seeing this issue confirm if this is still a problem on 1.25?

**Comment by Thebarda** [comment]
I'm running on Ubuntu 17.10 and Gnome on Xorg as desktop environment, Atom don't gives white blinks. 
But when I'm running on Gnome on Wayland, Atom gives white blinks. 

Note : I have an Intel Kaby Lake.

**Comment by 50Wliu** [comment]
@Thebarda and what Atom version are you using?

**Comment by gusbemacbe** [comment]
I spent a lot of time with Atom on Windows and on macOS. No white blinks/flickers. If the white blink appears, I'll report to you.

**Comment by Thebarda** [comment]
@50Wliu I'm using 1.24.0

**Comment by 50Wliu** [comment]
@Thebarda please try Atom 1.25 beta as suggested above.

**Comment by pascalduez** [comment]
`1.25.0-beta0` on Ubuntu 16.04 LTS, flashing.
`1.25.0-beta0` on Ubuntu 17.10 (wayland), flashing. 
Will give it a try on 17.10 (xorg).

**Comment by Thebarda** [comment]
@50Wliu Thanks. That solves my problem

**Comment by bh** [comment]
Atom 1.24.0 on Arch Linux x86_64 (current) with Wayland: **flashing**
Atom 1.26.0.dev.34465 on Arch Linux x86_64 (current) with Wayland: **not flashing**

@50Wliu Thanks. That fixes the issue.

**Comment by kmyokoyama** [comment]
1.25.0-beta2 on Ubuntu 16.04 LTS still flashing.

**Comment by gusbemacbe** [comment]
@kmyokoyama, you need to upgrade from 1.25 to 1.26.

**Comment by Arcanemagus** [comment]
@gusbemacbe The v1.25.0-beta0 build includes the Electron update theorized to fix this, v1.26.0 development builds aren't necessary (but _also_ would include that Electron update).

@kmyokoyama Your graphics driver in use, as well as the display server (X, Wayland, ?) would be helpful.

**Comment by ilavidas** [comment]
Has anyone tried this?
https://github.com/steelbrain/linter/issues/1372#issuecomment-287307487

**Comment by awilkins** [comment]
* 1.25.0-beta3
* Ubuntu 16.04
  * Xorg 1.18.4
  * `i915_bpo` GPU driver (Xorg log claims it's the i965 driver though)
  * DRI2 rendering mode
* GPU `00:02.0 VGA compatible controller: Intel Corporation Skylake Integrated Graphics (rev 06)`
  * Still block-blinks under load (my usual test of installing `atom-beautifier` came up naturally this morning because it had an update)
* OR `01:00.0 3D controller: NVIDIA Corporation GM107GLM [Quadro M1000M] (rev ff)`
  * Still steady

(this machine is great for testing this issue because it's the exact same hardware but I can flip GPUs)

I think it's much improved, it's nowhere near as pronounced now, but now there are also "blank blinks" where the text blanks out a moment in a similar pattern to the white blinks.

Going to try this from the Arch wiki : [turning off vsync](https://wiki.archlinux.org/index.php/intel_graphics#Disable_Vertical_Synchronization_.28VSYNC.29). The symptoms described - of Chrome having slow performance unless you use ``--disable-gpu`` - mesh very much with the other symptoms I experience with this, which is that performance of graphics updates in Atom are v.v.slow and impact other processes - e.g. installing `atom-beautify` can take 5-10x longer than it takes via `apm install`. While doing it via the GUI is slower than the command line on a non-Intel GPU box, it's more like 1.2-1.5x rather than the incredible slowness.

Think the overall takehome here is that the drivers for Intel integrated GPUs have some kind of "quirk" (bug) that Chrome/Blink particularly triggers and thus Atom is especially hard on as a hard-working multi-layout app.

**Comment by martinosorb** [comment]
```
Atom    : 1.25.0-beta3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

Still flashing on Ubuntu 16. This is quite serious, I'll have to change to another editor until it's fixed I think :(

**Comment by martinosorb** [comment]
Update: @ilavidas 's suggestion to try steelbrain/linter#1372 (comment) worked for me! Hooray!

**Comment by awilkins** [comment]
I'm finding the [disable vsync](https://phoronix.com/scan.php?page=news_item&px=Ubuntu-Debian-Abandon-Intel-DDX) workaround I linked above (and here) to be quite acceptable also - I'm still switched to my Intel GPU not the nvidia, and I've not thrown my laptop out of the window.

The comments in the linter bug link to a Phoronix post that seems to think that using the modesetting driver may cure this... sadly it's not available for Ubuntu 16.04 (which I'm sticking with at present because I'm one of those weirdos who likes the Unity desktop).

**Comment by lionep** [comment]
Does it still happen in DRI 3?
It fixes for me on the same kind of blink with css animations in electron

**Comment by danielsalles** [comment]
My notebook is Nvidia, but I have the drivers disabled. I'm keeping the one from Intel, and those flash's have happened quite often.

**Comment by danielsalles** [comment]
I uninstalled the NVidia driver and the error seems to have stopped.

I use Linux.

**Comment by PostholerCom** [comment]
I've been using atom for about a month now and love it. I can easily duplicate the flash and ensuing crash. Search for something when that search term isn't present. The screen flashes, editor freezes and I get an alert asking me if I want to force exit, which you have to. I'm on centos 7.2. Here's the debug info when it cores. Looks like a GL issue and possible race condition:

/usr/bin/atom: line 129:  2958 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[2980:0410/193817.707749:ERROR:gles2_cmd_decoder.cc(17045)] [.RenderWorker-0x2b110fdc2c00]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[2980:0410/193817.708047:ERROR:gles2_cmd_decoder.cc(16316)] [.RenderWorker-0x2b110fdc2c00]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0

**Comment by drguiom** [comment]
As far as I can tell this is very much dependent on the load of the host running Atom. I get this reliably on OSX (latest) and lates version of Atom when the CPU is high.

It seems to be related also to the size of the file open (in terms of line) and possibly the linter in use (linter-php 1.5.1)

**Comment by Akumzy** [comment]
I think this flickering is either from Ubuntu or Electron am facing same issue  with vscode and my electron apps
Ubuntu: 17.10

**Comment by flamein** [comment]
Sad to say, it has happened again for me after update to Atom 1.26.1 on Fedora 27.
further info:
- Display: wayland
- CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
- VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)

**Comment by meowsus** [comment]
I can't tell if these are my seizures or the editor anymore.

**Comment by flamein** [comment]
Okay, still there with Atom 1.27.0 on Fedora 28.

@PostholerCom: what is your setup?
- Display server
- CPU 
- Graphics
- Atom --disable-gpu flag passed or not?

**Comment by 50Wliu** [comment]
Electron was upgraded to 2.0.0 in Atom 1.28.0 beta.  Would anyone mind testing that version?

**Comment by gusbemacbe** [comment]
@50Wliu It worked everything. 

@burabure can you test it for us, please? I tested it and it was everything normal. I am not sure about you.

**Comment by PostholerCom** [comment]
I upgraded to 1.27.0 this morning. So far, so good. It hasn't crashed once and I've tried. I'll give it a day or two.

**Comment by PostholerCom** [comment]
1.27.0 crashed on me this morning. Bummer.

**Comment by gusbemacbe** [comment]
@PostholerCom you have to update to 1.28-beta to test. He didn't ask you to test 1.27. He asked you to test 1.28.

**Comment by PostholerCom** [comment]
I got 1.28.0 beta to crash almost immediately. 

Atom    : 1.28.0-beta0
Electron: 2.0.0
Chrome  : 61.0.3163.100
Node    : 8.9.3

ps -ef: 

user    8822     1  0 11:31 pts/1    00:00:00 /bin/bash /usr/bin/atom-beta
user    8824  8822  9 11:31 pts/1    00:00:15 /usr/share/atom-beta/atom --executed-from=/home/user --pid=8811
user    8826  8824  0 11:31 pts/1    00:00:00 /usr/share/atom-beta/atom --type=zygote --no-sandbox
user    8872  8824  6 11:31 pts/1    00:00:10 /usr/share/atom-beta/atom --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,9,27,70,84 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0f31 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=E8B012139F21224CB8F6AC037396F645

**Comment by gusbemacbe** [comment]
@PostholerCom Strange, it worked here without crash and blink. 

@50Wliu, issue this to Electron team.

**Comment by danielsalles** [comment]
Version 1.27.0 made this worse.

**Comment by 50Wliu** [comment]
@PostholerCom This issue is not about crashes.  Please file a new issue.

@danielsalles as I mentioned above, it would be very helpful if you could also test Atom 1.28.0 beta.

**Comment by PostholerCom** [comment]
@50Wliu 'Crash' is the wrong word and I shouldn't use it. As stated above, I search, the screen flickers white and the editor locks for about 15 seconds, then a popup asks if I want to quit. Saying no, leaves your with a locked up editor. Yes is the only response.

**Comment by pascalduez** [comment]
```
Atom    : 1.28.0-beta1    
Electron: 2.0.1           
Chrome  : 61.0.3163.100   
Node    : 8.9.3        
```
Ubuntu 17.10

Flashing really badly.  
Several white flashes, menu tree and panes flickering.

**Comment by rmasp98** [comment]
Happens for me too!

Versions
Atom : 1.19.0
Electron : 1.6.9
Chrome : 56.0.2924.87
Node : 7.4.0

Arch Linux
Razer Blade Stealth 2016 Core i7 16GB RAM

I found a complaint about not being able to bind texture 0 in opengl and also get:
`org.gnome.Shell.desktop[801]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1a00001 (Atom)` 

I get this stack trace if it helps:
`Jun 19 12:29:30 Rayleigh systemd-coredump[28304]: Process 28237 (electron) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 28237:
                                                  #0  0x00007fccfbba286b raise (libc.so.6)
                                                  #1  0x00007fccfbb8d40e abort (libc.so.6)
                                                  #2  0x000055eacee70882 n/a (electron)
                                                  #3  0x000055eacee70353 n/a (electron)
                                                  #4  0x000055eacfd66ac1 n/a (electron)
                                                  #5  0x000055ead079e1fb n/a (electron)
                                                  #6  0x000055ead079d7a7 n/a (electron)
                                                  #7  0x000055ead079d6f8 n/a (electron)
                                                  #8  0x000055ead07e4b93 n/a (electron)
                                                  #9  0x000055ead07baf16 n/a (electron)
                                                  #10 0x000055ead07ce331 n/a (electron)
                                                  #11 0x000055ead079bfb9 n/a (electron)
                                                  #12 0x000055ead0794934 n/a (electron)
                                                  #13 0x000055ead07946e2 n/a (electron)
                                                  #14 0x000055ead079303e n/a (electron)
                                                  #15 0x000055ead06c3fe3 n/a (electron)
                                                  #16 0x000055ead0818993 n/a (electron)
                                                  #17 0x000055eaceeb48ed n/a (electron)
                                                  #18 0x000055eacee74215 n/a (electron)
                                                  #19 0x000055eacee745e8 n/a (electron)
                                                  #20 0x000055eacee74a47 n/a (electron)
                                                  #21 0x000055eacee7666a n/a (electron)
                                                  #22 0x00007fcd0264a368 g_main_context_dispatch (libglib-2.0.so.0)
                                                  #23 0x00007fcd0264a5b1 n/a (libglib-2.0.so.0)
                                                  #24 0x00007fcd0264a63e g_main_context_iteration (libglib-2.0.so.0)
                                                  #25 0x000055eacee764f7 n/a (electron)
                                                  #26 0x000055eacee840cc n/a (electron)
                                                  #27 0x000055eacf4af4b6 n/a (electron)
                                                  #28 0x000055eacef126d7 n/a (electron)
                                                  #29 0x000055ead0671d2d n/a (electron)
                                                  #30 0x000055eacef11102 n/a (electron)
                                                  #31 0x000055ead222f388 main (electron)
                                                  #32 0x00007fccfbb8f06b __libc_start_main (libc.so.6)
                                                  #33 0x000055eacee3c02a _start (electron)
                                                  
                                                  Stack trace of thread 28242:
                                                  #0  0x000055eacee3c2de __libc_free (electron)
                                                  #1  0x000055eacf8d22ed n/a (electron)
                                                  #2  0x000055eacf8da6ba n/a (electron)
                                                  #3  0x000055eacf8daa93 n/a (electron)
                                                  #4  0x000055eacf8ce8b5 n/a (electron)
                                                  #5  0x000055eacf8ce71a n/a (electron)
                                                  #6  0x000055eacf8d957d n/a (electron)
                                                  #7  0x000055eacf8d74ea n/a (electron)
                                                  #8  0x000055eacf8cb261 n/a (electron)
                                                  #9  0x000055eacf8ece5f n/a (electron)
                                                  #10 0x000055ead06c07ee n/a (electron)
                                                  #11 0x000055eacf6a8bb5 n/a (electron)
                                                  #12 0x000055eacf6a84c4 n/a (electron)
                                                  #13 0x000055eaceeb48ed n/a (electron)
                                                  #14 0x000055eacee74215 n/a (electron)
                                                  #15 0x000055eacee745e8 n/a (electron)
                                                  #16 0x000055eacee74a47 n/a (electron)
                                                  #17 0x000055eacee76db9 n/a (electron)
                                                  #18 0x000055eacee840cc n/a (electron)
                                                  #19 0x000055eaceebc9b2 n/a (electron)
                                                  #20 0x000055eacee7fb33 n/a (electron)
                                                  #21 0x00007fcd066ec075 start_thread (libpthread.so.0)
                                                  #22 0x00007fccfbc6453f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 28251:
                                                  #0  0x00007fcd066f23f6 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                  #1  0x000055eacee8a533 n/a (electron)
                                                  #2  0x000055eaceeded1b n/a (electron)
                                                  #3  0x000055eaceedee3d n/a (electron)
                                                  #4  0x000055eaceeb92c4 n/a (electron)
                                                  #5  0x000055eaceeb990e n/a (electron)
                                                  #6  0x000055eacee7fb33 n/a (electron)
                                                  #7  0x00007fcd066ec075 start_thread (libpthread.so.0)
                                                  #8  0x00007fccfbc6453f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 28239:
                                                  #0  0x00007fcd066f1ffc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                  #1  0x00007fcce91400a4 n/a (i965_dri.so)
                                                  #2  0x00007fcce913fd98 n/a (i965_dri.so)
                                                  #3  0x00007fcd066ec075 start_thread (libpthread.so.0)
                                                  #4  0x00007fccfbc6453f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 28240:
                                                  #0  0x00007fcd066f23f6 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                  #1  0x000055eacee8a533 n/a (electron)
                                                  #2  0x000055eaceeded1b n/a (electron)
                                                  #3  0x000055eacee76103 n/a (electron)
                                                  #4  0x000055eacee840cc n/a (electron)
                                                  #5  0x000055eaceebc9b2 n/a (electron)
                                                  #6  0x000055eacee7fb33 n/a (electron)
                                                  #7  0x00007fcd066ec075 start_thread (libpthread.so.0)
                                                  #8  0x00007fccfbc6453f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 28241:
                                                  #0  0x00007fccfbc6485f epoll_wait (libc.so.6)
                                                  #1  0x00007fccfeeb5a95 n/a (libevent-2.1.so.6)
                                                  #2  0x00007fccfeeab8f4 event_base_loop (libevent-2.1.so.6)
                                                  #3  0x000055eacee76d93 n/a (electron)
                                                  #4  0x000055eacee840cc n/a (electron)
                                                  #5  0x000055eaceebc9b2 n/a (electron)
                                                  #6  0x000055eacee7fb33 n/a (electron)
                                                  #7  0x00007fcd066ec075 start_thread (libpthread.so.0)
                                                  #8  0x00007fccfbc6453f __clone (libc.so.6)
-- Subject: Process 28237 (electron) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 28237 (electron) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
`

**Comment by flamein** [comment]
It still seems to be present, although less then before.
now only happens under severe load, linting 4 ansible playbooks at the same time.

**Comment by chaitanyathengdi** [comment]
Happens for me:
```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

Ubuntu 16.04 LTS, running on an i3-4130 with integrated graphics.

Running atom with the `--disable-gpu` flag seems to mitigate the issue, but normally the flicker happens when something changes in the UI, such as a popup or fetch/push etc.

**Comment by gusbemacbe** [comment]
@chaitanyathengdi 

The version 1.26 is out of date. Check the https://atom.io/ and see that the current version is 1.29.

**Comment by flamein** [comment]
I still get this with atom 1.29.0

Although i have seen similar issues on Slack which might point to electron
after all. It's less noticeable on Slack for me as the background is white
anyway.


Met vriendelijke groet / Kind regards,

*Finke Lamein*

Devops Engineer
*T:*+31 6 52 17 95 63
*E:*f.lamein@catawiki.nl
*W:*www.catawiki.nl | www.catawiki.com

**Comment by chaitanyathengdi** [comment]
@gusbemacbe Still noticing on Atom 1.29.0.

```
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by pascalduez** [comment]
Looks like it's finally behind me.

```
Atom    : 1.30.0-beta0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

Ubuntu 18.4.1

**Comment by adavie1** [comment]
I am having this issue as well- current version of **Atom 1.26.1** on **Ubutuntu 16.04 LTS**
Linux gaia 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
ares: "1.10.1-DEV"
atom-shell: "1.7.11"
chrome: "58.0.3029.110"
electron: "1.7.11"
http_parser: "2.7.0"
modules: "54"
node: "7.9.0"
openssl: "1.0.2k"
uv: "1.11.0"
v8: "5.8.283.38"
zlib: "1.2.11"
```
Some releases of Atom it goes away, then another release the issue comes back.

I get that this may be an Electron issue- however, it's hurting Atom.

I am (**gasp**) even considering moving to Visual Studio Code. I really like Atom, but after years of this issue not being fixed, it's get a bit much. I've been using Atom since version 0.5X.

**Comment by awilkins** [comment]
Reverted the `.drirc` workaround from Arch wiki mentioned in my comment above while on `1.30.0-beta2` and, wow, the flickers are more horrible than ever. The workaround must be really good though...

Now going to try `1.31.0-beta0` because the changelog mentions some WebGL changes from Electron that got merged...

Nope, still horribly flickery.

<puts `.drirc` back>

Still running on 

* Ubuntu 16.04
* Intel Skylake integrated graphics

**Comment by gusbemacbe** [comment]
@adavie1, ATom still uses Electron instead of Electron 2!

They should upgrade to Electron 2 and to Electron 3!

I ran Atom, using Electron 2 and 3.

**Comment by rajsingha4520** [comment]
I am an Android developer. I read in class 12
I am very poor please help me with some money I have a computer with 2 gb ram and Intel process I developes app on it but it's hard to run ...so please donate me some money. Bank name - UCO Bank , MY Bank account number - 06570110036969 , Swift code - UCBAINBB102 , Ifsc code - UCBA0000657 , Account holder name - Raj Singha ..I am from India . Please donate as you like.

**Comment by Asday** [comment]
Reasonably sure this is happening when you have enough elements at once.  I have two files open, one 1700 lines long, one 484 lines long, and that's 274KiB of HTML in the `<body />` element.  This is about 10 minutes into me starting work on this, and I generally end up with 10-20 files open at once while chasing down an issue.

It seems to me that this just isn't what HTML is for, as convenient as it seems.

**Comment by flamein** [comment]
I believe Atom 1.30.0 finally solved this, so please check if you're on that version.

**Comment by Asday** [comment]
I can confirm it's not at all fixed on 1.13.0.

Just open up some large files, perhaps even have two of the same file open in different panes, and scroll around, and perhaps click in some places.  Currently half my treeview failed to repaint, and I have several large squares of solid background colour where there should be text and such.

**Comment by gusbemacbe** [comment]
@Asday, you have confounded 1.13 with 1.30. The version 1.13 is too too old and is no longer supported. Please switch to 1.30.

**Comment by ssfrr** [comment]
I was still seeing this issue on Atom 1.32-beta0. I was able to fix it by changing the DRI vsync settings.

Create a file called `~/.drirc` with the contents:

```xml
<device screen="0" driver="dri2">
	<application name="Default">
		<option name="vblank_mode" value="0"/>
	</application>
</device>
```
According to [this random reddit post](https://www.reddit.com/r/linuxquestions/comments/4ua5tk/vblank_mode_setting/d5o6m7t/) this setting will disable vsync. If this causes issues with other apps you should be able to make this specific to atom by adding an `executable=atom` option to the `application` tag, but I haven't tested that. See [here](https://dri.freedesktop.org/wiki/ConfigurationInfrastructure/) for more info on this config file).

Before this change I was seeing the flickering quite frequently (probably at least once a minute), but after creating this file (and rebooting, though suspect that's not necessary) I haven't seen any flickering.

I got the idea from the [arch wiki](https://wiki.archlinux.org/index.php/intel_graphics#Disable_Vertical_Synchronization_.28VSYNC.29).

**Comment by ssfrr** [comment]
Also cross-linking #14776 because it doesn't seem to be otherwise marked as a duplicate.

**Comment by PostholerCom** [comment]
Here's the solution I've found.

If I go into Edit->Preferences and change 'Color Profile' to sRGB, then allow atom to reload at the prompt, everything works great. BUT, when I normally close atom and open it again I get the same flickering mess. If I go through the steps again, it is fine.

@ssfrr I tried your fix without success. But thanks for the tip!

**Comment by PostholerCom** [comment]
Still happening on 1.31.2

Fortunately, the above hack still works.

**Comment by Asday** [comment]
More in-depth work has been done, and the flickering returned.  I didn't need to set sRGB each time, but if the flickering starts, switching the profile between sRGB and default and letting Atom restart itself seems to assuage the issue.

**Comment by ryanvade** [comment]
Tried out the sRGB fix and it doesn't seem to work for me.  Atom is now almost unusable with all plugins disabled the flickering occurs constantly (almost every time I open the command pallet for example). :-1: 

Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS      : Fedora 28
Desktop : GNOME
CPU     : i7-6500U
Graphics: Intel HD 520
Ram     : 12 GiB

**Comment by ryanvade** [comment]
![screenshot from 2018-10-16 14-04-59](https://user-images.githubusercontent.com/1910293/47040789-cb1a0580-d14c-11e8-8ef3-535a7fabab80.png)
Also going to add this screenshot of Atom Startup with only a theme and systax theme enabled.

**Comment by rmasp98** [comment]
@ryanvade have you tried @ssfrr's [workaround](https://github.com/atom/atom/issues/15323#issuecomment-427018396)? Seems like this may be caused by a fundamental issue in chromium with vsync on intel graphics. [Here](https://bugs.chromium.org/p/chromium/issues/detail?id=606152) is a link to the original issue. It fixed my issues with other electron apps but not done too much testing on atom yet

**Comment by guillochon** [comment]
@ssfrr's solution worked perfectly for me! Ubuntu 14.04.5, Atom 1.31.2.

**Comment by ryanvade** [comment]
@rmasp98 I tried the workaround suggested by @ssfrr , the flashing has been reduced slightly but is not eliminated. But it is at least usable now (the white screen on startup hasn't changed but that disappears quickly).

**Comment by Asday** [comment]
Any news on this, or is it systemic?

**Comment by joveice** [comment]
```
Atom: 1.34.0
Electron: 2.0.16
Chrome: 61.0.3163.100
Node: 8.9.3
```
Fedora 29

Quite often.

**Comment by adavie1** [comment]
For me, this issue is resolved.
Ubuntu 18.04
Atom 1.34.0

**Comment by gilbertohasnofb** [comment]
@gusbemacbe I think there are many people still experiencing this issue, myself included, and the fixes and workarounds proposed here did not work on my side. I think this issue should be left opened, particularly given the number of affected people.

**Comment by joveice** [comment]
I were just about to comment what the fix was since it got closed. I still experience the issue and the fix only works sometimes for me. (not most times, so quite annoying)

**Comment by Asday** [comment]
@gusbemacbe Come on dude, one guy says he doesn't have the problem any more on a _124 comment issue_, and you close it?

Still happening for me.  Please reopen the issue.

**Comment by gilbertohasnofb** [comment]
I have tried @ssfrr's [suggestion](https://github.com/atom/atom/issues/15323#issuecomment-427018396) once again, and this time it seems to have fixed the issue for me. That said, this solution is far from ideal as 1) it did not seem to work with my previous GPU and 2) Atom should be able to handle vsync IMO, like every other application.

**Comment by Asday** [comment]
I would like to reiterate, **this is still happening.**  Mint 18, Atom 1.35.1 x64.

Please reopen the issue.

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback.

As this is an underlying Electron issue and isn't something that is within our control, the Atom team isn't going to be working on this issue other than working to get Atom updated to a more current version of Electron. Since updating to a new version of Electron is being tracked [elsewhere](https://github.com/atom/atom/pull/18916), you may want to subscribe there for updates. Since this issue isn't something we're going to be working on individually, we're going to leave it closed.

Thanks again for all the help and information.

**Comment by Asday** [comment]
Has this already been fixed in a later version of Electron, or do we need to open an issue with them?

Or is there _already_ an issue open with them?

**Comment by geryit** [comment]
I was on Intel Gpu, switched to Nvidia Gpu on my dell xps 15, no flicker now

**Comment by danielsalles** [comment]
Before I used wayland on Linux, after returning to Xorg this problem solved. I think it's one of the causes of flicker.
As solved for me, I'm mutating the thread.

Good luck guys.

**Comment by Asday** [comment]
I'm on AMD Radeon and XOrg, so it looks like neither of them are a factor.

**Comment by Asday** [comment]
Is there a way to force the "Restart atom" popup to appear?  Or some command to restart atom?

My startup procedure is:

* Launch atom;
* Switch to the other color profile;
* Restart;
* Work.

It doesn't matter which profile I'm on, the important thing appears to be either the switching or the restarting, and I'd like to narrow it down.

**Comment by awilkins** [comment]
AFAIR ctrl-shift-F5 restarts Atom

**Comment by Asday** [comment]
Thanks @awilkins, that's exactly what I was looking for.  Doesn't solve the flickering issue, meaining it is something to do with the colour profile switch.

**Comment by Asday** [comment]
It seems to be fixed in 1.39.1 x64.  I'll update if that's not correct.
