### ISSUE TITLE
Path too long exception on Windows install Again:

### ISSUE THREAD

**Issue by scottie-uk** [atom/atom#15664]
I know the issue of problems with installation in windows 10 has been closed, but I've just downloaded the latest 64 bit installer for my Core I7 Windows Machine, and got the Path to long exception showing up in the logs. They are attached. I've run it as administrator and sill no joy. It worked on my office computer which is also a Windows 10 machine, but not my home machine.

<details>
2017-09-15 21:53:01> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2017-09-15 21:53:01> Program: Starting install, writing to C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\SquirrelTemp
2017-09-15 21:53:01> Program: About to install to: C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom
2017-09-15 21:53:01> Program: Install path C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom already exists, burning it to the ground
2017-09-15 21:53:02> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-09-15 21:53:02> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-09-15 21:53:02> CheckForUpdateImpl: Reading RELEASES file from C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\SquirrelTemp
2017-09-15 21:53:02> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-09-15 21:53:02> ApplyReleasesImpl: Writing files to app directory: C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom\app-1.20.0
2017-09-15 21:53:04> LogHost: Rigging execution stub for atom_ExecutionStub.exe to C:\Users\andrew.DESKTOP-T8M2OVN\AppData\Local\atom\atom.exe
2017-09-15 21:53:16> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
2017-09-15 21:53:16> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

</details>

**Comment by bartop** [comment]
@scottie-uk afaik it is purely Windows issue - i mean it is the OS limitation, not the application

**Comment by scottie-uk** [comment]
I can't agree with that. The file path length limitation has always been a limitation of windows, it did not arrive in Windows 10. If the project is building a dedicated Windows 64 bit installer and putting it on the home page then its a limitation with respect to Atom's system compatibility with the host OS. Squarely, the problem lies with Atom.

**Comment by 50Wliu** [comment]
@scottie-uk what happens if you try the Atom 1.21 beta installer?  Paths should be a lot shorter in that version.

**Comment by scottie-uk** [comment]
@50Wliu  Yes tried that, ran  the install as admin and still got the same issue of the paths being to long.

Do do understand that in the 21 century its getting hard for developers to put up with the file path limitations of windows. I really do with MS would do something main stream about it. I know they are  lazily experimenting with long file paths in Windows 10, but they still have not perfected it yet.

**Comment by danPadric** [comment]
[mood := friendly conversational]
@scottie-uk: 
Andrew that is a _bloody_ long user name `andrew.DESKTOP-T8M2OVN`. (I'd sure like to know why.) It simply not practical for the chaps to throw time at this issue that M$ caused, IMHO.

The only way past this would be to have a more flat directory tree structure. That is a more long term commitment to make.

What does an installation of Visual Studio Code do on your system?

Is it too much of a disadvantage to you to make a portable installation of Atom in the closer-to-root directory?

**Comment by 50Wliu** [comment]
Running the installer as admin does _nothing_.  If you look closely at the first line of the Squirrel log, the installer will automatically close itself and relaunch itself without admin permissions.

In the meantime, until we can get npm to give us a flatter directory structure, you should still be able to use Atom by downloading the portable version (`atom-windows.zip`/`atom-x64-windows.zip`) as @danPadric mentioned.

**Comment by scottie-uk** [comment]
@danPadric, the developers did not have to choose the usre's profile folder as the installation location. C: Program Files would be been far shorter and more uniform among the windows user base, it would have made their lives easier and ours.  

@50Wliu  Many thanks for the response. The portable version sounds interesting. How easy would it be to change the default installation directory of Atom? Furthermore, beyond adding a file chooser to the installation GUI how difficult would it be to let us choose?

**Comment by 50Wliu** [comment]
@scottie-uk We use the [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) framework, which has historically been against allowing the user to choose the installation directory (https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/goals.md#installing, https://github.com/Squirrel/Squirrel.Windows/issues/1002).

**Comment by scottie-uk** [comment]
That seems a peculiar ideology , but it is what it is I suppose.  It seems the way of the world now, give software users less and less choice. So I guess that means no fix for this issue will come any time soon.

**Comment by phillibert** [comment]
Having an officially endorsed Windows installer that is faulty on a substantial number of Windows machines and then linking to it on the homepage leads to a poor user experience. 

Blaming the user for having a long name when they try to report the issue isn't a great experience either.

As mentioned previously, you may want to consider promoting the portable solution instead.

**Comment by the-j0k3r** [comment]
See this https://github.com/Squirrel/Squirrel.Windows/issues/1024#issuecomment-338368400

This is a Squirrel issue which has apprently been fixed, this issue also affects (according  to @paulcbetts ) bug https://github.com/atom/atom/issues/15320

So it seems Atoms Squirrel framework needs to be updated to include that ASAR inclusion fix.

**Comment by paulcbetts** [comment]
@the-j0k3r Hi, this is an incorrect summary - *Atom* chooses whether ASAR is enabled or disabled, Squirrel knows nothing about ASAR, it just knows about writing files.

The good news is, Atom re-enabled ASAR, so these glitches _should_ be going away. If you see old versions of Atom hanging around in your app folder, you can manually delete them safely.

While Squirrel could be patched in order to clean up these super long paths, I'd rather actually _not_ patch this, because generating them in the first place is a Generally Bad Idea

**Comment by the-j0k3r** [comment]
@paulcbetts so this bug report is due to ASAR being disabled in Atom, which you explained already its been re-enabled and this issue then should be fixed.

I wrote a script for the task of deleting old stuff, I know that is reliable at least.

**Comment by jolsen71** [comment]
I'm still experiencing this issue with 1.25.0-beta2 on production release of Win 10.

I tried to use the zip extract.exe and run "update.exe --install" and setting squirrel_temp env var mentioned in #14264 but it doesn't seem to work this time.

**Comment by Jacq** [comment]
Yes, still the same problem here with v1.30.0-beta1 also on Win 10

**Comment by Naim28** [comment]
I would like to suggest you, try **LongPathTool** program to resolve this issue.
This tool is very helpful to resolve the issue.

**Comment by benignbala** [comment]
This is an issue with 1.29.0 on Windows Server 2016. And a few points to note (friendly discussion, of course)

1. Always expect the users to do the unexpected (like having long user names, profile paths)
2. Most people trying to use atom are (I believe) tech people. So, it is common to expect customisable install paths. If Squirrel doesn't support it, then it is not suitable to be used by Atom (of course, one of the bugs says it is possible, but one of the devs said it is squirrel's ideology not to allow users to customise the install path).
3. Finally, I hope/wish that atom joins Emacs and Vi as a top level customisable, developer friendly editor. And the first step towards that is customisable install paths. Possibly atom devs can learn a thing or two from Emacs/Vi devs. Thanks
