### ISSUE TITLE
Massive memory leak when opening projects with symlink loops

### ISSUE THREAD

**Issue by thetechnick** [atom/atom#15966]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi!
First of I know this sounds silly, but I experience this problem only when opening one of my projects, so bear with me.
When opening a ~checkout of my project (https://github.com/thetechnick/nginx-ingress)~ project folder in the size range of >150MB atoms memory consumption is rising constantly at about ~30 MiB per second until it reaches around 14GB and freezes my system.

First I suspected the golang plugin `go-plus` and `ide-go`, but now I have disabled all community packages and the `atom-fuzzyfinder` and the issue still occurs. (same for `--safe` and `--clear-window-state`

I have done a short CPU Profile in Chrome, but it shows nothing I can identify as a Problem:
[CPU-20171022T113255.zip](https://github.com/atom/atom/files/1404767/CPU-20171022T113255.zip)

### Steps to Reproduce

1. Open the project
2. Look at the `top`/`the gnome taks thingy` or whatever shows the amount of memory atom uses

**Actual behavior:** Atom allocates ~30 MiB of memory per second until it crashes the system

**Reproduces how often:** 15~20 times before opening this issue

### Versions

OS: Fedora 26

`atom --version`
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

`apm --version`
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.6

### Additional Information
- all community packages are disabled
- can reproduce this issue when opening the content of this ZIP in atom:
https://drive.google.com/file/d/0ByW_Oz6LLJGWVVAwbUdoS3pwS00/view?usp=sharing

**Comment by 50Wliu** [comment]
Does anything happen if you disable the `github` package?  It's interesting that clear-window-state didn't fix it, which means Atom is reacting badly to something in the repo itself rather than having some incorrect state stored.

**Comment by thetechnick** [comment]
@50Wliu Hi, great response time!
I disabled the `github` package, but its still the same (killed atom at 1GB)

**Comment by thetechnick** [comment]
Strange, I just cloned a fresh copy of the repo to `/tmp/repo` and now memory is back to normal...
@50Wliu Can I upload something to make debugging this easier?

**Comment by 50Wliu** [comment]
I don't know much about debugging, but it seems like "Record Allocation Timeline/Profile" are listed as helpful in solving memory leaks?

**Comment by thetechnick** [comment]
I did some more testing, the issue only occurs after installing the project dependencies into the `/vendor` folder. When deleting the folder atom stays at normal memory usage.

An example is uploaded here, so it is simpler to reproduce: 
https://drive.google.com/file/d/0ByW_Oz6LLJGWVVAwbUdoS3pwS00/view?usp=sharing

When opening this folder in atom 1.21.1, it will not stop allocating memory until the system limit is reached.
I still run atom with the plugins listed above. `--safe` and `--clear-window-state` make no difference.

**Comment by daveshah1** [comment]
I am also experiencing this issue in 64-bit Arch Linux. In my case the leak is even faster, about 100MiB/second, and again it is causing a total system crash when it reaches the limit.

Downgrading from 1.21.1 to 1.20.1 fixes the issue.

**Comment by joerg-krause** [comment]
Same here on 64-bit Arch Linux with version 1.21.1.

**Comment by 50Wliu** [comment]
@daveshah1 @joerg-krause are you two using the same project that @thetechnick is?  If not, are there any similarities?

**Comment by joerg-krause** [comment]
@50Wliu No, I am not using the same project. I am using a quite large project with several of thousands files. Furthermore, it is a git project.

**Comment by maxbrunsfeld** [comment]
@thetechnick I can't reproduce this (just cloned your project, opened it in Atom and opened a couple of files). Are there some other steps you can provide? Do I need to install dependencies or something?

**Comment by thetechnick** [comment]
Hi!
I have attached a zip in my previous comment. The memory bug only occures
afer installing the dependencies or on other very large projects I can not
share.

I will update the issue title and description when i am back at work.
When I opened this issue I could only reproduce this on my project.

Max Brunsfeld <notifications@github.com> schrieb am Mo., 23. Okt. 2017,
21:41:

**Comment by dbstraffin** [comment]
I'm having the same issue with Atom 1.21.1, but not 1.21.0.  It consumes ~200% cpu and memory until the system locks up and the OOM killer kicks in.  It still happens when running `atom --safe`.  All my loaded projects are proprietary, so I doubt it's a specific project.

### Versions

OS: Ubuntu 17.04/17.10 (occurred before and after upgrade)

atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.1

**Comment by dbstraffin** [comment]
The issue stops when i change the filesystem watcher from native to emulated.  It starts back up when i switch back to native.

**Comment by thetechnick** [comment]
@dbstraffin thanks for the hint
I can confirm that the issue does only occur with the native file system watcher.

**Comment by smashwilson** [comment]
Yes, that's quite likely. On Linux, the [filesystem watching library](https://github.com/Axosoft/nsfw) needs to maintain an in-memory tree of inotify handles that mirrors the project directory structure. I'm a little surprised that you ran out of RAM before hitting the watch descriptor limit, though!

@dbstraffin: would you mind trying out [the new library we're working on](https://github.com/atom/watcher) on your project root? If you have a recent-ish Node.js install, you can run a [little CLI utility](https://github.com/smashwilson/watcher-stress) that uses it with:

```
npx @smashwilson/watcher-stress --cli /path/to/project
```

If not, no worries, I can try it out the next time I'm on my Linux box.

**Comment by dbstraffin** [comment]
@smashwilson I think i had increased `fs.inotify.max_user_watches` to `SOME_LARGE_VALUE` when my Nextcloud client ran into issues syncing some folders.

I ran the above cli utiliy, but did not experience the run away ram usage.

@thetechnick does your project have any symlinks? My was caused by a subproject that was symlinked in to the current project.  I thought it might be due to a symlink loop, but haven't been able to reproduce it with another project so far.  

Symlink loop or not, It seems to me that the file watcher should have ignored the subproject.  I had it listed in `.gitignore` and `Exclude VCS Ignored Paths` is checked.  I also tried adding it to `Ignored Names` and unchecked `Follow Symlinks`.

**Comment by dbstraffin** [comment]
Oh the script just finished:
```
>> RESOURCE USAGE <<
uptime 10.46 minutes (627.566s)
CPU usage: 351566 user 989021 system
RAM usage: rss 172.77 M (172769280b) total heap 11.38 M (11378688b) used heap 7.67 M (7672072b) external 192.67 k (192669b)
```

**Comment by thetechnick** [comment]
@dbstraffin I do not use symlinks in my project, but coreos/etcd in my vendor directory does
And it looks an awful lot like a loop to me...

```
# find . -type l -ls
  3808270      0 lrwxrwxrwx   1  nschieder nschieder        7 Sep 16 22:59 ./vendor/github.com/coreos/etcd/Documentation/README.md -> docs.md
  3808016      0 lrwxrwxrwx   1  nschieder nschieder        8 Sep 16 22:59 ./vendor/github.com/coreos/etcd/cmd/tools -> ../tools
  3808017      0 lrwxrwxrwx   1  nschieder nschieder       10 Sep 16 22:59 ./vendor/github.com/coreos/etcd/cmd/etcdctl -> ../etcdctl
  3808018      0 lrwxrwxrwx   1  nschieder nschieder        3 Sep 16 22:59 ./vendor/github.com/coreos/etcd/cmd/etcd -> ../
  3807970      0 lrwxrwxrwx   1  nschieder nschieder       12 Sep 16 22:59 ./vendor/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd -> ../../../../
```

**Comment by daveshah1** [comment]
Yes, I had a symlink loop in the project causing the memory leak too.

**Comment by smashwilson** [comment]
Ah, I see. Okay, I'll have to be certain I'm handling this in atom/watcher.

**Comment by Goldfinch** [comment]
I'm having the same issue 1.21.1, was on El Capitan about a weak ago when this issue has appeared. As other, I tried safe mode, disabled all packages, no changes. Just recently have updated os up to Siera 10.12.6, reinstall atom. CPU 80-100%.

I suspect this issue has appeared since the last release, 1.21.1. In my case, no matter how big is a project you working on, it freezes the system every minute, you just can't work. I've been forced to switch to Sublime, hope it's temporary.

**Comment by joerg-krause** [comment]
I can confirm that my projects has several symbolic link endless loops.

**Comment by smashwilson** [comment]
@Goldfinch do your projects also contain symlink loops? Does changing the watcher backend to "emulated" in your settings-view prevent the problem?

![image](https://user-images.githubusercontent.com/17565/32056956-f4de7710-ba33-11e7-81aa-cbab01f1156c.png)

**Comment by nathansobo** [comment]
Okay, so I think I have some fairly conclusive evidence that the file system watching library we introduced in 1.21 does not handle symlink loops well on Linux. This will be my top priority until we find a fix, but until then, the fix for people with these kinds of symlink loops is to change to the file system watcher to "emulated" in preferences.

We're working on a brand new [file system watching library](https://github.com/atom/watcher) that we plan to heavily load and fuzz test, but I understand that in the meantime this is a real pain. I'm sorry to everyone this has inconvenienced.

**Comment by stefanb2** [comment]
Same issue here: 1.21.0 works fine, 1.22.1 & 1.22.0-beta1: busy looping. Switching the watcher to emulation and restarting atom fixes the issue.

In my case the problem was triggered by [buildroot](https://buildroot.org/). In my build it creates ~10 file system loops, according to the warnings I get when I execute `find -type l | xargs -I {} find -L {} -type d | wc -l`

**Comment by Goldfinch** [comment]
@smashwilson no, I switched to Emulated but the leak is still the same, even when I run atom in the safe mode, 80-100%.
Now when I change the watcher back to Native, CPU goes up even more 130-150%, it crashes the system in the next couple of seconds after I open atom.

**Comment by nathansobo** [comment]
@Goldfinch there's another issue I found with the fuzzy-finder where we still get into loops if you have a symlink to a parent folder *above* the project folder.

**Comment by nathansobo** [comment]
The issue with our path watching library should be fixed in 1.21.2, which will be released early next week. There's still another issue, https://github.com/atom/fuzzy-finder/issues/329, I found with the fuzzy-finder that could still create problems with symbolic links that link to ancestors of the project folder. That's also on my radar but probably won't go out with 1.21.2.

**Comment by stefanb2** [comment]
1.21.2 does not solve the issue for me, i.e. if I switch the watcher back to native API atom starts to hog the CPU after restart.

**Comment by nathansobo** [comment]
@stefanb2

**Comment by nathansobo** [comment]
@stefanb2 That is disconcerting. Can you distill a simple example of the symlink structure that is causing your problem. @ungb @Ben3eeE Could you help trying to reproduce this issue on Linux?

**Comment by Ben3eeE** [comment]
@nathansobo We have some information from @stefanb2 through the duplicate issue already /cc: https://github.com/atom/atom/issues/16011#issuecomment-339886618

**Comment by nathansobo** [comment]
@Ben3eeE Thanks for that information. So @stefanb2 is the problem only happening when recursive links are created while Atom is already running? Perhaps my fix missed the case where new links are introduced, though I'm not sure how yet.

**Comment by stefanb2** [comment]
No, the file system structure already exists when I start atom.

Maybe this will help you to reproduce the issue:

- close all files in atom
- remove all project folders from atom
- switch watcher back to native API
- close atom

```
$ find -L -type l 2>&1 >/dev/null | perl -ne 'print "$1\n" if m,detected;\s+[^.]+([\w/.-]+),' | xargs ls -l
lrwxrwxrwx. 1 stefanb stefanb 1 Oct 30 09:17 ./output/build/attr-2.4.47/include/attr -> .
lrwxrwxrwx. 1 stefanb stefanb 1 Oct 30 10:45 ./output/build/host-acl-2.2.52/include/acl -> .
lrwxrwxrwx. 1 stefanb stefanb 1 Oct 30 10:45 ./output/build/host-acl-2.2.52/include/sys -> .
lrwxrwxrwx. 1 stefanb stefanb 1 Oct 30 10:44 ./output/build/host-attr-2.4.47/include/attr -> .
lrwxrwxrwx. 1 stefanb stefanb 1 Oct 30 09:00 ./output/host/usr -> .

# script to simulate "buildroot" type of project directory
$ cat create-file-system-loops.sh 
#!/bin/bash
set -x
for _l in \
        build/attr-2.4.47/include/attr \
        build/host-acl-2.2.52/include/acl \
        build/host-acl-2.2.52/include/sys \
        build/host-attr-2.4.47/include/attr \
        host/usr \
; do
        mkdir -p $(dirname ${_l})
        ln -s . ${_l}
done
```

1. `atom --safe --clear-window-state`: everything is fine
2. add existing buildroot directory as project folder: CPU jumps to 100%
3. remove buildroot project folder: CPU stays at 100%
4. close atom
5. `atom --safe --clear-window-state`: everything is fine
5. run `create-file-system-loops.sh` in an empty directory
6. add that directory as project folder in atom: CPU jumps to 100%

It may be that it is possible to recreate the issue with only one link loop, as all of them look the same i.e. `xyz -> .`

**Comment by stefanb2** [comment]
I simplified the reproducer to two symbolic links:

```
$ ln -s . abc
$ ln -s . def
$ ls -l
lrwxrwxrwx. 1 stefanb stefanb   1 Nov  1 22:02 abc -> .
lrwxrwxrwx. 1 stefanb stefanb   1 Nov  1 22:02 def -> .
```

When I add that directory as project folder to atom, the CPU usage jumps to 100%. Actually Atom UI freezes and doesn't even show the project folder in the pane. After restarting Atom the folder shows up in the project pane.

**Comment by nathansobo** [comment]
@stefanb2 I'm having a hard time reproducing the issue. I recorded a screen capture of me following what I think are your described reproduction steps. Is there something I'm missing?

![cant-reproduce-cpu-bug-linux](https://user-images.githubusercontent.com/1789/32296315-833fb794-bf11-11e7-8bf1-3e130cc7d256.gif)

**Comment by nathansobo** [comment]
Apparently @Ben3eeE can reproduce the issue so I'll work with him to straighten myself out.

**Comment by nathansobo** [comment]
Okay, I'm reproducing it now. Not sure hat was going on before.

**Comment by stefanb2** [comment]
@nathansobo you need to create the symbolic links *before* starting atom. But I guess you already figured that out by yourself :-)

**Comment by nathansobo** [comment]
@stefanb2 Ugh. I made a stupid mistake that caused us not to require the fixed version of our path watching library. Extremely sorry for the noise everyone. I tested the library itself on the VM but not the final packaged version of Atom. This will have to go out as another fix. I'll be sure to test the full bundle this time and also ask @Ben3eeE verify it as well.

**Comment by Ben3eeE** [comment]
:sparkles:

**Comment by stefanb2** [comment]
I can no longer reproduce the issue with 1.22.0. Thanks.
