### ISSUE TITLE
package installation fails on Celeron N3350 with SSL error

### ISSUE THREAD

**Issue by escapedsalmon** [atom/atom#16640]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I downloaded and installed Atom on a new notebook. So it's pretty much a clean install, both win10 and Atom itself. And I also tried safe mode, problem still persists:
I cannot download/install any package using the package installer of atom. It always throws the following error message
```
    Fetching featured packages failed.Hide output…
    write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
    101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
```

Doesn't matter if I try installing teletype like from the Welcome-tab or just querry for any other package that might be available.
I am asuming it is related to an openssl error in connection with node.js and the Intel Celeron N3350 CPU (https://github.com/nodejs/node/issues/12691 ).
(at least it it's not network related. I tried 4 different networks, doesn't work (but works on other machines on these networks. It's not a kind of proxy issue.)

### Steps to Reproduce

1. Clean install Atom from atom.io
2. navigate to the package installer and lookup any package

**Expected behavior:** 
showing the package I looked up (e.g. teletype)

**Actual behavior:** the error message seen above

**Reproduces how often:** 100% 

### Versions
npm  3.10.10
node 6.9.5 x64
atom 1.23.3

Windows 10, current 1709, 64bit.

### Additional Information
Already mentioned, I assume this issue being OpenSSL/CPU releated.
https://github.com/nodejs/node/issues/12691

**Comment by 50Wliu** [comment]
It looks like this fix is on Node 8+, which means this should be fixed when we upgrade to Electron 1.8.0+.

**Comment by tzak902** [comment]
I'm having same issue.
Latest version doesn't fix it yet.

`Installing “atom-beautify@0.32.4” failed.Hide output…
Request for package information failed: write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
 (EPROTO)
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.`

apm  install --check:

`Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
gyp ERR! stack 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
gyp ERR! stack
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at WriteWrap.afterWrite (net.js:801:14)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Zakaria\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Zakaria\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\Zakaria\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
`

apm --version

`apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python
git
visual studio`

any idea guys

**Comment by damieng** [comment]
@tzak902 The fix is in **1.28 beta** - you are running **1.27 stable**  You'll need to download the beta version for now.

**Comment by damieng** [comment]
@lee-dohm Do you have any idea why Atom 1.28 is shipping with node 6.9.5 still given it's now on Electron 2.0?  It's supposed to be Node 8 for that version of Electron....

**Comment by Arcanemagus** [comment]
@damieng See https://github.com/atom/apm/pull/752, Atom's version of Node.js is now v8.9.3, but `apm` is still on v6.9.5.

(Note that that PR was based on Electron v1.7.11, it should be updated to match Electron v2.0.1 now.)

**Comment by tzak902** [comment]
@damieng  I'm still facing same issue even after installing 1.28 beta, here is my  apm --version output:


C:\Users\Zakaria>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0-beta1
python
git
visual studio


Please check the screenshot
<img width="952" alt="capture" src="https://user-images.githubusercontent.com/39320435/40322652-945ec380-5d22-11e8-969a-07992df4220f.PNG">

**Comment by tzak902** [comment]
I installed the 32 bit version and it works fine, is there any limitations by using the 32bit in terms of functionalities and features?

**Comment by damieng** [comment]
@tzak902 Theoretically it can access less memory (2GB) but I doubt you'll see any performance/memory differences in regular day-to-day use.

**Comment by tzak902** [comment]
Thank you very much Mr @damieng
