### ISSUE TITLE
Atom freezing when editing ERB files with tree-sitter

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#18342]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

https://github.com/atom/atom/issues/18327#issuecomment-433267915 wrote:

> I've experienced issues with syntax highlighting in ERB files since updating to 1.32.0. I don't think I can reproduce intentionally, but it did occur to me several times today where syntax highlighting will break during edits and eventually Atom will freeze with high CPU usage for about 10 seconds at a time. It doesn't seem to resolve itself unless I close the file and reopen it.

### Steps to Reproduce

* Open [this ERB file](https://gist.github.com/Ben3eeE/d5c285849a7b86d51cbb8b6ddd266f43)
* Select all
* Cut
* Repeat:
  * Paste
  * Undo

**Expected behavior:** Not freezing/incorrect highlighting 

**Actual behavior:** Atom freezing/incorrect highlighting

**Reproduces how often:** Unknown

### Versions

1.32.0

### Additional Information

/cc: @pjrebsch

**Comment by Ben3eeE** [comment]
@maxbrunsfeld Can you provide some details about how you reproduced this issue to see if we can get some reliable repro steps? 🙇

**Comment by pjrebsch** [comment]
Since adding `useTreeSitterParsers: false`, it hasn't happened to me again. I'll re-enable the feature to see how it might be reproducible.

**Comment by turgs** [comment]
I have the same problem. I'm using Ubuntu 18.10. Atom freezes then crashes. As it freezes, I always have an ERB file open and I can see the syntax highlighting is messed up similar to #18327. I'm going to try set `useTreeSitterParsers: false` in the interim.

**Comment by pjrebsch** [comment]
@Ben3eeE I've been using Atom in safe mode, but haven't got to editing ERB files until now. Pretty much the first file that I started editing triggered the issue. I was copying and pasting about 80 lines of code into the file and the syntax highlighting immediately broke and Atom froze soon after. It did resolve itself about a minute later, probably because I stopped trying to make edits this time. So we can check off the item about reproducing in safe mode.

<img width="861" alt="screen shot 2018-10-30 at 8 44 40 pm" src="https://user-images.githubusercontent.com/3499763/47759257-2091fe80-dc85-11e8-9fbc-cb2dbb5f461f.png">

**Comment by maxbrunsfeld** [comment]
@pjrebsch Thanks for the update. This is a high priority for me but I was not able to reproduce and fix it by tonight's patch release. I hope to get this fixed ASAP and release another hotfix, Atom 1.32.2.

**Comment by danPadric** [comment]
> 
> 
>At the moment I can't get Atom to re-open because it's now trying to open the same windows and crashes again before I can move the cursor or click anything.
@turgs - Hi Tim. Are you still having problems to open Atom? Try opening Atom from the terminal using the command: `atom --clear-window-state`

Does it help you?

**Comment by maxbrunsfeld** [comment]
Ok, I think I've identified the cause of this. I should be able to fix it early next week and then publish another patch release.

**Comment by maxbrunsfeld** [comment]
Ok, I think this is fixed, but I'm not going to close it yet. @Ben3eeE can you test this again on master when you get in tomorrow?

I believe the issue was caused by a bug in Tree-sitter itself, which prevented tree rebalancing from working properly in the case of ERB/EJS files. This was exacerbated by some inefficient code in `SyntaxNode.children` method in `node-tree-sitter`. I've fixed both issues.

* https://github.com/tree-sitter/node-tree-sitter/commit/4a2f804e9943b916e6ea6e09b295404b5b52b5fa
* https://github.com/tree-sitter/tree-sitter/commit/5dbd15f5f2e66e586a20949d7fbeeb934dcdeee2

**Comment by Ben3eeE** [comment]
@maxbrunsfeld I can no longer reproduce the freezing that I saw earlier when running on https://github.com/atom/atom/commit/116fd668bdf136dd8c188970b200ff5c4ed96aad

I do still see broken highlighting when pasting ERB rapidly. When pasting about 70 lines of ERB I see syntax highlighting flash broken for a short while and then repair itself. If I hold down `ctrl-v` it breaks after just a couple of hundred lines pasted.

**Comment by maxbrunsfeld** [comment]
Reopening because the fix above doesn't seem to fully address the problem.

**Comment by maxbrunsfeld** [comment]
@turgs @pjrebsch Sorry for how long this took to fix. We're publishing a new patch release today that contains the fixes.

**Comment by dcjones1** [comment]
I'm running Atom 1.34.0, yet I'm still getting this issue. It's super easy to reproduce, literally any ERB file that work with, when I open an embedded Ruby section, <%=, the moment that I close it, %>, my syntax highlighting disappears. In order to get highlighting back to normal, I can delete the first character in my file and retype it, and highlighting is back to normal. 

This bug only affects the syntax highlighting after the embedded Ruby bit.

**Comment by SeaCDragon** [comment]
Just here to confirm that this is still a problem on Atom 1.39.0. Closing and reopening the file's tab fixes the highlighting, but nothing else. Basic HTML is unaffected, but any ERB except the `<%= %>` is shown as basic text
