### ISSUE TITLE
Some unicode characters seem to confuse Atom

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1849]
Halp ticket:
* support/e61e5074bc3011e396a434cf997499c3

> Support for Unicode is incomplete. Unicode characters are shown, but the cursor get stuck, and the navigation with the keyboard arrows stop working.

The user was using this string as an example `ג׳ג׳ג׳dwdwdww`

Here's a GIF of me pressing just the right arrow key to get from the beginning of the string to the end:

![test1006](https://cloud.githubusercontent.com/assets/38924/2644705/38820a02-bf2b-11e3-8c5c-917400a391d1.gif)

**Comment by facundofarias** [comment]
Do we have news on this regard? :(

**Comment by nathansobo** [comment]
We're working on a new document model which should set the stage for fixing this.

**Comment by jtauber** [comment]
I'm seeing a likely related issue with polytonic Greek. Here's a GIF:

![out](https://cloud.githubusercontent.com/assets/24426/6761095/df59dfca-cf25-11e4-82fd-31fffd75642f.gif)

**Comment by jtauber** [comment]
It's not easy to paste files that exhibit the bug here as a certain level of normalization is taking place in the copy-paste (and the bug likely relies on differences between decomposed characters and precomposed characters) but here's a hex dump of a file that shows the bug:

```
0000000 ce ac ce b4 ce b9 ce ba ce ad cf 89 2c 20 ce ac
0000010 ce b4 ce b9 ce ba ce ae cf 83 cf 89 2c 20 e1 bc
0000020 a0 ce b4 ce af ce ba ce b7 cf 83 ce b1 2c 20 e1
0000030 bc a0 ce b4 ce af ce ba ce b7 ce ba ce b1 2c 20
0000040 e1 bc a0 ce b4 ce af ce ba ce b7 ce bc ce b1 ce
0000050 b9 2c 20 e1 bc a0 ce b4 ce b9 ce ba ce ae ce b8
0000060 ce b7 ce bd 0a                                 
0000065
```

**Comment by jtauber** [comment]
Note that in my Greek example, I'm running 0.187.0 on OS X 10.10.2 with a default font of PT Mono which doesn't support polytonic Greek so is using a fall-through font.

**Comment by mhf-ir** [comment]
Middle east developer waiting for solve this issue :+1:  ... cheers guys

**Comment by thanhmssl10** [comment]
So long time with this error :(

**Comment by ebraminio** [comment]
Probably [this commit](https://github.com/marijnh/CodeMirror/commit/c9b03929a009952b1ba1a8463783b9057a72e1840) that brought RTL support to CodeMirror and [the not fixed bug on Ace](https://github.com/ajaxorg/ace/issues/1429) will help to get some context.

[Adobe Brackets](https://github.com/adobe/brackets) (CodeMirror based?) and [Visual Studio Code](https://code.visualstudio.com/) (Monaco) are also supporting RTL text well. I wish MS would donate Monaco to FOSS community someday. Perhaps Github guys would be able to accelerate MS on that.

**Comment by jtauber** [comment]
@nathansobo what's the best way to track progress on the new document model?

**Comment by jtauber** [comment]
This bug (at least my particular manifestation of the problem) seems to have improved slightly (but *not fully* been fixed) in 0.205.0.

**Comment by jtauber** [comment]
This is probably the best example I can come up with of the bug and it's effect:

1) the existence of the macron on the alphas makes every glyph on the line narrower (including all those earlier in the line)
2) the *cursor* placement ignores this narrowing and the cursor's x offset on the second line is where it would be on the first line

![screen shot 2015-06-06 at 2 16 12 am](https://cloud.githubusercontent.com/assets/24426/8020407/72580e3a-0c45-11e5-8ab9-96c171c5b159.png)

**Comment by ebraminio** [comment]
You probably hit complex/simple path difference: http://crbug.com/404597

**Comment by jtauber** [comment]
So it's upstream in Chromium? I hope it's fixed before Atom 1.0

**Comment by ebraminio** [comment]
Yes AFAIK but it won't fix RTL issues merged on this bug which needs local [care](https://github.com/atom/atom/issues/1849#issuecomment-102712443).

**Comment by jtauber** [comment]
@ebraminio I'm wondering if I should reopen #5975 then, if that can be fixed independent of this bug.

**Comment by ebraminio** [comment]
Testcase:
```
1234567890 | α
1234567890 | ά
1234567890 | ὰ
1234567890 | ᾶ
1234567890 | ἀ
1234567890 | ἄ
```
Current situation:
![image](https://cloud.githubusercontent.com/assets/833473/8021164/ea260660-0ca9-11e5-86f1-b4ee4ef492f0.png)
After merge of simple and complex:
![image](https://cloud.githubusercontent.com/assets/833473/8021174/1a7997aa-0caa-11e5-8c41-88e146004b20.png)
(the inconsistency is resolved)

How to trig complex path for all text (the thing will happend after merge of them)? By applying text-rendering: optimizeLegibility; somewhere on the editor like this:
![image](https://cloud.githubusercontent.com/assets/833473/8021186/63c367ba-0caa-11e5-8e6a-c7a166be008e.png) 

With this you can get the idea of what that change could mean, not sure if that would be all good :) But sure this is not just finalized version of complex that will happen to all text, there are issues that before merge of them should and will be fixed but that inconsistency should go.

**Comment by nathansobo** [comment]
There's a few issues in here. As for this one:

> ![](https://cloud.githubusercontent.com/assets/833473/8021174/1a7997aa-0caa-11e5-8c41-88e146004b20.png)

Once we change our approach to text measurement (per #6055, #6083), measure issues like the one above should no longer be a problem, regardless of how Chrome resizes the line.

I think I can do something to improve the soft-wrap situation this week. @izuzak do we have an issue open specifically related to unicode characters and soft wrap, or is this the catch-all?

**Comment by izuzak** [comment]
> I think I can do something to improve the soft-wrap situation this week. @izuzak do we have an issue open specifically related to unicode characters and soft wrap, or is this the catch-all?

@nathansobo Not sure which soft-wrap situation you're referring to :thought_balloon: -- didn't notice any mention of that in this issue. There's https://github.com/atom/atom/issues/1783 (soft-wrapping in CJK), https://github.com/atom/atom/issues/7050, and also https://github.com/atom/atom/issues/1894,  https://github.com/atom/atom/issues/3461, and https://github.com/atom/atom/issues/3437 related to soft wrap problems.

**Comment by ebraminio** [comment]
If you want improve things, I suggest applying `text-rendering: optimizeLegibility;` somewhere that both measurement and presentation layer would use, because that is what next versions of Chrome would work and better your work would be upon to that.
> @ebraminio I'm wondering if I should reopen #5975 then, if that can be fixed independent of this bug.
Better to unmerge #5975 and continue this discussion there, the solution for this particular issue (RTL text handling) is described [here](https://github.com/atom/atom/issues/1849#issuecomment-102712443).

**Comment by jtauber** [comment]
I've reopened #5975 as there seems agreement it's a separate issue.

**Comment by rabbani1** [comment]
how can I fix this problem?

**Comment by 50Wliu** [comment]
@izuzak @as-cii This is fixed now, right?

**Comment by as-cii** [comment]
Yup! Thanks.

**Comment by izuzak** [comment]
:zap: @as-cii.

This issue has comments which point to a few different problems. I _think_ this one still isn't resolved (and I think I remember we talked about this in chat briefly): https://github.com/atom/atom/issues/1849#issuecomment-50087298

Should we create a new issue for this so that we don't forget about this?

**Comment by as-cii** [comment]
Agreed to track RTL support in a separate issue, 'cause I applied some changes that made working with lines made up by only RTL characters usable. For example:

```
السلام عليكم السلام عليكم السلام عليكم السلام عليكم
```

Should work just fine. Due to some limitations of the `Range` API, Chrome starts to getting confused as soon as LTR and RTL are used in the same line.

Thanks for pointing that out, @izuzak. :heart:

**Comment by ebraminio** [comment]
Not sure if any other thing is left here (I don't have access to updated Atom editor) but you can consider integration some parts of https://github.com/Microsoft/vscode Monco editor now which works great on this area ([more details](https://github.com/atom/atom/issues/1849#issuecomment-102712443))

**Comment by ebraminio** [comment]
Also optimizeLegibility now is default Chrome 49 behavior so no more weird looking like https://github.com/atom/atom/issues/1849#issuecomment-109609228 difference on lines with different kind of characters.

**Comment by alilotfi** [comment]
Same for me 
atom 1.2.0

**Comment by n0o0bSina** [comment]
This seem not completely fix.
see:
![2016-04-07_02-16-59](https://cloud.githubusercontent.com/assets/15300551/14334070/29c49afe-fc67-11e5-9d85-afd3dba3c319.gif)
Atom 1.6.2

**Comment by ahmadalukah** [comment]
yeah the same problem here :cry: the pointer is never on the right place ..

**Comment by ebraminio** [comment]
Lets continue our RTL text bug dicussion here: #10132

**Comment by Javanmardi** [comment]
A simple flush left/right like Notepad++ would be satisfying.
Recently I installed force-text-direction, but it does not do anything.

**Comment by vhp1360** [comment]
Hello members,
I'll appreciate if any one give any update regarding this issue.

**Comment by jtauber** [comment]
@vhp1360 this issue has been closed for over a year. Any follow up should probably take place on open issues referenced.

**Comment by vhp1360** [comment]
@jtauber thanks for your replay,
I knew but it did not labelled  as "close" and some other issues referenced to this like[#2391](https://github.com/atom/atom/issues/2391), [#4007](https://github.com/atom/atom/issues/4007),[#7529](https://github.com/atom/atom/issues/7529),[#7897](https://github.com/atom/atom/issues/7897) and for example @izuzak  referenced other one to this and more important this issue is remaining yet.
then please labelled _close_ if it should be closed.
thanks.

**Comment by 50Wliu** [comment]
@vhp1360 This issue clearly has a red label next to it that says "Closed".
In addition, if you read through the entire issue you would have noticed that this issue was closed on October 8th, 2015.

New conversation should take place in #10132 (for now).

**Comment by iegik** [comment]
OS: Windows 10
`НОМЕНКЛАТУ́РА` in Notepad++ http://joxi.ru/52abw49CG5xX0A.png
