### ISSUE TITLE
Newly opened files should only open in an existing window if they're in the same directory as the other file opened there; otherwise should open a new window.

### ISSUE THREAD

**Issue by raystubbs** [atom/atom#18770]
It gets really annoying when I open a new file from another project/directory and it gets mixed in with the existing, but completely unrelated tabs.  It should open in a different window if it's from a different directory.

**Comment by 50Wliu** [comment]
Should be fixed by #18608 and be available starting with the next beta! @smashwilson please let me know if I'm wrong.

**Comment by smashwilson** [comment]
Yeah, with #18608, if you open a new file from the command-line:

* If you don't provide `--add`, Atom will _always_ open a new window containing only the named file;
* If you do provide `--add`, Atom will _always_ open the named file in an editor in an existing window with a project folder containing its path, or the most recently opened window if there are none.

If you see this not being the case after 1.36.0-beta0, please let us know 🤞

**Comment by raystubbs** [comment]
Mm, this seems reasonable when working at the command line.  But from a
graphical point of view it doesn't fix the issue.

When I double click a text file with Atom as my default editor the yes,
it'd be better to open in a new window then to get mixed up with a
different project.

But it'd be much better if Atom would detect if the file is part of one of
the projects (if it's in their directory tree) that are already open, and
if so then open it in the respective window.  Otherwise open it in a new
window.

It sounds like you already have the project/directory checking with the
'--add' option.  But it shouldn't just add it to the most recent window if
there's no related project; it should open a new one.  And this should be
the default behavior I think.

Just my opinion anyway.  I like Atom, but this annoys me to no end.
