### ISSUE TITLE
switching keyboard layout to Alt + Shift moves focus to main menu

### ISSUE THREAD

**Issue by inFlowia** [atom/atom#21825]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I switch the layout language from English to Russian or from Russian to English using Alt + Shift, the focus moves to the main menu. This appeared in version 1.51, which I had to upgrade to due to the upgrade to Ubuntu 20.04. Before that, I was working on version 1.26.1 and there was no such problem. The problem is very serious, because if you do not notice that you have jumped to the main menu and continue printing, you can simply destroy the document and the project, knock off the settings and much more that can be done through the main menu.

### Steps to Reproduce

1. Start typing in document
2. Press Alt+Shift (first hold Alt, then press Shift)

**Expected behavior:**

The keyboard layout should just switch to Russian and the typing cursor should remain in the typing field and not disappear, the focus should remain on the typing field

**Actual behavior:**

the focus moves to the main menu and typing stops

**Reproduces how often:**

This is reproduced almost always, but sometimes, with some "successful" switches, the focus does not jump. I did a lot of experiments and realized that the order of pressing the keys is to blame. If you first hold down Alt and then Shift, then the focus will jump, but if you do the opposite - first hold down Shift and then Alt, then the focus will remain in the text field, and the layout will switch. But this is not an option! I have been trying for 4 long months to retrain to switch to Shift + Alt and not to Alt + Shift - and to no avail. I work on many computers with different OS and editors, and the good old Shift + Alt works there, it dulls my guard and again returning to Ubuntu I forget.

### Versions
Problem on:
Atom-x64 1.53.0
Atom-x64 1.51.0
UbuntuStudio (Xubuntu) 20.04.1 With default anvironment and Cinnamon 4.4.8 the same

NO PROBLEMS ON: Xubuntu 19.10 + Atom-x64 1.26.1

### Additional Information

In keybindings resolver when i press Alt+Shift:
alt-groupnext

When press Shift+Alt:
groupnext-alt

**Comment by wlwl2** [comment]
Can I clarify something? What happens when you press the alt key by itself? Is it changing the focus to File, Edit, View, ... etc.?

**Comment by inFlowia** [comment]
> What happens when you press the alt key by itself? Is it changing the focus to File, Edit, View, ... etc.?
Yes. If the cursor is in the text and I press Alt, then the focus changes to the main menu (File, Edit, etc.). If I press Alt again, the focus returns to the text.

**Comment by wlwl2** [comment]
> > What happens when you press the alt key by itself? Is it changing the focus to File, Edit, View, ... etc.?
> > Yes. If the cursor is in the text and I press Alt, then the focus changes to the main menu (File, Edit, etc.). If I press Alt again, the focus returns to the text.

It happens on Windows 10 as well. This was changed recently so I can no longer use alt key for my shortcuts. Not sure if it is a bug, or intended but I would like the option to go back.

**Comment by wlwl2** [comment]
Under Core Settings there is an option called "Auto Hide Menu Bar" (toggle the menu by pressing Alt, only on Windows and Linux). If you turn it off, pressing Alt alone should not focus on the menu I think, but this is not working?

**Comment by wlwl2** [comment]
@inFlowia I think pressing alt while on currently focused text editor window should do nothing (not toggle between menu and editor). Is that the solution to your problem as well?

**Comment by inFlowia** [comment]
> Under Core Settings there is an option called "Auto Hide Menu Bar" (toggle the menu by pressing Alt, only on Windows and Linux). If you turn it off, pressing Alt alone should not focus on the menu.

Unfortunately, this is not a solution to the problem. I had this checkbox turned off by default and I never turned it on. I switched it over - the problem did not disappear.

An interesting observation: I think the Alt button is not to blame for everything. This is why I think so: to test your advice, I had to launch Xubuntu 20 with LiveUSB and install Atom. And you know, the problem was not observed at first. I actually put the cursor in the textbox and pressed Alt and the cursor stayed in the text editor! The focus did not run away forever to the main menu. Rather, he moved there only while holding down the Alt button. As soon as I released it, he returned to the text editor. Moreover, I even pressed Alt + Shift - and everything was still fine. However, this happened until the Alt + Shift key combination was enabled in the operating system. As soon as I turned on the Alt + Shift key combination in the Xfce settings to switch the layout between RU / EN, the problem immediately appeared. As soon as I turned off the key combination, the problem disappeared.

**Comment by wlwl2** [comment]
1) @inFlowia Let's focus on getting it to the Xubuntu 19.10 + Atom-x64 1.26.1 state.

2) Regarding the first point- it was not a solution. That was just a note or reminder, something that also affects the Alt key in addition to everything else. So after we get the solution to the problems we have, we need to also deal with this Atom setting.

3) Thanks for the testing. I think that would mean that the 3 common states: KeyUp, KeyDown and KeyPress (holding) need to also be addressed/considered when using Alt. Maybe we can assist this from Atom's side regardless of the operating system or even Electron?

Relevant issues (you don't have to read these):

# https://github.com/electron/electron/issues/28088

# https://github.com/electron/electron/issues/474

# https://github.com/electron/electron/issues/17418

**Comment by maxsupermanhd** [comment]
Have same issue here, "Auto hide menu bar" not helping.
Ubuntu 20.04.2 LTS x86_64, Xfwm4, Xfce

**Comment by vetash** [comment]
This electron caused issude fixed in https://github.com/electron/electron/releases/tag/v13.1.0
https://github.com/electron/electron/pull/29445

**Comment by wlwl2** [comment]
1.58.0 alt key on Windows 10 is still not working like it did in the past (select all occurrences using alt-f3 removes focus so you can't do anything with the selection). Not sure if this is an OS specific problem.

**Comment by SPiRiT369** [comment]
Looks like it's fixed in Electron side (?) ...
But anyway, for users who still experience this annoying bug, there is a workaround.
You can hold the Shift key a bit longer and it will not trigger the menu.
Hope this is helpful for someone :-)

**Comment by inFlowia** [comment]
1.59.0 and 1.60.0-beta0 tested and bad news: nothing has been fixed. This bug still happens.

**Comment by inFlowia** [comment]
I have tested some latest versions (1.50.0, 1.47.0, 1.46.0, 1.45.0, 1.59.0) and 1.46.0 is the latest version where language switching works fine.
