### ISSUE TITLE
Chromium's font rendering color inaccurate

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#3015]
Font rendering in Chromium has a problem: the color is inaccurate. While it's not serious for a web browser, it's serious for a code editor. I was so frustrated when writing a syntax theme. Can GitHub do something to tweak Chromium's font color to what it should be?

To show everybody the problem, I made a comparison between 3 browsers. First, take a look at 13px font in Chrome (same effect as Atom). Left is black, right is rgb(0,128,0) green:
![chrome-008000-13](https://cloud.githubusercontent.com/assets/731796/3636927/84ec4c5e-0fe9-11e4-9030-3946b770c852.png)

It's a little darker. What's the correct color? Let's take a look at Firefox and Safari's:

Firefox:
![firefox-008000-13](https://cloud.githubusercontent.com/assets/731796/3636952/16ee5862-0feb-11e4-924a-531b0da204ab.png)

Safari:
![safari-008000-13](https://cloud.githubusercontent.com/assets/731796/3636953/21753de6-0feb-11e4-94e8-95ea1506f344.png)

Chromium has a -webkit-font-smoothing css property, set to "subpixel-antialiased" by default. If changed to "antialiased", it becomes too bright:
![chrome-008000-13-antialiased](https://cloud.githubusercontent.com/assets/731796/3636964/4ad44d5c-0fec-11e4-879b-04560558416e.png)

My conclusion is: whatever smoothing strategy I choose, it's inaccurate. Either too dark or too bright. It will become more serious if the font is even smaller.

Let's look at an extreme case (8px using default smoothing. not practical, just to show the problem):
![chrome-008000-8](https://cloud.githubusercontent.com/assets/731796/3637003/1c362b0c-0fef-11e4-8820-5680288feb41.png)
In Chrome it became completely black.

Firefox:
![firefox-008000-8](https://cloud.githubusercontent.com/assets/731796/3637018/de517a02-0fef-11e4-9a9d-42d65e6a1976.png)

Safari:
![safari-008000-8](https://cloud.githubusercontent.com/assets/731796/3637019/e6e1e012-0fef-11e4-8ea0-df4ac245ec95.png)

Before my test, I thought it's a Webkit problem, but now I tend to think it's a Chromium problem, because Safari is OK.

Update:
Seems it's caused by anti-aliasing. If you set `-webkit-font-smoothing` to `none`, then the color is correct, but the font looks ugly. Maybe Webkit has some internal parameters that control the anti-aliasing, but Chromium did not tune it to its best? That's why Safari's font color is OK? I don't know.

Update:
If React editor is enabled (default in v0.117), then it will be too bright rather than too dark.

**Comment by benogle** [comment]
This has been solved, right? cc @simurai @as-cii

**Comment by simurai** [comment]
I can still reproduce this:

![screen shot 2016-01-28 at 12 42 50 pm](https://cloud.githubusercontent.com/assets/378023/12634494/50e0357a-c5bd-11e5-8b98-17a075983298.png)

It looks like they use different subpixel-aliasing (orange on the left, blue on the right). Like the vertical line of `b` and `d` is blue in Atom, but green in Safari. And Atom uses a darker orange.

I don't think we can do much about it. And [that Chromium issue](https://code.google.com/p/chromium/issues/detail?id=396689) seems stale. Maybe just be aware when porting an existing theme to Atom to compare screenshots, and adjust if needed.

**Comment by as-cii** [comment]
> I don't think we can do much about it. And that Chromium issue seems stale. Maybe just be aware when porting an existing theme to Atom to compare screenshots, and adjust if needed.

I think they archived the issue because there was no activity after a year. Honestly I agree that there isn't much we can do about it: subpixel anti-aliasing is problematic in so many ways but we have to rely on Chromium for it to work, or simply disable it everywhere (which would cause other text display issues).

Still, I feel like we may close this as it's not really related to Atom but to Electron/Chromium. Thoughts? :thought_balloon:

**Comment by lee-dohm** [comment]
I agree with closing this as it isn't something we have control over ... or at least obtaining control would be far too costly at this stage. Since this bug boils down to "we don't render the same as native rendering", the only way to truly fix it (in all its variations) is to start using native rendering ... and I don't believe we are likely going to stop using Chromium for our rendering engine any time soon?
