### ISSUE TITLE
Atom Helper not responding

### ISSUE THREAD

**Issue by flynfish** [atom/atom#3928]
Looking at activity monitor, I always get a `Atom Helper (Not Responding)`, even if I start atom in safe mode. 

I'm on OSX mavericks and atom 0.138.0. I noticed this at least a few versions back too. 

![screen shot 2014-10-21 at 10 08 40 am](https://cloud.githubusercontent.com/assets/253936/4739097/05bb3504-5a02-11e4-9216-54f719241018.png)

**Comment by pastak** [comment]
I've updated Atom to Ver 0.169.0 but I have same proble.

It is on Mac OS X 10.9.4. 

Thanks.

**Comment by brandonweiss** [comment]
Yeah I still have the same problem. It isn't necessarily affecting performance anymore (previously it seemed to be), but it's still odd to seem them not responding properly.

**Comment by DinisCruz** [comment]
confirming that I also have it

![image](https://cloud.githubusercontent.com/assets/656739/5728579/417eed68-9b63-11e4-8a89-3e907e47cd7b.png)

**Comment by aom** [comment]
Same here. Updated to 0.171.0 today and I still see Atom Helpers in Not Responding state.

![screen shot 2015-01-14 at 10 32 01](https://cloud.githubusercontent.com/assets/2383/5736005/9cdbb2de-9bd8-11e4-8cce-817b7ca6dfe2.png)

**Comment by muhasturk** [comment]
In my opinion, sending your screenshots again and again does not help to resolve problem.

**Comment by matti** [comment]
@muhasturk In my opinion it helps to get attention to this issue that has been open for a long time. (not sending my screenshot of Atom Helper (Not Responding))

**Comment by pre** [comment]
I'm not sending my screenshot, but I just came here to bump this issue. This happens all the time.

**Comment by marcguyer** [comment]
:+1: OSX 10.9.5 Atom v0.172.0

**Comment by mogarick** [comment]
Atom v0.172.0 @ OSX 10.9.5 still showing the same issue "Atom Helper (Not Responding)"

**Comment by paulcbetts** [comment]
If you have the same environment as any of the previous posters, please don't add an additional "Me Too" - this bug is almost certainly _not_ sensitive to your particular config.

**Comment by pre** [comment]
Yes, a simple "+1" is enough to bump this issue.

**Comment by matti** [comment]
Totally agreed, a simple "+1" would be enough to make this long standing and ignored issue to be hopefully fixed.

**Comment by 50Wliu** [comment]
It hasn't been ignored.  Atom can't really do anything about it since it seems like it's still a Chromium bug.

**Comment by hax** [comment]
+1

**Comment by lstroud** [comment]
+1

**Comment by paulcbetts** [comment]
Please stop "+1"ing. Seriously. Everyone knows. Got it. The text is red and you don't like it, even though it doesn't affect the app in any real way whatsoever. Enhance Your Calm.

**Comment by le717** [comment]
If it is any consolation to anyone, Brackets has this same issue on Mac.

adobe/brackets#5794

**Comment by rpechayr** [comment]
:+1: , please let us know what are the plans for this issue. Os 10.10.2, and Atom 0.179

**Comment by maknoll** [comment]
seems to be resolved in 0.180

**Comment by brandonweiss** [comment]
I don't think so. I'm on 0.182 and still seeing it.

**Comment by pives** [comment]
+1

**Comment by thedaniel** [comment]
> what are the plans for this issue

This issue is that the process appears to be not responding in activity monitor, but performance & responsiveness is not actually affected. Furthermore it appears to be a Chromium bug, so the plans are to do nothing until it's fixed upstream. I'm with @paulcbetts, a little frustrated at all the +1 comments because they don't add anything to the issue other than spamming everyone that's subscribed to it already.

**Comment by ijuma** [comment]
An interesting question is why does Chrome not show the problem anymore while Atom still does? (that's the case for me, at least).

**Comment by batjko** [comment]
@ijuma If that's the case there's hope that it will just take a Chromium update to atom-shell sometime soon.

**Comment by rpechayr** [comment]
I'd be happy to +1 the chromium issue if I'd be pointed to it.

**Comment by ijuma** [comment]
@batjko Unlikely, this has been fixed since Chrome 39 and atom-shell has been using Chrome 40 for a while. @rpechayr, the Chromium issue is https://code.google.com/p/chromium/issues/detail?id=397642 (it was mentioned in this same thread).

**Comment by pre** [comment]
To the people who want to +1 this problem:

Please [bump the Chromium issue](https://code.google.com/p/chromium/issues/detail?id=397642), the last comment there is "I'm going to call this Fixed now" from November 2014. So if I understood correctly, Chromium project considers this fixed and Atom considers this a Chromium bug.

**Comment by rpechayr** [comment]
@ijuma @pre thank you. I've starred the issue on chromium.

**Comment by bassu** [comment]
This issue seems to be in a deadlock. Atom thinks it's a Chrome issue while Chrome claims to have fixed it. While people on Mac can still reproduce it on both :snail: 

:thought_balloon: 
I am beginning to think that the whole idea of using of HTML and CSS for rendering a text editor might have been flawed and not carefully fawned upon!

**Comment by mark-hahn** [comment]
> to think that the whole idea of using of HTML and CSS for rendering a
text editor might have been flawed

I don't see how a bug in an implementation could reflect badly on an
overall architecture choice.  If that were true then the iPhone was a
flawed idea.

**Comment by bassu** [comment]
> I don't see how a bug in an implementation could reflect badly on an overall architecture choice
I was referring to generic overall sluggishness and aggressive resource consumption!

**Comment by mark-hahn** [comment]
> I was referring to generic overall sluggishness and aggressive resource
consumption!

This is what you pay for the wonderful hackability and personalization. No
other architecture could come close.  I am approaching my dream editor.

Incremental improvements over time in Atom and Chromium will solve your
problem with sluggishness (I have no problem except start-up time which is
fixed by leaving it running).  And hardware has a way of catching up with
software.

**Comment by thedaniel** [comment]
This isn't really the place to yet again discuss whether web technology is the right thing to use to build an editor. Let's just discuss the "Atom Helper not responding" issue here.

In any case, this appears to be about how it's shown in Activity Monitor and not an actual lockup. That's not to say it's not a bug but it's a less critical one since it doesn't appear to be affecting how the editor runs.

**Comment by bassu** [comment]
> And hardware has a way of catching up with software.

I think you are expecting Moore's Law to give leverage and fix problems caused by the software. It's already slowed down recently.



> Let's just discuss the "Atom Helper not responding" issue here.
> In any case, this appears to be about how it's shown in Activity Monitor and not an actual lockup

Ok, I'll stop discussing the Atomic lag now. But I disagree that "Not responding" doesn't have an impact on the process. The CPU usage shoots up as soon as the process becomes unresponsive.

**Comment by paulcbetts** [comment]
@thedaniel Can you lock this thread please? We probably understand everything we need to know about this bug atm.

**Comment by thomasjo** [comment]
@paulcbetts :see_no_evil:

**Comment by 50Wliu** [comment]
This issue appears to have been fixed now that Atom is on Chrome v56.  If you are still experiencing a **visual** issue where the Atom Helper process shows as "Not Responding" but is in fact responsive, please create a new issue and completely fill out the issue template.  Thanks!
