### ISSUE TITLE
npm error code 128 installing packages

### ISSUE THREAD

**Issue by b0nk** [atom/atom#3957]
This happens on every package I try to install
```
C:\Users\utilizador>apm install minimap
Installing minimap to C:\Users\utilizador\.atom\packages failed

npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/delegato
npm http GET https://registry.npmjs.org/temp/0.5.0
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/temp/0.5.0
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/delegato
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/Benvie/harmony-collections.git)
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm ERR! git clone https://github.com/Benvie/harmony-collections.git Cloning int
o bare repository 'C:\Users\utilizador\.atom\.node-gyp\.atom\.apm\_git-remotes\h
ttps-github-com-Benvie-harmony-collections-git-df214100'...
npm ERR! git clone https://github.com/Benvie/harmony-collections.git fatal: Unab
le to find remote helper for 'https'
npm http 304 https://registry.npmjs.org/property-accessors
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\utilizado
r\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collec
tions-git-df214100'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\ProgramData\\chocolatey\\lib\\Atom.0.139.0\\tools\\Atom\\r
esources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "C:\\Pr
ogramData\\chocolatey\\lib\\Atom.0.139.0\\tools\\Atom\\resources\\app\\apm\\node
_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalcon
fig" "C:\\ProgramData\\chocolatey\\lib\\Atom.0.139.0\\tools\\Atom\\resources\\ap
p\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\u
tilizador\\.atom\\.apmrc" "install" "C:\\Users\\utilizador\\.atom\\.node-gyp\\.a
tom\\.apm\\minimap\\3.3.4\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\UTILIZ~1\AppData\Local\Temp\apm-install-dir-114925-5376-38
44vb
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm
```
Fresh install of 0.139.0
Themes install just fine

**Comment by JaKXz** [comment]
I'm having the same issue currently on Atom v0.166 on Windows 8.1. Out of curiousity, is it possible to specify explicit paths to the `git` and `node` executables in Atom's config? Both are on my `PATH` but Atom seems to be using it's own executables. I've also tried setting the environment variables as mentioned above but with no luck.

**Comment by lee-dohm** [comment]
Atom uses its own version of `node` and `npm`, yes. It does not come with its own version of `git` though.

**Comment by JaKXz** [comment]
@lee-dohm thanks for the response. To be perfectly honest, I have no idea what the problem is and where to look to solve it, but it would be great to be able to install packages again.

**Comment by lee-dohm** [comment]
Sorry, unfortunately I'm not on Windows so I can't be much help for the deep-dive stuff. You might try searching on [Discuss, the official Atom message board](https://discuss.atom.io) for solutions that people have found there.

**Comment by kevinsawicki** [comment]
I believe this was an old npm bug that was fixed when we upgraded to npm 2.0+

**Comment by Jmales** [comment]
I'm having the same [problem](https://github.com/npm/npm/issues/15699) on Windows, using the latest npm. So no, the bug is not solved.

**Comment by lee-dohm** [comment]
@Jmales Please open a new issue so that we can do a new investigation. Since this has been closed without comment for over a year and a half, you likely have a completely different problem even if it has the same symptom.

**Comment by Jmales** [comment]
I already did man. There's a link in my previous answer. No one solved it yet
