### ISSUE TITLE
Atom editor does not go to foreground when opened from console

### ISSUE THREAD

**Issue by pascalchevrel** [atom/atom#4324]
OS: Ubuntu 14.10
Atom version 0.152.0

Steps to reproduce:
1/ have Atom already opened
2/ in a console, open a file with atom (ex: atom foobar.php)

expected result:
File is loaded and Atom window is moved to the foreground

actual result:
File is loaded in the background, Atom window does not move to the foreground.

**Comment by gregmac** [comment]
At first glance, I'm guessing fix for this will probably be in the various openPath() methods in https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee ? 

Also experiencing this in Windows (8.1), including with the 'Open with Atom' context item.

**Comment by msiniscalchi** [comment]
I just wanted to point out that this is not just a minor annoyance, but a significant shortcoming for people who want to use Atom to edit LaTeX files. 

Modern TeX distros and PDF viewers include a sync function: you click on a line in the TeX-generated PDF file, and your designated editor opens and jumps to the corresponding point in the TeX source. If the editor stays in the background,  this creates an unneeded friction in the editing process: the user must manually focus the editor before making any changes.

This is only to point out that Atom not focusing correctly is not just something three user has to deal with once, when opening a file; it's a constant annoyance throughout the editing process.

**Comment by nige123** [comment]
Yes - I use a command line utility called "jmp" to open files as part of the editing process. In other editors, for example, sublime - the window comes to the foreground. I'm working on Ubuntu. Any ideas on how to get it to come to the foreground? I'm considering writing some sort of launch wrapper to achieve this.

**Comment by nige123** [comment]
Ok - a fix for Ubuntu users is to do this:

shell> dconf write /org/compiz/profiles/unity/plugins/core/focus-prevention-level 0

This will enable the window to come to the foreground. Use this to restore the default:

shell> dconf write /org/compiz/profiles/unity/plugins/core/focus-prevention-level 1

**Comment by dbackeus** [comment]
Same issue for OSX.

**Comment by lee-dohm** [comment]
@dbackeus I can't reproduce this issue using Atom v1.3.3 on Mac OS X 10.11.2. If you are still running into this problem, please open a new Issue.

**Comment by dbackeus** [comment]
@lee-dohm you are correct, this appears to be fixed in 1.3.3.

**Comment by Pixy** [comment]
I still reproduce the issue on windows 7 in 1.3.3

**Comment by newjie** [comment]
I have similar issue on windows 10, when dbl clicking a file with atom already open, atom doesn't come to foreground. Insteadly, the small icon in the taskbar flashes. 

On my iMac air, there is no such problem.

**Comment by iamprem** [comment]
OS: Ubuntu 15.10
Atom: 1.5.3

Faced the same issue and @nige123 trick fixed it.

**Comment by youurayy** [comment]
still happening, windows 10

**Comment by ArniPL** [comment]
Any news on this issue? It's still happening. Windows 10, Atom 1.8.0.

**Comment by ArniPL** [comment]
I've found that it only happens (Windows), when Atom window is *not* minimized. If you open a file and Atom is minimized, then everything works as expected.

**Comment by youurayy** [comment]
Nah. Happens all. the. time. Just happens. Annoying as hell:)

**Comment by compujosh** [comment]
still an issue on Windows

**Comment by Pixy** [comment]
V1.9.2, still happening, I still can't use Atom because of that =( 
Windows 10

**Comment by skirem** [comment]
thanks for the fix, but the fix ist not includet in 1.9.8? Still got the issue on Windows 10

**Comment by damieng** [comment]
No, the fix was made to master which will be 1.11 - we only tend to hotfix critical regressions on existing stable releases.

**Comment by neverthejetsetter** [comment]
Hello, I am running 1.11.0-Beta-5, and it does not appear that this issue has been resolved.
The difficulty that I am having is that when opening a file from FTP or any other program (including Windows Right click "Open with Atom", Atom does not come to foreground when the file has been opened. It just blinks at me from below on the Windows task bar, and I have to click on Atom on the task bar to bring the window to the foreground.
For clarity, I am running Windows 7 and using WinSCP FTP and Atom together. And Atom is actively running and open (and not minimized).

**Comment by 50Wliu** [comment]
@damieng This still doesn't seem to be working for me when just invoking `atom`, so re-opening.

`atom .` does work, but that also focuses the previously-focused window briefly before the new one pops up, which is pretty jarring.

**Comment by damieng** [comment]
While I do briefly get the previously-focused Window focusing first I am not able to get new instances of Atom to fail to be focused.  I've tried; 

1. From start-bar icon
2. From command prompt with no args
3. From command prompt with arg of a path not yet open
4. From command prompt with arg of a file within a window already open
5. From command prompt with arg of a file within a window not already open
6. Variations of above with ``--wait``

Does anyone have a solid repo that still has this issue on master?

**Comment by 50Wliu** [comment]
This doesn't work for me:
1. Open Atom
2. Minimize it
3. `atom`, `atom path`, `atom already-opened-file`, `atom --wait` all fail to focus the new window.

**Comment by bpasero** [comment]
For Windows 10, this sounds like https://github.com/electron/electron/issues/2867

**Comment by bpasero** [comment]
Fyi this is a good blog post about why on Windows you cannot put a window to the foreground if you are a second instance that talks to the first instance: https://blogs.msdn.microsoft.com/oldnewthing/20090220-00/?p=19083

**Comment by damieng** [comment]
Okay, it looks like a reliable implementation of this is going to require we switch from our own single-instance code to Electron's makeSingleInstance

**Comment by tkoop** [comment]
On this page: https://github.com/electron/electron/issues/2867  andreieftimie posted a workaround:

```
const win = new BrowserWindow();
win.setAlwaysOnTop(true);
win.focus();
win.setAlwaysOnTop(false);
```

I don't know how to use this code, but maybe somebody else here does.

**Comment by damieng** [comment]
Hmm. Interesting, I'll see if that works here.

**Comment by damieng** [comment]
The setAlwaysOnTop didn't work - it did bring the Window above other windows but no amount of win.focus(), app.focus() or alwaysOnTop would get it to focus.  Indeed the only way was a minimize/restore as mentioned on that thread which also has some OS issues.

This is again on hold pending a move to Electron's singleInstance code which correctly does this using the Windows API directly.

**Comment by the-ress** [comment]
You could call [`AllowSetForegroundWindow`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632668.aspx) before telling the existing instance to open a new window ([like VS Code does](https://github.com/Microsoft/vscode/pull/13255/commits/90770d236fe50a4f1874c4934d7158a82b5b3808#diff-d8dfcbab1cae48b2cbc3cabc682c9cd4R308)). Then `focus()` should work as expected. (I believe the right place for this is [here in `AtomApplication.open`](https://github.com/atom/atom/blob/543bde0851375798946ef4fbc08852c996568cf4/src/main-process/atom-application.coffee#L50).)

I made a wrapper for this API: [the-ress/node-windows-foreground-love](https://github.com/the-ress/node-windows-foreground-love)

**Comment by aguilarcarlos** [comment]
The tip proposed by @nige123  worked for me.

**Comment by Peechiz** [comment]
This was happening to me too, but I was able to circumvent it. Context: last session I'd had two different projects open (plus an ftp folder) and whether I started Atom from command line or desktop it would revert to previous session.  By specifying a specific folder, it was able to start and take focus.  

`$ cd someFolder; atom .; cd theOtherFolder; atom -a .`

**Comment by ps374** [comment]
This issue is still happening. I have tried Atom version 1.32, 1.33 and 1.34 (Preview release) but the problem persists. Here is a screenshot depicting Atom is running in the Background (Windows 10):

![atom-issue](https://user-images.githubusercontent.com/10158104/49720983-32ed5800-fc87-11e8-9cfe-81ed4c67a425.png)

**Comment by damieng** [comment]
Yes, this issue was closed not because it is fixed but because there is no activity.

**Comment by ps374** [comment]
[https://github.com/atom/atom/issues/4324#issuecomment-445737826](url)
Also, I tried opening Atom directly, not through Console but it does not work at all. It always runs in the background.

**Comment by the-ress** [comment]
@ps374 Does it open any window at all? Does it show up in the taskbar? (If not, it’s probably not related to this issue.)

**Comment by randysoun** [comment]
Having the same issue as @ps374

**Comment by ps374** [comment]
@the-ress No, it does not open any window at all. No, it does not show up in the Taskbar. 
Is there any solution for this issue: "Atom editor does not go to foreground"?

**Comment by ps374** [comment]
Also, Is there any open case / question for this issue (that I reported)? I will check there then.

**Comment by rsese** [comment]
> No, it does not open any window at all

If that's the case, your issue sounds different than the one reported here as @the-ress mentioned - please open a new a issue with the issue template filled out and we can take a look.

**Comment by debanshumukherjee** [comment]
Greetings Team,

I got this issue resolved by adding the path to the atom.exe file which was (C:\Users\deban\AppData\Local\atom\atom.exe) in my case, to the path environment variable under 
the Advanced system properties (Control Panel\System and Security\System->Advanced system settings->Advanced tab -> Environment variable)...now if I type, for example, atom .bashrc it open Atom in foreground with .bashrc file.
This resolved the issue for me and I hope it does for other too...if not....then my apologies for making you try this.

**Comment by prestapro8** [comment]
In my case. I've renamed the the installed Atom folder from .atom to atom then it worked again.
Happy day to all
