### ISSUE TITLE
Tooltip arrow wrongfully positioned

### ISSUE THREAD

**Issue by wcandillon** [atom/atom#5009]
This happens if the file system pane is closed.
![hnnho9zjh6wvyz_y-d5uheutchljuloo-3etj22umfk](https://cloud.githubusercontent.com/assets/69169/5708259/5b23db90-9a44-11e4-961c-f05aa9c158ff.png)

**Comment by izuzak** [comment]
Looks like a duplicate of https://github.com/atom/tabs/issues/86 and/or https://github.com/atom/tabs/issues/66, so closing this in favor of those two issues.

**Comment by benogle** [comment]
This is actually a core issue, I'd rather leave this open.

**Comment by benogle** [comment]
Also, updated the title

**Comment by mnquintana** [comment]
Yup, I can reproduce this in Yosemite:

1. Hide tree-view
2. Hover over file tab until tooltip pops up

**Comment by mnquintana** [comment]
As far as I can tell, this has been fixed as of Atom 0.190, so I'm going to close this. @wcandillon Feel free to reopen though if you experience this again!

**Comment by benogle** [comment]
![screen shot 2015-04-13 at 11 46 46 am](https://cloud.githubusercontent.com/assets/69169/7122891/3de2892e-e1d3-11e4-9d25-35de2a4d9e98.png)

This is still an issue

**Comment by mnquintana** [comment]
As far as I can tell, this (or something like this) happens whenever a tooltip arrow can't be centered on the element it's bound to (ie. if the element is up against the window edge and the tooltip content is long enough). Here's another example from find-and-replace:

## No arrow
![screenshot 2015-05-18 18 15 12](https://cloud.githubusercontent.com/assets/823545/7691614/ec778274-fd89-11e4-9dcd-e1a4dd014fe0.png)
![screenshot 2015-05-18 18 15 01](https://cloud.githubusercontent.com/assets/823545/7691615/ec790018-fd89-11e4-8746-c254af73fde6.png)

## Arrow
![screenshot 2015-05-18 18 15 20](https://cloud.githubusercontent.com/assets/823545/7691616/ec79b904-fd89-11e4-8fe2-046509841c3a.png)
