### ISSUE TITLE
New icon looks pixellated on Debian

### ISSUE THREAD

**Issue by drammock** [atom/atom#5474]
Just updated to 0.177.0. Love the new logo, but...  I read through #4807 and noticed that the other OSes got various pre-built icon sizes, whereas the Linux version only gets one big 1024x1024 image.  Here's a screenshot of how that looks when crammed into a Linux dock:

![atomiconscreenshot](https://cloud.githubusercontent.com/assets/1810515/6119513/a3e606d8-b104-11e4-999d-8222c3469077.png)

So pixellated!  Last I checked `xdg-icon-resource install` still does not support SVGs, but could Linux users get multiple sizes of PNGs too?

**Comment by 50Wliu** [comment]
This will be fixed in v0.178.0 (see #5405 for details).

**Comment by drammock** [comment]
@50Wliu Thanks, and sorry I didn't turn up that answer myself before opening a new issue.

**Comment by drammock** [comment]
it looks like #5405 only affects RPM, not debian builds?  I'm now on 0.179.0, the screenshot above still reflects what I am seeing, and there is still only one logo png in the install tree, at: 

> /usr/share/atom/resources/app/resources/atom.png

Reopen?

**Comment by kevinsawicki** [comment]
@drammock is this still an issue on Atom 1.0+?

**Comment by 50Wliu** [comment]
I can't reproduce this on Ubuntu 15.04 (Unity).

**Comment by thomasjo** [comment]
Not reproducible in Ubuntu 14.04 LTS either. I'd say this has been resolved.

**Comment by kevinsawicki** [comment]
@50Wliu and @thomasjo thanks for testing, closing this out.

**Comment by drammock** [comment]
sorry to chime in late.  I'm still seeing the original problem here, but if it's working for others then I won't re-open on the assumption that I'm just being too finicky about the appearance.  FWIW, after updating to 1.0.2, on my system `locate atom | grep png` yields only one relevant file: `/usr/share/pixmaps/atom.png`, and that file (which is 1024x1024px) is getting scaled down for menus/docks/etc (and looks bad to my eye), rather than using pre-built versions of the icon at various sizes for the different uses.
