### ISSUE TITLE
Restart and Update Doesn't from Release Notes Page

### ISSUE THREAD

**Issue by joshvickerson** [atom/atom#5692]
Using the Restart and Update button on the release notes view doesn't properly restart and update. Atom closes, but it never restarts. When launched again, it hasn't updated. Restart and update from the Atom Menu works fine.

2010 iMac, OSX 10.10.2

**Comment by mnquintana** [comment]
Which version of Atom?

**Comment by joshvickerson** [comment]
I've noticed this on the past few releases and have just gotten around to submitting the issue.

In the most recent case I was trying to update from .181 to .182

**Comment by judahstevenson** [comment]
I'm experiencing this problem as well, but only when I open atom from the command line, and even then it only happens on certain repos. If i open atom using spotlight it doesn't happen. I'm on version .188 but the notes page show's the latest release as .186

Clicking on the "restart and update" button closes Atom, but then it never re-opens. If I open from the command line again after that it opens on the release notes page as before.

**Comment by cemsbr** [comment]
It is happening with me from 191 to 192

**Comment by judahstevenson** [comment]
hallelujah I was finally able to fix the behavior in my installation of atom. I stumbled across this forum discussion about cache in atom: 

https://discuss.atom.io/t/clean-cache-when-atom-starts/13196/5

I closed atom, deleted all the content in ```` ~/.atom/storage ````

restarted atom via spotlight, then opened the repo that I had been experiencing the problem with. No files opened up by default, including the release notes view. 

When I posted my original comment I was on version 181/182 but I have kept current with releases, even though the problem persisted. I'm on 192 right now. 

It might be worth noting that prior to trying this solution I had also tried just nuking the entire repo and re-cloning but it had no effect.

**Comment by mark-hahn** [comment]
> Using the Restart and Update button on the release notes view doesn't properly restart and update. 

I don't see any such button in my Atom release notes page.  Where is it supposed to be?  I'm on atom 190 on Ubuntu 14.0.4.

BTW, I haven't gotten an auto-update in months when on Windows.  I'm now on Linux.  Does it work differently than on Windows?

I just tried clearing storage.  I'll see if I get an update.  If I don't I'll file an issue.  I've been putting that off for a long time.

**Comment by 50Wliu** [comment]
Linux doesn't have auto-updates yet.

**Comment by cemsbr** [comment]
@joshvickerson , it also worked for me. Before, I noticed that there is no Restart and Update button if atom is launched in a folder where it hasn't been launched before. Probably because there is no entry for that folder in the storage files.

**Comment by mark-hahn** [comment]
>Linux doesn't have auto-updates yet.

So I guess that is also why there are no update buttons.

**Comment by ChristianGrech** [comment]
+1

**Comment by Stanzilla** [comment]
For me, even restart and update from the Atom menu never works. I was told by @paulcbetts this was an issue because Atom was using an older version of Squirrel but this has since then been updated and it still does not work. (Windows)

**Comment by elxris** [comment]
Help!
I tried to close Atom `rm -r ~/.atom` and then initialize atom then press the button in the bar menu `restart and update`, but nothing happens. Later I opened Atom and is not updated. I'm in 1.0.3

I search in the console and found this 4 messages over and over and over.
```
8/18/15 2:06:48.661 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[580]) Service could not initialize: 14E46: xpcproxy + 13421 [1402][7D917364-B96E-3F93-B923-A89B5BF5736D]: 0xd
8/18/15 2:06:48.661 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
8/18/15 2:06:49.664 PM com.apple.xpc.launchd[1]: (com.apple.spindump[581]) Service exited with abnormal code: 75
8/18/15 2:06:49.664 PM com.apple.xpc.launchd[1]: (com.apple.spindump) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by dstack27** [comment]
Still doesn't work for me either. The only thing that seems to work is downloading and reinstalling from atom.io - OS X 10.10.4.

**Comment by Stanzilla** [comment]
Still does not work, just updated from .15 to .16.

**Comment by bunster** [comment]
I'm having this problem too. I'm on version 1.0.15 and the next update it wants me to restart and update to is 1.0.16. I downloaded Atom from the main website. I've tried clearing `~/.atom/storage/` as suggested above and it still didn't work. I've waited a long time and it just isn't working. I'm on **OS X Yosemite 10.10.5**.

**Comment by piotr-cz** [comment]
This happens for me in the `v1.0.19`. Release notes show that latest installed version is `v1.0.18` and there is a button 'Restart and update' that does nothing.

**Comment by tompave** [comment]
This has been happening for me since the very first release. Still happening at the moment, with the latest.

**Comment by MentalGear** [comment]
Hey guys,

I had also stuck updates, even deleting the app & manually dl it again didn't solve it.

However, going to "~/.atom/" and deleting the "compile-cache" did the trick !

**Comment by piotr-cz** [comment]
Deleting `compile-cache` contents didn't help me.
Release notes still show v1.1.0 and _Restart and Update_ button even if I'm on v1.2.4

**Comment by hugoduraes** [comment]
Restart and Install Update doesn't work for me either.

If it helps, I'm running Atom v1.2.3 on OS X El Capitan (10.11.1) from my user's Applications folder.

**Comment by ryanaltvater** [comment]
I'm also experiencing the same issue. Oddly enough, even though I downloaded 1.2.4 and overwrote my current version manually, when I open the release notes the last version listed is 1.1.0 and it still asks me to restart and update even though "About Atom" shows 1.2.4.

**Comment by hugoduraes** [comment]
@ryanaltvater try the solution I've posted above.

**Comment by ryanaltvater** [comment]
I ran those couple commands and I'm not seeing anything different.

**Comment by samuarl** [comment]
@hugoduraes This solution resolved the problem for me. Thanks!

**Comment by lukeapage** [comment]
+1 on windows 7, behind a proxy, just updated to 1.3.3, last release notes show 1.1.0

**Comment by joshaber** [comment]
#10377 addressed this by removing release-notes.

**Comment by NoNameProvided** [comment]
Atom 1.5.3 cant update to 1.5.4 on my Mac. Should I create a new issue or continue the discussion here?

**Comment by krishnadasmallya** [comment]
Same for me here. OSX 10.10.4 and Atom 1.5.3. It shows downloading then asks for password with "Add Helper" button but when I try Restart and install update, it quits but doesn't start. Have waited really long but do not see any process associated. Please advise if a new issue needs to be created.

**Comment by piotr-cz** [comment]
so long, release notes.

**Comment by dylan-baskind** [comment]
Hopefully someone finds this helpful -- on OSX, although the button on the UI fails silently,  going to the "Atom" in the OSX menu bar (i.e. next to Apple symbol), and clicking "Restart and Install Update" worked for me.

**Comment by sandrodz** [comment]
confirming, workaround by @dylan-baskind  works.

**Comment by jriesen** [comment]
Just got this problem trying to upgrade from 1.7.4 to 1.8.0, the workaround by @dylan-baskind worked for me too.

**Comment by Sogl** [comment]
@dylan-baskind Many thanks! Helped me to update from 1.7.4 to 1.8.0 on OS X 10.11.5.

**Comment by Dayjo** [comment]
Same as above, @dylan-baskind workaround worked for me

**Comment by sjsadowski** [comment]
Just another confirmation of what @dylan-baskind stated as a workaround; button did not work, menu item does. OSX 10.10.5

**Comment by 50Wliu** [comment]
Can someone affected by the About UI bug please open a new issue on [atom/about](https://github.com/atom/about)?  Thanks!

**Comment by controversial** [comment]
@50Wliu Still experiencing this, will open.

**Comment by ilg-ul** [comment]
the workaround (using the menu item) did not work for me. 

I guess the problem is related to the fact that my account has no administrative rights, and the update procedure should ask the user for a password in order to be able to write into the `/Applications` folder.

**Comment by RyanBalfanz** [comment]
It didn't work for me either, possibly due to permissions (just as @ilg-ul alluded). I've installed with two different mechanisms. One does ask for my password to install a Helper (which doesn't seem to do anything, possibly fails), and another (via Homebrew Cask) doesn't. In both cases, the auto-update from the about page as well as from the menu bar, fail. Atom does close, but never restarts.

**Comment by privateblue** [comment]
This bug is still there. I couldn't find any other way to update, but to download Atom again from atom.io.

**Comment by ilg-ul** [comment]
if you are security concerned and your account has no administrative rights, one possible workaround is to install Atom in `$HOME/Applications` instead of `/Applications`.

**Comment by privateblue** [comment]
That's a good idea, thanks @ilg-ul

**Comment by yobyot** [comment]
This has _been driving me crazy_. And I think @ilg-ul nailed the issue. But why, OH WHY, does Atom -- unlike so many other utilities -- insist on making our machines less secure by requiring administrative access on macOS?

**Comment by ilg-ul** [comment]
laziness?

**Comment by RyanBalfanz** [comment]
@ilg-ul, @privateblue, @yobyot 

FWIW: I'm guessing a lot of people install Atom using Homebrew, which installs to `/Applications` by default.

**Comment by jriesen** [comment]
I installed Atom a long time ago (not long after it came out) from atom.io.  The ZIP file just unzips into an Atom.app, which - as has been the practice on Macs for a very long time - I dragged to my Applications folder to install.  This installs it into /Applications.  I never installed it via Homebrew.  (In fact, I never knew you _could_ install it via Homebrew - I may do that instead.)  My Mac has 133 apps on it in /Applications, and two apps in $HOME/Applications that were put there by installers, plus the Chrome Apps folder.

It should be generally assumed that Atom will be placed into /Applications by users, unless the Atom team actually builds an OS/X installer for it instead of providing a .app build.

**Comment by RyanBalfanz** [comment]
@jriesen When I said Homebrew I really meant [Homebrew Cask](https://github.com/caskroom/homebrew-cask).

**Comment by ioquatix** [comment]
As well as not working for me, it appears Atom Helper chewed through my entire monthly allocation of mobile data in the background despite having check for updates switched off :(

**Comment by janoschpizza** [comment]
This has never worked for me and as of version 1.12.7 is still not working. It now does restart the app (which it didn't do before) but it doesn't update. Upon selecting "check for update" the update is being re-downloaded again. 

I think @ilg-ul is correctly pointing to lack of permissions. I'm also not using an admin/root account and normal procedure for installing would be presenting a credentials dialog. 

OSX 10.10.5

**Comment by ali-hellani** [comment]
+1, version 1.12.7 is still not working

**Comment by ilg-ul** [comment]
good luck with this!

(I'm no longer using Atom...)

**Comment by audrummer15** [comment]
Has never worked for me, and I'm still on 1.10.2 because of it

**Comment by TylerBrock** [comment]
This just started happening to me. Lame.

**Comment by MentalGear** [comment]
Yupp, started again !

**Comment by tompave** [comment]
Seems odd that this issue was closed, since it's not been resolved.
Is anyone looking at this, @nathansobo ?

**Comment by 50Wliu** [comment]
Check for relevant issues on the [atom/about](https://github.com/atom/about) repo, which handles most of the restart-and-update logic now.

**Comment by maahd** [comment]
Had a similar issue. Was resolved by repeatedly trying restart and install updates. However, it seems like the update process is a bit broken on OS X. I still see the old versions for atom whereas I don't see them for other apps. Was almost considering switching back to Sublime...but I hate the popups...maybe I should buy Sublime...

![screen shot 2017-03-03 at 8 37 48 pm](https://cloud.githubusercontent.com/assets/3487028/23566247/64df5fe0-0051-11e7-8647-f882a22ed60f.png)

**Comment by nmagedman** [comment]
I've been experiencing this silent update failure as well.  I noticed that `~/Library/Caches/com.github.atom.ShipIt/ShipIt_std{err,out}.log` were owned by root.   From memory, I recall that the `~/Library/Caches/com.github.atom.ShipIt/` folder itself was also owned by root, but I can't now find the lines in my terminal's scrollback buffer to corroborate that.

The ShipIt_stderr.log file had the following repeating every two seconds:
```
2017-06-08 13:38:16.419 ShipIt[84425:3320374] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fe0f3e0ac50 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fe0f3e057b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-06-08 13:38:16.420 ShipIt[84425:3320374] ShipIt quitting
```

Notice that it's trying to access the _root_ user's Library/Caches folder, not my own.

I moved the folder aside and a few moments later some process recreated the folder and files, with the same ownership as before (i.e. all root; or some files root, some me).

I followed a suggestion from several comments on https://discuss.atom.io/t/restart-and-update-does-not-work-macos/15067/30 to `sudo chown -R` the folder to myself.  I then had similar lines in the ShipIt_stderr.log, but referencing my *own* Library/Caches folder: 
`/Users/noach/Library/Caches/com.github.atom.ShipIt/ShipItState.plist`.   (At some point, the logfile must have gotten truncated or deleted, because it doesn't have the /var/root/Library/... lines anymore.)

These new lines continued every two seconds until I started Atom again at which point it stopped.  (Presumably it created the plist file at that point.)

From there, I was able to upgrade Atom from within the app and got the following:

```
2017-06-22 17:08:35.574 ShipIt[65729:2230846] Beginning installation
2017-06-22 17:09:18.410 ShipIt[65729:2224503] Moved bundle from file:///Applications/Atom.app to file:///var/folders/sm/7bqrc0f52jb3_g7sns2vh28r0000gn/T/com.github.atom.ShipIt.hEc8xF5H/Atom.app
2017-06-22 17:09:18.410 ShipIt[65729:2224503] Moved bundle from file:///var/folders/sm/7bqrc0f52jb3_g7sns2vh28r0000gn/T/com.github.atom.ShipIt.PAMesPEo/Atom.app to file:///Applications/Atom.app
2017-06-22 17:09:23.073 ShipIt[65729:2224503] Couldn't remove owned bundle at location file:///var/folders/sm/7bqrc0f52jb3_g7sns2vh28r0000gn/T/com.github.atom.ShipIt.PAMesPEo/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/sm/7bqrc0f52jb3_g7sns2vh28r0000gn/T/com.github.atom.ShipIt.PAMesPEo/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2017-06-22 17:09:26.051 ShipIt[65729:2224503] Installation completed successfully
2017-06-22 17:09:26.117 ShipIt[65729:2231716] Application launched at file:///Applications/Atom.app
2017-06-22 17:09:26.118 ShipIt[65729:2231716] ShipIt quitting
```

I am now running the latest version.

Note BTW the gap in the timestamps (June 8 to June 22).  I have some ideas about what might have happened (inability to write to the root-owned logfile), but that's inconsistent with my (probably faulty) memory of the sequence of events in troubleshooting this.   Still, I hope that this accounting might provide helpful information for resolving the problem.

The main takeaway is that some root-owned process is creating files/folders that are then unreadable by user-owned processes, causing the upgrade to fail.

**Comment by Tim15** [comment]
I am getting the same exact issue as @nmagedman 
```
2017-07-22 13:00:26.669 ShipIt[66133:1248464] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fd663d14fd0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fd663d13580 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-07-22 13:00:26.669 ShipIt[66133:1248464] ShipIt quitting
```
Over and over again.

Please fix this. It's a quite a drag to have to reinstall to update this. This is quite an issue for a large portion of users.

**Comment by nmagedman** [comment]
@Tim15 Please run `ls -la ~/Library/Caches/com.github.atom.ShipIt` and paste the output here.

**Comment by Tim15** [comment]
```
$ ls -la ~/Library/Caches/com.github.atom.ShipIt
total 80264
drwxr-xr-x   6 timhigins     staff       204 Aug 29 18:01 .
drwx------+ 57 timhigins     staff      1938 Aug 29 22:12 ..
-rw-r--r--@  1 timhigins     staff      6148 Aug 29 17:53 .DS_Store
-rw-r--r--   1 timhigins     staff       282 Aug 29 17:53 ShipItState.plist
-rw-r--r--   1 root          staff  41080468 Jul 22 13:00 ShipIt_stderr.log
-rw-r--r--   1 root          staff         0 Jul 20 13:06 ShipIt_stdout.log
```

**Comment by Tim15** [comment]
Sadly, after tiring of this issue, I just upgraded Atom by copying the auto-downloaded Atom.app to my Applications, so I can't get more info for the downloads. However, I do know there was a folder with an id like `gpfsqhde` (for illustration) that contained an `atom.zip` and then an `Atom.app`. 

I assume the updater would then just start a separate process, shut down Atom, copy in the new Atom, and start the new Atom. That seems to be where the error is and @nmagedman you are probably right that is an issue with the permissions.

**Comment by janoschpizza** [comment]
This seems to be a general problem with Electron apps that rely on ShipIt for updates.  Check similar (long) thread on VS Code repo. Same fix should apply here, although it's not working for me for other reasons, probably due to running as a non-admin user in OSX. For me the solution was to move these apps to the ~/Applications folder, which is not ideal.

https://github.com/Microsoft/vscode/issues/7426

**Comment by 50Wliu** [comment]
An upcoming Electron upgrade should properly fix this issue as it will bring in Squirrel (ShipIt) fixes for non-Admin accounts.

**Comment by janoschpizza** [comment]
That's really good news @50Wliu . Very much looking forward to this update!

**Comment by Tim15** [comment]
Finally, this issue is solved, in Atom ~1.20. Thanks to everyone!

**Comment by lschuetze** [comment]
I still get errors with the update from 1.21.0 to 1.21.1 looking like the outputs from @nmagedman.

This was today morning as I tried to install an update and restarted Atom because it seemed to not do anything: 

`~ ➜ more ~/Library/Caches/com.github.atom.ShipIt/ShipIt_stderr.log`
```
2017-10-16 06:47:42.873 ShipIt[93138:9198651] Beginning installation
2017-10-16 06:47:50.818 ShipIt[93138:9198652] Moved bundle from file:///Applications/Atom.app to file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.SmVJ0BWZ/Atom.app
2017-10-16 06:47:50.819 ShipIt[93138:9198652] Moved bundle from file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.JcuJdIbD/Atom.app to file:///Applications/Atom.app
2017-10-16 06:47:50.829 ShipIt[93138:9198652] Couldn't remove owned bundle at location file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.C9wRH3i/Atom.app/, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.C9wRH3i/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2017-10-16 06:47:50.830 ShipIt[93138:9198652] Couldn't remove owned bundle at location file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.JcuJdIbD/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.JcuJdIbD/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2017-10-16 06:47:51.755 ShipIt[93138:9198652] Installation completed successfully
2017-10-16 06:47:51.755 ShipIt[93138:9198652] ShipIt quitting
2017-10-16 06:49:20.086 ShipIt[98155:9201773] Beginning installation
2017-10-16 06:49:22.677 ShipIt[98155:9201774] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.7cVhCRG6/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.7cVhCRG6/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSUnderlyingError=0x7fdc34546780 {Error Domain=NSCocoaErrorDomain Code=4 "The file “test” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.7cVhCRG6/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/bl/test, NSUnderlyingError=0x7fdc3455d4c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.7cVhCRG6/Atom.app}
2017-10-16 06:49:22.677 ShipIt[98155:9201774] ShipIt quitting
2017-10-16 06:49:28.716 ShipIt[98199:9202636] Resuming installation attempt 2
2017-10-16 06:49:28.724 ShipIt[98199:9202637] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.fJGpUGY8/Atom.app" UserInfo={NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app, NSLocalizedDescription=Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.fJGpUGY8/Atom.app, NSUnderlyingError=0x7fdbb4007f90 {Error Domain=NSCocoaErrorDomain Code=260 "The file “Atom.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app, NSUnderlyingError=0x7fdbb4007e20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-10-16 06:49:28.724 ShipIt[98199:9202637] ShipIt quitting
2017-10-16 06:49:28.798 ShipIt[98215:9202679] Resuming installation attempt 3
2017-10-16 06:49:28.805 ShipIt[98215:9202706] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.6Wphk7Vo/Atom.app" UserInfo={NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app, NSLocalizedDescription=Failed to copy bundle file:///Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app/ to directory file:///var/folders/28/fqt91mbn0rs_zf8dxkqw4pbr0000gn/T/com.github.atom.ShipIt.6Wphk7Vo/Atom.app, NSUnderlyingError=0x7fed4c013bc0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “Atom.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/lschuetze/Library/Caches/com.github.atom.ShipIt/update.KxzDZee/Atom.app, NSUnderlyingError=0x7fed4c00bc40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-10-16 06:49:28.805 ShipIt[98215:9202706] ShipIt quitting
```

**Comment by Eschon** [comment]
I also can't update from 1.21.0 to 1.21.1 on OSX 10.11.6

Here's my ShipIt error log:
```
2017-10-13 11:26:04.151 ShipIt[95029:11820170] Beginning installation
2017-10-13 11:26:06.836 ShipIt[95029:11820168] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/ to directory file:///var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.haFla86g/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.haFla86g/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSFilePath=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSUnderlyingError=0x7f93b1e25110 {Error Domain=NSCocoaErrorDomain Code=4 "The file “package.json” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.haFla86g/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSFilePath=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/Contents/Resources/app/apm/node_modules/asynckit/package.json, NSUnderlyingError=0x7f93b1e258a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/egon/Library/Caches/com.github.atom.ShipIt/update.XLhc8VW/Atom.app/ to directory file:///var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.haFla86g/Atom.app}
2017-10-13 11:26:06.837 ShipIt[95029:11820168] ShipIt quitting
2017-10-13 20:09:53.874 ShipIt[40139:12888069] Resuming installation attempt 2
2017-10-16 11:43:21.556 ShipIt[2984:325533] Resuming installation attempt 3
2017-10-16 11:43:24.530 ShipIt[2984:325534] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/ to directory file:///var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.4M1Occix/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.4M1Occix/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSFilePath=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSUnderlyingError=0x7fa4c1602350 {Error Domain=NSCocoaErrorDomain Code=4 "The file “Libraries” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.4M1Occix/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSFilePath=/Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries, NSUnderlyingError=0x7fa4c161c040 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/egon/Library/Caches/com.github.atom.ShipIt/update.6NxrE0u/Atom.app/ to directory file:///var/folders/rh/0xm8ygv57lj_2t187v1c3fgm0000gp/T/com.github.atom.ShipIt.4M1Occix/Atom.app}
2017-10-16 11:43:24.530 ShipIt[2984:325534] ShipIt quitting
```

**Comment by timrayers** [comment]
Eschon:
> I also can't update from 1.21.0 to 1.21.1 on OSX 10.11.6

Getting the same ShipIt log error as @Eschon when trying to update from 1.21.1 (x64) to 1.22.0

**Comment by joelricci** [comment]
Yeah, same thing for me. This still doesn't work. I updated from OSX 10.10 to 10.12 but it made no difference.

**Comment by timrayers** [comment]
@joelricci this worked for me:

1. In Atom, download the update
2. Click Restart and Install button. Atom then 'closes' itself, but in the dock you should see that it appears to be open despite the window closing
3. Right click the dock icon, click Quit
4. Wait; Atom should then reopen itself, with the update applied.

**Comment by joelricci** [comment]
@timrayers For me, when I click "Restart and Install", Atom restarts fine but it doesn't actually being updated, it's still stuck on the same version. Hence it keeps repeating over and over; downloading, restarting, downloading, restarting and so on...

I think we are looking at (at least) two different problems here. I strongly believe my problem is related to using a non-Admin account because I have the same issue with other Electron apps as well. The workaround for me is moving problematic apps to $home/Applications but it comes with other problems.

So, still waiting, still hoping...

**Comment by timrayers** [comment]
@joelricci sounds like it! Good luck...

**Comment by morkro** [comment]
The issue still persists for me on macOS Sierra and latest Atom (currently 1.23.1). I click restart, Atom closes but never opens. If I click on the app icon again it opens but hasn't uploaded. I repeat the action and it works.

**Comment by joelricci** [comment]
@morkro Just out of curiosity, does your mac OS user account have administrative rights?

**Comment by morkro** [comment]
@joelricci I have in fact restricted administrative rights :)

**Comment by joelricci** [comment]
@morkro So have I. I suspect this is part of the problem. However, I have **never** been able to update Atom by manually restarting, like you seem to have. And my Atom restarts, it just doesn't update. So, there are probably several issues working together to cause this problem.

**Comment by 50Wliu** [comment]
@morkro @joelricci As [per my last comment](https://github.com/atom/atom/issues/5692#issuecomment-332588439), this should be fixed in an upcoming Electron upgrade (currently, we'll need to upgrade to at least Electron 1.8, which is still in beta).

**Comment by joelricci** [comment]
This is good news @50Wliu. I thought the upgrade had already been done, hence my vigorous posting here. I guess we'll just hang tight until the upgrade is through then and wish for the best 👍

**Comment by joachim-n** [comment]
I still get this problem.

The contents of ~/Library/Caches/com.github.atom.ShipIt/ShipIt_stderr.log shows:

```
2018-01-24 11:16:30.525 ShipIt[35827:223367] Moved bundle from file:///var/folders/ww/qthsz0j54kg77tbycjdnntwm0000gn/T/com.github.atom.ShipIt.1k787kjj/Atom.app to file:///Applications/Atom.app
2018-01-24 11:16:31.454 ShipIt[35827:223367] Couldn't remove owned bundle at location file:///Users/joachim/Library/Caches/com.github.atom.ShipIt/update.r7TTRnN/Atom.app/, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/Users/joachim/Library/Caches/com.github.atom.ShipIt/update.r7TTRnN/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
```

**Comment by FMJansen** [comment]
For me the problem persists as well (today on 1.25.0 to 1.25.1, happend on 1.24.x to 1.25.0 and other upgrades, too). OS X 10.11.6.
`/Users/floris/Library/Caches/com.github.atom.ShipIt/ShipIt_stderr.log`:
```
2018-04-07 21:20:49.608 ShipIt[3050:2331363] Moved bundle from file:///Applications/Atom.app to file:///var/folders/3v/jmkl1mjx2hb8b3lxt7hpsbz40000gn/T/com.github.atom.ShipIt.qBYd2aiF/Atom.app
2018-04-07 21:20:49.608 ShipIt[3050:2331363] Moved bundle from file:///var/folders/3v/jmkl1mjx2hb8b3lxt7hpsbz40000gn/T/com.github.atom.ShipIt.3yuLNn5z/Atom.app to file:///Applications/Atom.app
2018-04-07 21:20:50.922 ShipIt[3050:2331363] Couldn't remove owned bundle at location file:///var/folders/3v/jmkl1mjx2hb8b3lxt7hpsbz40000gn/T/com.github.atom.ShipIt.3yuLNn5z/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/3v/jmkl1mjx2hb8b3lxt7hpsbz40000gn/T/com.github.atom.ShipIt.3yuLNn5z/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
```

**Comment by moleculezz** [comment]
Also still having the same problem

```
2018-04-20 09:38:39.039 ShipIt[14495:481542] ShipIt quitting
2018-04-20 09:41:57.123 ShipIt[15277:484548] Resuming installation attempt 3
2018-04-20 09:42:02.556 ShipIt[15277:484549] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/ to directory file:///var/folders/wq/2qbvwp710zb41gbd7_hz3cmh0000gn/T/com.github.atom.ShipIt.txK3D0js/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/Contents/Resources/app.asar.unpacked, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/wq/2qbvwp710zb41gbd7_hz3cmh0000gn/T/com.github.atom.ShipIt.txK3D0js/Atom.app/Contents/Resources/app.asar.unpacked, NSFilePath=/Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/Contents/Resources/app.asar.unpacked, NSUnderlyingError=0x7fbac4f7d370 {Error Domain=NSCocoaErrorDomain Code=4 "The file “app.asar.unpacked” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/Contents/Resources/app.asar.unpacked, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/wq/2qbvwp710zb41gbd7_hz3cmh0000gn/T/com.github.atom.ShipIt.txK3D0js/Atom.app/Contents/Resources/app.asar.unpacked, NSFilePath=/Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/Contents/Resources/app.asar.unpacked, NSUnderlyingError=0x7fbac4f7de20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/gdarends/Library/Caches/com.github.atom.ShipIt/update.suuaj0c/Atom.app/ to directory file:///var/folders/wq/2qbvwp710zb41gbd7_hz3cmh0000gn/T/com.github.atom.ShipIt.txK3D0js/Atom.app}
```

**Comment by metakermit** [comment]
What @timrayers suggested [here](https://github.com/atom/atom/issues/5692#issuecomment-342794780) worked for me. Too bad this is still happening 3 years after the issue's been reported 😕

**Comment by stephenshutters** [comment]
Dude. THANK YOU. That worked for me, @metakermit!

**Comment by framerate** [comment]
@metakermit 's suggestion of @timrayers' steps does indeed work. This is the #2 bug that makes me think "Maybe I SHOULD switch to VSCode" every time it happens (right behind the "why is ESLint taking 2 hours to lint this project" but I don't know for a fact that has anything to do with atom directly... just that VSCode lints it a lot faster :P

**Comment by chimit** [comment]
The only way to bypass this problem was [described](https://github.com/atom/atom/issues/5692#issuecomment-342794780) by @timrayers.

It lasts for years without fixing.

**Comment by chimit** [comment]
@mnquintana, @50Wliu please, reopen this issue. The problem still takes place.

**Comment by morkro** [comment]
I also have this issue still. I accepted it as a quirk of Atom, but it sure is annoying. Takes me a couple of restarts every time Atom has an update.

**Comment by joelricci** [comment]
Ya, I can confirm the issue still exists. I solved it by switching to another editor :-/

**Comment by jriesen** [comment]
I've noticed in recent years that when you've downloaded an update to Atom and then close the editor, it immediately begins update installation via a ShipIt executable that runs silently in the background (you can see it in Activity Monitor).  If you relaunch Atom before ShipIt is finished, you end up getting the old version, at which point it redownloads the update and the cycle begins anew.  I've learned to wait and make sure ShipIt has actually finished installing the update and terminated (and sometimes it can take over a minute!) before relaunching Atom manually.

**Comment by morkro** [comment]
That's some great insight @jriesen! I wonder if Atom could just open a separate window in Electron with a loading indicator until ShipIt has finished the download. It might not be ideal, but at least it provides some feedback to the user on what is going on.

**Comment by chimit** [comment]
Was finally fixed in 1.36.1! I got Atom updated automatically the first time today since 2015 😀

**Comment by stephenshutters** [comment]
I sure hope what you say rings true for me as well, @chimit.
