### ISSUE TITLE
Settings-view package - Uncaught SyntaxError: Unexpected token C

### ISSUE THREAD

**Issue by fogine** [atom/atom#6161]
When I go to Settings panel I get Uncaught SyntaxError on "packages", "themes", "updates" and "install" tabs.
Note that atom can't load any data from the internet about packages etc..
I'm running nodejs version 0.12.1 x64
Atom v.0.190.0

Error:
> SyntaxError: Unexpected token C
>   at Object.parse (native)
>   at C:\Users\User name with space\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:61:27
>   at exit (C:\Users\User name with space\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
>   at BufferedProcess.triggerExitCallback (C:\Users\User name with space\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:63:47)
 >  at ChildProcess.<anonymous> (C:\Users\User name with space\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:85:18)
>   at ChildProcess.emit (events.js:119:17)
>   at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

**Comment by izuzak** [comment]
When did that start happening, @fogine? Do you have any packages installed? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by fogine** [comment]
Platform Windows 7 x64.

I installed clean version of atom, when I try to install packages I got the above error in settings panel (see image). 
Yes I can reproduce the problem in safe mode.
![atom](https://cloud.githubusercontent.com/assets/7884288/6901422/4ccadeda-d70d-11e4-96dc-4c822697a3df.jpg)

I've tried to reinstall nodejs after I got the error.

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/settings-view/commit/e5c1024812533ba1b5f71a4d2c840614a7e7e318

**Comment by fogine** [comment]
On updates tab I'm still getting "Unexpected token C" Error. But I can't show stack trace anymore....
On packages tab it always freeze on "Loading packages...."

**Comment by mnquintana** [comment]
@fogine This will be fixed in the next version of Atom (0.195.0).
