### ISSUE TITLE
Cannot paste into Atom from other apps; cannot paste from Atom into other apps; may crash Atom

### ISSUE THREAD

**Issue by alexdor** [atom/atom#6221]
I'm using Atom ver. 0.189.0 on Ubuntu 14.04.2 LTS. When I copy a piece of text in atom and I try to paste it the right-click menu either won't show up or will show up without giving me option to paste. The paste shortcut doesn't work either and it creates issues even if I try to copy and paste text from other programs (after I have coping something from atom). I have disable all the extra plugins, so it isn't a plugin issue. I didn't had this issue with the previous version (I am using webupd8 ppa). If I do a right click on a place where there isn't a text entry (meaning a place where it doesn't support paste anyway) the right click menu appears fine.

**Comment by YuriSolovyov** [comment]
+1. Ubuntu 14.04.2 LTS
```
atom -v
0.190.0-7c2b9fa
```

**Comment by amayer5125** [comment]
I can copy and paste within Atom. I can paste things copied from outside Atom. But I can not copy in Atom and paste outside of Atom.
OS: Fedora 21
Atom: 0.189.0

**Comment by alexdor** [comment]
@amayer5125  Oh yeah I forgot to mention that... Same here

**Comment by jrmedd** [comment]
Yep, cannot paste anywhere outside of Atom:

Ubuntu 14.04.02
Atom 0.189.0

**Comment by marcopiraccini** [comment]
+1
Ubuntu 14.10 64
Atom 0.189.0

**Comment by mohoff** [comment]
In my case, Atom crashes when trying to paste something inside Atom which was copied from outside. 

Ubuntu 14.04.02
Atom 0.189.0

**Comment by Huluti** [comment]
I have this bug too...
Ubuntu 14.10
Atom 0.189.0

**Comment by 50Wliu** [comment]
Can confirm on `0.190.0-b72b111`, Ubuntu 14.10.
Copying within Atom will actually disable right-click outside of Atom if you attempt to right-click inside a textbox :frowning:.  Once you copy something else then right-click-->paste all the previous right-clicks suddenly get registered :confused:.

**Comment by andya9** [comment]
I confirm the issue on Arch Linux, atom 189.

**Comment by www2000** [comment]
I have the same problem from atom 0.189 to gedit and from gedit.
ubuntu 14.04 64 bit

**Comment by amayer5125** [comment]
Another observation: I can not copy and paste from one Atom window to another.

**Comment by Mayccoll** [comment]
also crash atom
Linux Mint 17.1
Atom 0.189.0

**Comment by marcopiraccini** [comment]
Any workaround? With this issue, atom is quite unusable...

**Comment by Zireael07** [comment]
Wonder what caused it? And does it happen on other OSes? I'm pretty scared to try it now on Win...

**Comment by jacobmischka** [comment]
Also having this issue. Copying text within atom completely breaks the clipboard, preventing context menus as mentioned and even breaking clipboard managers like clipit.

**Comment by edgard** [comment]
Same, clipboard not working properly and random crashes. Fine with 0.188.0.

**Comment by amayer5125** [comment]
Ive experienced Chrome crashing also when trying to copy and paste in Atom. Also on Fedora 21 Gnome.

**Comment by muchweb** [comment]
Cannot copy any text outside of editor and frequent crashes (with loss of data).

Cannot believe that such a major bug made it to a release :-1:

---
GNU Operating System, Atom `v0.189.0`

**Comment by gpolek-gp** [comment]
+1 Ubuntu 14.04

Atom v0.189.0 downloaded from Atom.io.

**Comment by izuzak** [comment]
@zcbenz Any ideas what might be causing this?

**Comment by despairblue** [comment]
probably the same bug: https://github.com/atom/atom/issues/6231

**Comment by izuzak** [comment]
Similar copy/paste problems reported in https://github.com/atom/atom/issues/6251 as well.

**Comment by izuzak** [comment]
There's a lot of feedback about this in this other issue as well: https://github.com/atom/atom/issues/6237

**Comment by Kuzirashi** [comment]
On Ubuntu 15.04 there is no difference. Copying/pasting from Atom to Chrome and right clicking freezes chrome for XX seconds(only mouse working, but cursor icon is stuck) and no reaction to user actions. It makes Atom almost unusable on Linux for me combined with pasting to Atom crashing it.

**Comment by ostapiuk** [comment]
Same problem here with Xubuntu 14.04.2 LTS using Atom 0.189.0.  
Copy from Atom and nothing gets into clipboard.  Trying to paste causes any application to "pause" for a moment but noting is pasted.  I tried pasting into Firefox and gEdit.  The Paste menu item of the other applications is grayed out.
Pasting into Atom from gEdit caused it to crash (window closes).  After restarting I was able to paste just fine, but copy is still broken.
Since the crash, my system is a bit sluggish.  A quick glance at the system monitor shows the crashed instance of Atom is still running along with the new instance.

**Comment by arist0tl3** [comment]
The only time I experienced crashes was when pasting into Atom from an external program (Firefox). Both Ctrl-V and using right click to paste triggered the crash.

(Chr)Ubuntu 14.04 LTS using Atom 0.189.0.

Downgrading to 0.188.0 seems to have fixed the issue.

**Comment by gabriel-tessier** [comment]
+1 crash after paste experienced text from Atom, text from outside Atom (Firefox, Mail client etc...).
Kubuntu 14.10
Atom 0.189.0
Is there a link or a How To to perform a downgrade to 0.188.0
There's not only this problem and this version is really buggy can't work properly! 

Thanks, hope you can release quickly!

**Comment by jacobmischka** [comment]
Thank you @zcbenz!

**Comment by andya9** [comment]
Thank’you very much @zcbenz

**Comment by Koltharius** [comment]
@zcbenz is this the path /usr/share/atom/resources/app/src?

**Comment by pmros** [comment]
Thank you @zcbenz! 
I hope Atom 0.190 will be released soon!

**Comment by slang800** [comment]
Just built it manually and I can confirm that this fixes it on Ubuntu. Thanks @zcbenz!

**Comment by kevinsawicki** [comment]
> I hope Atom 0.190 will be released soon!

0.190 is out now

**Comment by didrocks** [comment]
Confirming that it's fixed with 0.190

**Comment by theblacklion** [comment]
Works fine now :)

**Comment by djhi** [comment]
Confirming it's fixed with 0.190 on Mint 17.1 cinnamon and kernel 4

**Comment by alexdor** [comment]
Confirming it's fixed with 0.190.0 on Ubuntu 14.04.2 LTS 64-bit

**Comment by asiniy** [comment]
I still have the trooubles with ubuntu `14.04` and atom v `1.0.7`

After paste something from firefox (1-2 locs), sometimes atom freezes. After that I get modal `application is not responding. keep it waiting?`.

**Comment by siriust29** [comment]
I solved it with the Keybinding Resolver package. 
The problem was that the hydrogen package we have the keybinding ctrl+c also. 
Commented out the line ctrl+c by hydrogen keybinding.
