### ISSUE TITLE
After updating to Atom 0.190.0 I get following deprecation notification of Atom core

### ISSUE THREAD

**Issue by rukshn** [atom/atom#6310]
**After updating to Atom 0.190.0 I get the following 3 deprecation notices of Atom core.** Anyone else noticed this?

Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
Called 1 time
Package.activateConfig - /usr/share/atom/resources/app/src/package.js:250:11
Package.activateNow - /usr/share/atom/resources/app/src/package.js:221:14

--------------------------------------------------------------------------------------------------------------

Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:

  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
Called 1 time
Package.getActivationCommands - /usr/share/atom/resources/app/src/package.js:764:9
Package.hasActivationCommands - /usr/share/atom/resources/app/src/package.js:689:20

----------------------------------------------------------------------------------------------------------------
ContextMenuManager::add has changed to take a single object as its argument. Please see https://atom.io/docs/api/latest/ContextMenuManager for more info.
Called 1 time
ContextMenuManager.add - /usr/share/atom/resources/app/src/context-menu-manager.js:57:18
Package.activateResources - /usr/share/atom/resources/app/src/package.js:299:61

**Comment by izuzak** [comment]
This looks very similar to https://github.com/atom/atom/issues/6278. @kevinsawicki -- https://github.com/atom/atom/issues/6278 turned out to be a problem in two packages. Would it be possible to somehow not report these as Atom core problems, but rather package problems?

**Comment by rukshn** [comment]
@izuzak It's shown as deprecation notices for atom core, doesn't show as a problem with any packages. That's why reported it as an atom core problem because I couldn't find any packages that's causing the problem

**Comment by rukshn** [comment]
Starting Atom in safe mode generates only 2 error,

Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
Called 1 time
Package.activateConfig - /usr/share/atom/resources/app/src/package.js:250:11
Package.activateNow - /usr/share/atom/resources/app/src/package.js:221:14

----------------------------------------------------------------------

Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:

  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
Called 1 time
Package.getActivationCommands - /usr/share/atom/resources/app/src/package.js:764:9
Package.hasActivationCommands - /usr/share/atom/resources/app/src/package.js:689:20

**Comment by blairvanderhoof** [comment]
+1

**Comment by mnquintana** [comment]
@rukshn Have you tried starting Atom in [safe mode](https://atom.io/docs/v0.190.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)? I see the same deprecation warnings normally, but not in safe mode, which makes me think it's actually some user installed package(s) that's causing this, despite the deprecation warning text.

**Comment by rukshn** [comment]
@mnquintana Hi, yes the warnings are there in the safe mode also when i tried atom in safe mode.

**Comment by rabugento** [comment]
In my tests, this errors shows when installs "linter" and "linter-jshint" packages.
I compile atom with these packages included.

Anyone knows how to fix this error?

**Comment by mark-hahn** [comment]
You should post issues on the repos for those packages.

**Comment by rabugento** [comment]
<a href='https://github.com/mark-hahn'>mark-hahn</a>, I'll do this. Thanks.

**Comment by ttaranto** [comment]
+1

**Comment by idan** [comment]
Seeing the same deprecation warnings in 0.192, with slightly different line numbers:

![deprecation_cop_-__users_igazit_dropbox__personal__heroku_awsdetailedbilling_-_atom](https://cloud.githubusercontent.com/assets/22723/7227545/304f9e28-e75a-11e4-8568-561ef4f90934.jpg)

Also seeing a warning about using a configSchema in package.activateConfig.

Unlike OP, both of these warnings go away when I load with `--safe`. Going through my addons and trying to isolate which one is responsible.

**Comment by idan** [comment]
OK, it is caused by 3rd party packages:

- sublime-style-column-selection triggers the first deprecation error
- emmet triggers the second

Filing tickets on each.

**Comment by idan** [comment]
- Emmet: [https://github.com/emmetio/emmet-atom/issues/257]
- sublime-style-column-selection: [https://github.com/bigfive/atom-sublime-select/issues/42]
- linter-jshint: [https://github.com/AtomLinter/linter-jshint/issues/60]
- linter-jsonlint: [https://github.com/AtomLinter/linter-jsonlint/issues/8]
- redacted: [https://github.com/ymendel/atom-redacted/issues/2]

**Comment by mnquintana** [comment]
@izuzak Is this one resolved now with the recent changes in Grim?

**Comment by izuzak** [comment]
> @izuzak Is this one resolved now with the recent changes in Grim?

Not yet. There are a few different deprecations here that needed tweaking, and we've been fixing them one-by-one. For example, this isn't fixed/merge yet: https://github.com/atom/atom/issues/6522. After that's fixed, I plan on going through this issue one more time to make sure we didn't miss anything. I'll close the issue once that's done.

**Comment by izuzak** [comment]
Thanks for all the reports, everyone! :sparkles: The way deprecated calls were being detected and reported needed some tweaking for specific calls. We've been doing that over the last week and I think we've handled all the incorrect attributions mentioned in this issue (e.g. see https://github.com/atom/atom/issues/6510, https://github.com/atom/atom/issues/6522, https://github.com/atom/grim/pull/5). 

These changes will be shipped with the next release of Atom (or right now if you're building from source). If you notice any other incorrect attributions in Deprecation Cop in Atom 0.195.0 (when it's released) -- please open a new issue here, or even better at https://github.com/atom/deprecation-cop. :bow:

**Comment by lgomez** [comment]
+1 Just reporting that the warning goes away when disabling https://atom.io/packages/atom-alignment @Freyskeyd
