### ISSUE TITLE
Install from source on linux creates desktop entry with wrong icon location

### ISSUE THREAD

**Issue by firstdoit** [atom/atom#6523]
When installing from source by following [this guide](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) the following `.desktop` entry is created in `/usr/local/share/applications/atom.desktop`:

```
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century.
GenericName=Text Editor
Exec=/usr/local/share/atom/atom %U
Icon=/usr/local/share/atom/resources/app/resources/atom.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
```

However, `/usr/local/share/atom/resources/app/resources/atom.png` does not exist.

```
$ ls /usr/local/share/atom/resources/app/
apm  atom.sh
```

I solved it by simply copying the atom icon in `atom/resources/atom.png` over to the expected path.

```
cd atom
sudo cp --parents resources/atom.png /usr/local/share/atom/resources/app/
```

I didn't find this bug last week when installing release 0.192.0. Maybe this was introduced on 0.193.0 because of the `asar` archive file.

**Comment by 50Wliu** [comment]
It doesn't exist for me either but Icon is just `atom.png` for me (possibly because I was using the Webupd8 PPA before building from source).  Launcher icon is still definitely Atom though...

**Comment by keirlawson** [comment]
This seems to also be an issue with Fedora builds

**Comment by shingonoide** [comment]
I can confirm this bug here, build from source on Arch Linux.

**Comment by jbt** [comment]
This appears to be fixed for me, as of 2893772d1a5df8b6ea394e14ebb8eab637cb731b

**Comment by mnquintana** [comment]
Yup, this has been fixed with https://github.com/atom/atom/pull/7170 – thanks!

**Comment by hickscorp** [comment]
I'm still having this issue on Ubuntu 17.10, using the package from the Github releases.
Super annoying when alt-tabbing a lot, as Atom becomes distinguishable from some other apps with the same problem.
