### ISSUE TITLE
Ctrl-O should open the file chooser in the current directory

### ISSUE THREAD

**Issue by olsonpm** [atom/atom#6762]
This is exactly the same issue as #3618 .  I'm re-submitting an issue because the old fix does not work anymore as a result of AtomWindow.projectPath no longer existing (assumed to be the result of #770 where multiple project paths are now supported.

I was unable to figure out how to get console.log statements or errors reported to the dev console.  If someone can shed some light on how to get that working, then I can submit a PR.

**Comment by MadLittleMods** [comment]
This also happens in Mac OSX. I would prefer to "open the currently open file's folder as default."

**Comment by sneakypete81** [comment]
@olsonpm: The title of this bug is too specific:
 * The correct behaviour is to open in the directory of the currently open file
 * Mac OSX and Windows are affected too

Can you please update the title to something like:
"Ctrl-O should open the file chooser in the current directory".

As the original report in #3618 stated:
> Using keyboard shortcut ctrl-o in Ubuntu launches open file dialog with "Recently used" as default
> folder. The default in basically all other apps (including Sublime Text) is to open the currently open 
> file's folder as default.
>
> Yes, the tree view is there to quickly open files from current directory, but breaking convention is 
> bad.

**Comment by afandria** [comment]
I agree. Please fix Ctrl+O. I am having a very hard time with Atom's current behavior.

**Comment by olsonpm** [comment]
@sneakypete81 - I kept the title the same in order to keep it consistent with the original issue.  Changing the title assumes something different is occurring - I would like to keep it the same for that purpose.

**Comment by monocasual** [comment]
Confirmed also in Ubuntu 14.04 with Atom 1.2.2.

**Comment by kleinbottle** [comment]
I am a new atom-editor user who was previously using KDE's kate and kile. I am on Netrunner Rolling Release 2015-09, which is a derivative of Manjaro Linux, and ultimately Arch. The version of atom editor is 1.2.4.

Ctrl-O gives me "Recently Used" as reported here. What is worse, some of recent those files are PDFs, not intended for editing. 

Is there an installable package that allows circumventing this problem as quick workaround?

**Comment by olsonpm** [comment]
@kleinbottle - if you find one please let me know.

The workaround I've been using is to utilize a different workflow.  I'm now accustomed to opening 'projects' (for which there are many plugins depending on how you want to manage those).  Within an open project, the fuzzy finder works very well - and there's even an "open buffer fuzzy finder" which  searches the files that you currently have open.

The above workflow doesn't work well for one-off files unfortunately - for which I use the tree view or the command line.

**Comment by lalomartins** [comment]
@olsonpm there are still times when I want to use something like the file picker even within a project, especially for large projects and/or projects with similar filenames (e.g. I have a file “card.coffee” on client, one on server, one on models, plus “card.jade” on client).

The workaround I've been using for that is advanced-open-file, but it's not quite good enough.

**Comment by lalomartins** [comment]
I guess mainly I dislike the tree view? :-)

**Comment by olsonpm** [comment]
@lalomartins - Of course is natural to open your OS's file explorer and find a file via the behavior you're used to.  Either most people are used to opening up the recent file list, or they just aren't using the file explorer.

Thanks for mentioning advanced-oopen-file.  I'll have to take a look

**Comment by kleinbottle** [comment]
Thanks for suggesting advanced-open-file @lalomartins.

As @olsonpm has put it, I so much like the file selector in KDE where the "Recently Used" option was not pre-selected and so did not intrude in the way I work. I wonder why something so customizable as atom-editor does not have an option for this default behaviour.

**Comment by stilliard** [comment]
Any updates on this? :)

**Comment by olsonpm** [comment]
@stilliard It's likely safe to say this problem doesn't impact enough people to warrant development time against - unless you have the time to do it yourself.

**Comment by stilliard** [comment]
Thanks @olsonpm

**Comment by lalomartins** [comment]
I'm sorry @olsonpm, and I'm more than happy to try my hand at a patch, but — how the blazes does this doesn't impact enough people? “Safe to say” even? Basically, ctrl-O is broken to the point of uselessness. If you think not enough people use `application:open-file`, take it off the menu and rebind the keys to something that works.

It's extra useless because Atom also doesn't do whatever needs to be done for files to appear on Recent — so what you get there is pretty much never what you want.

**Comment by lalomartins** [comment]
Hmm sorry, you're the reporter and you're saying what you observed, not a developer expressing a project view. I'll shut up and wait for an “official” answer then.

**Comment by lalomartins** [comment]
Hmm sorry, you're the reporter and you're saying what you observed, not a developer expressing a project view. I'll shut up and wait for an “official” answer then.

BTW, this needs the “linux” flag removed, and maybe the title rewritten. Maybe taking the Debian reference off would attract more attention?

**Comment by olsonpm** [comment]
@lalomartins haha - not a problem.  We're not in agreement over whether this impacts enough people.  We can only assume the number of people this negatively effects are the number of people who comment on this thread which is a single digit.

I haven't used application:open-file to notice its broken behavior, but I'll trust you're right on that.

I changed the title to what @sneakypete81 suggested.  Due to the issue being the same, I wanted to keep the title consistent.  Since it is not linux specific however I agree you and him are correct.  My bad on that.

**Comment by lalomartins** [comment]
`application:open-file` is the internal command ctrl-o (or cmd-o) is bound to :smiley_cat: sorry if that confused things, I wanted to be unambiguous and include linux, win, mac keybindings plus the menu File → Open

**Comment by olsonpm** [comment]
Nah I got that - and I used it for the same purpose :)

**Comment by afandria** [comment]
I suspect the problem is here (and yes, I still want this to be fixed).

https://github.com/atom/atom/blob/ec66a66bb3c4be92b01f861e210f429e4737da7b/src/browser/atom-application.coffee#L612

It's possible that we're unable to set the default path on linux, despite trying this: 
```
    if process.platform is 'linux'
      if projectPath = @lastFocusedWindow?.projectPath
        openOptions.defaultPath = projectPath
```

It does not even try to set the default path for `darwin`.

It's also possible that the implementation of `dialog.showOpenDialog` ignores the `defaultPath` part of its options.

**Comment by lalomartins** [comment]
Anyway opening in the project dir was a work-around, the correct behaviour is the dir where the current file is

**Comment by stilliard** [comment]
I've tested with a starter electron app and dialog.showOpenDialog defiantly works with defaultPath, so no issue in the core electron at least (unless fixed more recently). 
Also It looks like the save dialog works, so maybe comparing the open to save dialog code will help.

**Comment by afandria** [comment]
Yeah, Ctrl+Shift+S does work.

The Linux menu items are here: https://github.com/atom/atom/blob/dd1eb750fe95e4ab9bfeef294d98d1e738620102/menus/linux.cson
These commands (regardless of system) seem to be routed through here:
https://github.com/atom/atom/blob/38d6ded9c45bacfc0f5145e576468d3dbfddcbcb/src/register-default-commands.coffee

We can see the difference between `core:save-as` and `application:open-file` is that the former is handled by the model as `@getModel().saveActivePaneItemAs()` while the latter is handled separately by the application `ipc.send('command', 'application:open-file')` as seen in https://github.com/atom/atom/blob/ec66a66bb3c4be92b01f861e210f429e4737da7b/src/browser/atom-application.coffee#L172

* Definition of saveActivePaneItemAs: https://github.com/atom/atom/blob/28517563ebb6a73da1e7b03d1c7fe36ae8d0e611/src/workspace.coffee#L637
* Pane (and Item) spec: https://github.com/atom/atom/blob/db74f4a8f0656411ce39d51b05e465c990061301/spec/pane-spec.coffee

I do not know CoffeeScript, but unless I'm mistaken, we can get the default path from this:
`@getModel().getActivePane().getActiveItem().path`

We may need a few `?` if some of those things don't exist at runtime.

**Comment by afandria** [comment]
I think what I've proposed has a good chance of working. While I could make a pull request, I don't know how I would test it. Can someone with experience building Atom give this a try?

**Comment by olsonpm** [comment]
I just checked the build steps - seems pretty minimal.  If you make the changes and host it on a fork, I'll pull -> build -> test your fix.

**Comment by afandria** [comment]
Thanks, that sounds good to me! I'll let you know when I'm ready.

**Comment by afandria** [comment]
If I've done it correctly, you can see it here: https://github.com/afandria/atom/commits/patch-1 (afandria/atom on branch patch-1)

**Comment by olsonpm** [comment]
Alright.  I'll have time this weekend - aiming for saturday afternoon.  I'll get back to you Sunday at the latest.

**Comment by afandria** [comment]
Thanks, looking forward to it!

**Comment by olsonpm** [comment]
Quick update - nothing happens when I run this.  No console errors, no dialog, nothin.  I tested this against atom's master which does prompt as expected.  I'm looking into it myself now.  Unfortunately the build process takes a while on the vm I spun up.  This is new territory for me though - I may not be debugging efficiently.

**Comment by olsonpm** [comment]
Well I'm giving up again for the same reason I did last time.  I write console.log/error statements, I know I'm running through those log statements, but no output is shown in the dev console.

**Comment by mnquintana** [comment]
@olsonpm Are you running Atom in dev mode when you test those log statements? Where did you clone the Atom project?

**Comment by olsonpm** [comment]
No - from what I ready about dev mode, its use is mainly to prevent the need for `window: reload` after package changes.  And the location for where I cloned the repo doesn't matter.  Initially I was building->installing atom within a clean debian 8.2 vm.  After becoming familiar with the process, I started doing it on my personal laptop (also debian 8.2) attempting to avoid any vm performance penalties.

**Comment by jrkoenig** [comment]
@olsonpm The code in `src/browser/atom-application.coffee` runs in the browser process. The inspector only sees the render process. Stuff like this that interacts with the OS happens in the browser process. You can run atom with the flags `-fw` to see this output.

**Comment by olsonpm** [comment]
@jrkoenig - Thanks much, that makes sense.  I'll give it a shot this weekend.

**Comment by olsonpm** [comment]
Thanks so much @jrkoenig.  I'll test your PR when I get a chance.

**Comment by delliott2016** [comment]
@afandria The bug fix you posted all those days ago did not work, I'm sorry to say, due to `@getModel()` not being available _anywhere_ in browser files. Though your idea was spot-on.

I've been working on this a bit myself with a small group of people and have a few questions, but the most important is simply: why is the open-file code contained within the browser process? I can understand that area having the code for opening all the files on start, since they have to initialize and populate everything, but I don't understand why this single function is there also. Why isn't it next to the save function in `workspace.coffee`? Perhaps I just don't understand what the code within the folder title "browser" does, or the way opening files works in Electron though.

In any case, no reference to model or workspace is available in any files in the "browser" folder of Atom as far as I can tell, so there doesn't yet seem to be a chance of ever getting the active project (and the associated path) in order to resolve this bug by setting the default path. We've actually tried passing the model along through IPC, but that hasn't had much luck either. If anyone is still interested in this, information would be greatly appreciated.

**Comment by lalomartins** [comment]
I typed this long-ish text, then I read a few messages back and I noticed there's already a PR, so my post is obsolete.

I'm going to post it anyway, in case there's a problem with getting the PR merged, but as it is consider it a message from an alternate universe or something.

> 2¢ — if this is a huge project, it might be worth it as a temporary fix to open the file chooser in the direction it was last. So, whenever you select a file using the chooser, store the location as state somewhere, then next time start in the same place, if available. It would already be a lot less annoying, I believe, and that's what browsers do with the “save as” dialogue.
> 
> Alternatively, figure out how to interact with the various OSes “recent” list, so when it opens in that view, it will at least contain the last place(s) where you opened a file.

**Comment by delliott2016** [comment]
@lalomartins Those are pretty good ideas. I might accept the first one myself (saving the location as state somewhere and then just going back to it each time). That behavior almost seems better to me than the "correct" behavior of opening in the current directory. Do you think a fix that does that would be accepted?

And as for the PR that's been out for a while now, that one most likely will not pass. I actually get an error when I try to run it.

**Comment by lalomartins** [comment]
I would accept it, at least ;-)

**Comment by afandria** [comment]
@delliott2016: Thanks for trying it out. It's too bad it didn't work. :(

**Comment by delliott2016** [comment]
@lalomartins Good enough for me. ;)

@afandria No problem. It looks like this particular code is just in the wrong place. Anywhere else -- literally almost anywhere -- and your fix would have worked.

**Comment by lee-dohm** [comment]
Fixed in #11618, thanks to the hard work of @delliott2016.

**Comment by afandria** [comment]
@delliott2016 Thank you!

**Comment by delliott2016** [comment]
@afandria You are most welcome. It was only possible thanks to your research and hard work as well!

**Comment by Telofy** [comment]
This sounds like the problem is long resolved. Or is it an optional setting that needs to be activated somewhere? Because I’m using Atom 1.8.0 on Linux and have run into the same problem.

**Comment by 50Wliu** [comment]
@Telofy it should be fixed starting in Atom 1.9.0.

**Comment by jrial** [comment]
Still not fixed for "add project folder" though. But yes, ctrl-o works fine. Testing on 1.12.3

**Comment by 50Wliu** [comment]
@jrial Can you please create a new issue?

**Comment by JavaScriptDude** [comment]
Thanks for this fix! This was a huge pet peeve of mine.
