### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by adi-altiscale** [atom/atom#6831]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:128

TypeError: Cannot read property 'split' of undefined
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:435:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:729:31
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:771:29
    at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:119:18)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:647:27)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:765:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1950:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1924:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:763:19)
```
### Commands

```
     -0:57.4.0 time:insert (atom-text-editor.editor.is-focused)
  2x -0:51.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:49.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:40.5.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:39.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35.5.0 time:insert (atom-text-editor.editor.is-focused)
  2x -0:05.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:04.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.5.0 time:insert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/adi/Workspace"
  },
  "editor": {
    "invisibles": {},
    "fontSize": 32,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
saveallthetime, v0.1.1
time, v1.0.0
time-status, v1.1.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @adi-altiscale, what were you doing when this error occured?  If you know how to reproduce it, could you please try in safe mode (`atom --safe`)?  Thanks!

**Comment by Zireael07** [comment]
I got what looks like the same error after I used find and replace via Search in Directory, and then tried to Search in Directory in another directory immediately afterwards.

**Comment by pedzed** [comment]
I can confirm this issue, but I think it is rare. I am not sure how to reproduce.

**Comment by Ben3eeE** [comment]
@pedzed It would be great if you could include all the information from the exception when confirming, thanks.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/6831#issuecomment-103079637. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by RachelScodes** [comment]
I got this same issue when trying to insert a comment via keyboard shortcut (command - '/') on a .slim file. I also have wakatime, and the onedark themes installed. no other overlaps.

**Comment by Ben3eeE** [comment]
@RachelScodes The issue you are having should be fixed in Atom 1.13 currently in beta.

**Comment by sllewellyn13** [comment]
Still broken, I am getting the error with the sample usage code provided.
