### ISSUE TITLE
0.209.0 doesn't save session

### ISSUE THREAD

**Issue by solbjorn** [atom/atom#7231]
Atom 0.209.0 doesn't save open files and folders on exit (0.208.0 made this). After restart, there is only empty "untitled" file.
Here's my config:
```cson
"*":
  "exception-reporting":
    userId: "480b20de-e736-263e-a240-4205e8c90e87"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "one-dark-ui"
      "solarized-dark-syntax"
    ]
  editor:
    fontFamily: "'M+ 1mn regular'"
    invisibles: {}
  minimap:
    plugins:
      "git-diff": true
      bookmarks: true
      selection: true
      "color-highlight": true
      "find-and-replace": true
  "atom-beautify":
    _analyticsUserId: "13adc827-7ceb-4c02-bdb7-7a6d1b173567"
    c_configPath: "/usr/share/uncrustify/defaults.cfg"
    cpp_configPath: "/usr/share/uncrustify/defaults.cfg"
    cs_configPath: "/usr/share/uncrustify/defaults.cfg"
    objectivec_configPath: "/usr/share/uncrustify/defaults.cfg"
    java_configPath: "/usr/share/uncrustify/defaults.cfg"
  tabs:
    usePreviewTabs: true
  linter: {}
  "git-plus":
    wordDiff: false
  "merge-conflicts": {}
  "linter-clang":
    clangDefaultCFlags: "-Wall -Wextra -std=c99"
    clangDefaultCppFlags: "-Wall -Wextra -std=c++11"
  "atom-color-highlight": {}
  "autocomplete-clang": {}
  "open-recent": {}
```
0.209.0 built from sources.

**Comment by mnquintana** [comment]
Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce this in safe mode? (`atom --safe`)

Also, did this just happen after you Installed and Restarted Atom immediately after updating to 0.209.0? Or does this happen consistently every time you load a project, quit, and reopen Atom?

**Comment by solbjorn** [comment]
Yes, followed. This happens in safe mode too. Every time i close and reopen it. On first launch after upgrade to 0.209, Atom had restored session, but now it doesn't.

**Comment by mnquintana** [comment]
Can you try deleting Atom's storage folder? (Settings > Open Config Folder > delete `storage`) Then, restart Atom, open a project, open some files, quit, and see if you can reproduce this.

Also, what OS are you on?

**Comment by solbjorn** [comment]
Arch Linux x64.
OK, I'll try tomorrow, I forgot to test it with empty config folder.

**Comment by almostearthling** [comment]
Same here: it happens both in normal and in `--safe` mode. Removing the `~/atom/storage` folder does not solve the problem (again both in normal and in safe mode). Version is 0.209.0, host PC is Ubuntu 14.04 (although I wouldn't think of a particular distro problem).

F.

**Comment by skulden13** [comment]
Hello!
I have same issue. 
Deleting Atom's storage folder didn't help.

OS -- Ubuntu 14.04 x64.
Atom -- 0.209.
Custom packages for atom: color picker, emmet, git-plus, save-session.

Thanks

**Comment by maxbrunsfeld** [comment]
I think 0.203 was the last release in which the logic for saving the windows state changed. Trying to reproduce on Ubuntu...

**Comment by maxbrunsfeld** [comment]
I can't reproduce this on Atom 0.209. How are you exiting Atom? Can you report the contents of `~/.atom/storage/application.json` before and after exiting Atom?

**Comment by andersea** [comment]
Hi, also seeing this.

OS - Windows 7
Atom 0.209
Packages: autoclose-html, esformatter, language-ejs, pretty-json, react

Contents of C:\Users\Anders\.atom\storage\application.json (while open)

    [{"initialPaths":["X:\\NodeJS\\alt-tutorial-master"]}]

Contents after closing atom:

    []

**Comment by almostearthling** [comment]
On Ubuntu 14.04:

After closing Atom 0.208, ~/.atom/storage/application.json:
`[{"initialPaths":["/home/franz/Projects/Unmanaged/When"]}]`

After installing and starting Atom 0.209 (when still running, it loaded the windows initially), same file:
`[{"initialPaths":["/home/franz/Projects/Unmanaged/When"]}]`

After closing Atom 0.209 (same session), same file:
`[]`

Since it happens on close, it's unfortunately difficult to se a stack trace or something similar. I couldn't even try to log anything, however starting Atom 0.209 on the foreground in dev mode produces the following output:

```
franz@boris:~$ atom -d -f
[7364:0612/000906:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 1294ms
[7364:0612/000912:INFO:CONSOLE(15)] "activate linter-csslint", source: /home/franz/.atom/packages/linter-csslint/lib/init.coffee (15)
[7364:0612/000912:INFO:CONSOLE(20)] "activate linter-jshint", source: /home/franz/.atom/packages/linter-jshint/lib/init.coffee (20)
[7364:0612/000912:INFO:CONSOLE(19)] "activate linter-pep8", source: /home/franz/.atom/packages/linter-pep8/lib/init.coffee (19)
[7364:0612/000912:INFO:CONSOLE(11)] "activate linter-tidy", source: /home/franz/.atom/packages/linter-tidy/lib/init.coffee (11)
[7364:0612/000912:INFO:CONSOLE(17)] "activate linter-tslint", source: /home/franz/.atom/packages/linter-tslint/lib/init.coffee (17)
[7364:0612/000914:INFO:CONSOLE(56)] "Window load time: 6002ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (56)
[7364:0612/001009:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

Since the problem doesn't change in safe mode I didn't try to get a log using `--safe`. I'll switch back to 0.208 for now... go on with the great job! ;-)

F.

**Comment by xlaywan** [comment]
+1 win 10, atom 0.209

**Comment by almostearthling** [comment]
> Also, did this just happen after you Installed and Restarted Atom immediately after updating to 0.209.0? Or does this happen consistently every time you load a project, quit, and reopen Atom?

It happens consistently in 0.209: even if I add one or more project folders to the empty workspace and open one or more files, when I leave Atom and restart it the result is the same.

F.

**Comment by JohnMurga** [comment]
+1 on Win 8.1 64bit 209
More info : Happens with initial empty workspace window (when invoking Atom without parameters)
When invoking Atom with a directory name it seems to work (save and restore)

**Comment by joannadal** [comment]
Just now I fixed the problem in Ubuntu 14.04. You need to reinstall Atom.

- First steep:
sudo apt-get purge atom

- Second steep:
sudo rm -R /home/username/.atom

- Third steep:
sudo apt-get install atom (If you added the repository) or install again the .deb package.

**Comment by andersea** [comment]
I tried something similar on Windows, but it didn't work. I uninstalled. Deleted /Users/Anders/.atom, %AppData%/Local/atom and %AppData%/Roaming/atom, then reinstalled.

Didn't change anything.

**Comment by solbjorn** [comment]
It also would be nice if Atom could also restore session if launched with file or directory arguments (i mentioned it in #7186)

**Comment by barwinco** [comment]
+**1**
```
~/ → atom --version
0.209.0
~/ → apm --version
apm  0.171.0
npm  2.5.1
node 0.10.35
python 3.4.2
git 2.4.3
```
Gentoo Linux

**Comment by JohnMurga** [comment]
It appears that the application state while it's running is correct, it just gets cleared on exit ...
So I am hoping that recent commits by @maxbrunsfeld will fix this in the next release :-)

**Comment by Zireael07** [comment]
Same here, Win 7 x64, atom 0.209.0.

**Comment by JohnMurga** [comment]
This may be worth double checking by other on this thread ...
I kill Atom instead of exiting normally, the session is preserved and restored when I next start it.

**Comment by fonorobert** [comment]
Same here, when I exit with `killall` the session is preserved, but when I exit normally it isn't.

Ubuntu 14.10, atom 0.209.0

**Comment by ksprwhite** [comment]
**+1**

I have same issue,

Ubuntu-gnome 64 bits, atom v0.209.0

**Comment by fifovillage** [comment]
same problem, windows 7 ultimate 64bit atom v0.209.0
no problem with ubuntu 14.04

**Comment by shuriktm** [comment]
Same problem for me on Windows 8.1 in Atom v0.209.0.
Atom v0.208.0 worked properly.

**Comment by jlbooker** [comment]
+1 on Fedora 20, Atom version 0.209.0 (Installed via RPM package from the atom.io site)

Tried launching with atom and atom --safe. Neither remembers the project folders and open files from the last execution.

And worse, it seems the save-session package no longer implements this feature. It expects the core functionality to support this instead. So frustrating.

**Comment by 50Wliu** [comment]
@jlbooker, sorry for your frustration.  This has been fixed in 0.210.0 (which hasn't been released yet, but it should soon).

**Comment by quasipedia** [comment]
+1 on Fedora 22 64bit, Atom version 0.209.0 (Installed via RPM package from the atom.io site)

**Comment by goroskob** [comment]
Same on Ubuntu 15.04, Atom 0.209.0. Updated to it today from 0.204, where session saving worked good.

**Comment by maxbrunsfeld** [comment]
Atom 0.210 is out. Could everyone please upgrade and check that this problem is resolved? Thanks everyone. I'm sorry this feature has already had so many problems for the short time that it has existed.

**Comment by fonorobert** [comment]
works on ubuntu 14.10 x64 atom 0.210

**Comment by nickfmc** [comment]
Windows 8.1 atom 0.210 issue remains for me :(

**Comment by nadeemabd** [comment]
Works on windows 8.1 atom 0.210.

**Comment by onetrev** [comment]
I'm on Windows 8.1, Atom 0.210, I still have this issue. Session is completely lost on restart. Atom reopens with a blank slate, no session data, last project needs to be re-opened and all previously open files need to be re-opened.

**Comment by Malcolm** [comment]
Issue is resolved for me on Windows 8.1; File->Exit, ALT+F4 and window chrome X all work as expected on my system.

**Comment by solbjorn** [comment]
Fixed now for me, 0.210.0 built from sources, Arch Linux x64. Session properly saves and restores.

**Comment by ronjouch** [comment]
Fixed for me with 0.210.0 official deb under Ubuntu Linux 15.04 x64

**Comment by dovrosenberg** [comment]
+! to @nickfmc. Had to close once after upgrade to 0.210.0 and reopen before it started working - no big deal, just something for folks to be aware of so they don't assume it's still broken.

**Comment by andersea** [comment]
Fixed for me on Windows 7.

**Comment by denysdovhan** [comment]
Me too.
On ElementaryOS Freya (based on Ubuntu 14.10) has no problem.
Thanks! You're awesome!

**Comment by jlbooker** [comment]
Confirmed fixed for me as well.Thanks @50Wliu !

**Comment by wanghaisheng** [comment]
mac  10.10.4 
atom 1.0.2  still not working
any fix?

**Comment by maxbrunsfeld** [comment]
@wanghaisheng It seems like this feature works in most people's environments. Can you open a separate issue describing exactly how you're shutting Atom down and restarting it, and what you're seeing? Thanks.

**Comment by wanghaisheng** [comment]
@maxbrunsfeld   ok
