### ISSUE TITLE
atom 1.0.3 inserts superfluous characters

### ISSUE THREAD

**Issue by k5e** [atom/atom#8135]
I use a German keyboard and the package [keyboard-localization](https://atom.io/packages/keyboard-localization).
Today I updated atom to 1.0.3. Since then it inserts superfluous characters:

I type | I get
-------|-------
  " |  "@" 
 ' | '?'
 . | ..
 , | ,,
 - | --
 ( | (*) 
 # | #/ 
 + | +=
 * | *+
 ) | )() 
 ? | ?{}
 ß | ß[]

Most other non-alphanum characters are doubled. 

If I disable keyboard-localization I cannot type several characters like "\" in atom at all. Either way atom is unusable.

**Comment by Hejado** [comment]
Same here. Is this something I can quickfix in the keymapping myself, while waiting for an official fix? I'm going mad at least twice for each line of code I have to write right now... :(

**Comment by BlaM** [comment]
This needs a quick fix! Please.

Atom urgently need some kind of "test before release" mechanism now that it is beyond version 1.x.x

**Comment by k5e** [comment]
Well, the best solution would be if atom would behave well with non-US keyboards right from the box.

**Comment by Hejado** [comment]
That's a pity... Is there any way to downgrade atom?

**Comment by BlaM** [comment]
I just did that: Delete all subdirectories in my ~/.atom directory besides packages (which are the addons I installed) and delete ~/AppData/Local/atom.

Then download and install Atom 1.0.2 from https://github.com/atom/atom/releases

However: It has already started to download the update, again... So I need to be careful to not restart the editor until this is fixed.

**Comment by izuzak** [comment]
Thanks for the reports, everyone, and sorry to hear this is causing problems. The core Atom team is in the US so they'll be able to look into this a bit later today. 

cc @nathansobo @atom/core for :eyes:

**Comment by batjko** [comment]
I assume disabling the localization package you mentioned is not an option here, even just as a temporary workaround?

You can try that by starting atom in safe mode (`atom --safe`).

**Comment by andischerer** [comment]
actually my plugin in combination with the code changes from atom version 1.0.3 is causing the problem. I'm looking into this right now.

@BlaM there is no need for uninstalling and reinstalling atom for a downgrade. The old versions still exists in `AppData\Local\atom\app-1.0.2` folder

**Comment by k5e** [comment]
@batjko, no, that is not an option, because without keyboard-localization you cannot enter backslashes or @ signs in atom.

**Comment by BlaM** [comment]
@batjko: Many important keys won't work without that localization package. We can't use - for example - "@", "|", "{" or "}" without that addon

@andischerer: In that directory I had several 0.2xx.x versions and 1.0.3 - but no earlier 1.0.x version.

**Comment by batjko** [comment]
Understood regarding missing chars. I am keenly aware of the international keyboard issues, but I wasn't sure if there were any other workarounds people employed for this.

@BlaM The auto-updater gets rid of older versions (although very inconsistently). But as far as I know, it should retain the most recent version before the update in either case. 
Were you on 1.0.2 before?

**Comment by BlaM** [comment]
@batjko Yes, I upgraded from 1.0.2. I still had 1.0.2 this morning when I triggered the update to 1.0.3

**Comment by andischerer** [comment]
Should be fixed with atom-keyboard-localization@1.4.4

**Comment by Hejado** [comment]
Can confirm. Awesome, thanks!

**Comment by slhck** [comment]
It's not quite fixed for de_DE keyboards, even with the updated plugin, but I would agree with the previous comment that says:

> Well, the best solution would be if atom would behave well with non-US keyboards right from the box.

That's a different and more general issue though, so I think this issue here can be closed and @andischerer will probably deal with it in the localization package.

**Comment by Hejado** [comment]
Okay, the superfluous characters are gone, but the default actions are now back. For example: Hitting \ collapses the tree...

**Comment by BlaM** [comment]
There is another update to atom-keyboard-localization 1.4.5 which fixes this problem.

I guess: Feel free to close this issue. Bugfix is available.

**Comment by batjko** [comment]
@andischerer Thanks for stepping up so quickly!

Guys, I think this issue has now moved over to that package. Any further problems of this kind should probably be opened there (referencing this one).

**Comment by k5e** [comment]
@batjko, @BlaM, yes, I tend to close this.
And :+1: to @andischerer!

**Comment by nathansobo** [comment]
We're waiting on fixes to Chromium that are in progress and should hopefully resolve all the hassle on non-U.S. layouts. In the meantime, thanks @andischerer for the quick response on fixing you package. :heart:

**Comment by andischerer** [comment]
thanks for an awesome editor :thumbsup:
