### ISSUE TITLE
Atom does not recognize git worktree repositories

### ISSUE THREAD

**Issue by snaury** [atom/atom#8168]
When `git-repository-provider.coffee` searches for the git repository it looks for the `.git` directory, however `git worktree` creates repositories that have `.git` file that has `gitdir: path/to/gitdir` as contents. As a result atom cannot currently work with repositories created with `git worktree`. Unfortunately even making `.git` a symlink doesn't work, since worktree gitdir doesn't have `objects` or `refs` subdirectories.

Atom should recognize `.git` files that start with `gitdir:` as valid git repositories.

**Comment by phord** [comment]
@snaury I am interested in this bug and I'm working on a fix, but for me it primarily affects submodules.  I'm not sure what you mean about your symlink solution failing.  If you can provide a simple script to setup the failure condition, it would help ensure that is covered, too.

**Comment by phord** [comment]
@snaury Nevermind.  I see what you mean.  I didn't notice the new 'git worktree' command show recently.  The bug I was working on was only to fix the ".git-file" issue.   I think some more work needs to be done to support the new '.git/worktrees' arrangment.

**Comment by phord** [comment]
I do have a fix for the first half of this bug.  But the worktree problem (still marked "experimental" in git documentation) is not supported by libgit2 yet, and I don't have a working fix for that.

**Comment by fooishbar** [comment]
@phord libgit2 support is WIP: https://github.com/libgit2/libgit2/pull/3436

**Comment by rymohr** [comment]
Just ran into this one too. It hasn't been a showstopper for me but it does cause find-in-project to search across .gitignore'd files.

**Comment by sos4nt** [comment]
Any updates on this issue? I find `git worktree` quite useful and a proper support (editor wise) would be really nice.

**Comment by 50Wliu** [comment]
@sos4nt this issue is blocked until https://github.com/libgit2/libgit2/pull/3436 is merged.

**Comment by kriomant** [comment]
Worktree support in libgit2 just landed!

**Comment by 50Wliu** [comment]
Nice!  Now I think we'll need to wait for a new libgit2 release containing worktree support, update atom/git-utils to use that new version, and then update atom/atom to use the new git-utils version (phew).

**Comment by yao23** [comment]
I'm in top folder and it works only after save (cmd+s) the change, then it will show in git.

**Comment by pleonex** [comment]
FYI [libgit2 0.26.0](https://github.com/libgit2/libgit2/releases/tag/v0.26.0) with worktree support was released 3 days ago and there is already a pull request for git-utils: atom/git-utils#77 (related issue atom/git-utils#64)

**Comment by Arcanemagus** [comment]
Looks like this should be fixed by https://github.com/atom/atom/pull/16799, which was released in Atom v1.26.0-beta0 🎉.

**Comment by mortenpi** [comment]
Running v1.26.0, but a worktree directory is still not recognized as a repository. The only thing I could think of is that libgit2 installed through the repo is 0.24.1.. but Atom bundles it's own right? This is on Ubuntu 16.04 with Atom v1.26.0 installed from the official deb package.

**Comment by deepj** [comment]
I can confirm this. At least in my context, there is no diff highlighting of code. Visual Studio Code doesn't have a problem with this.

**Comment by Numblesix** [comment]
I can also confirm this issue still exists with version 1.32.2 running on a new Fedora29 installation.

**Comment by c-hartmann** [comment]
ATOM 1.44.0 (Linux with apt installed from official repos).  Project folder still not recognized right after an initial cloning from within atom from github repo.  **You still have to make any change to any file within and save this** ... THEN you get Login Button in the github tab/pane. Confusing.
