### ISSUE TITLE
Windows right-click context menu does not open multiple files in same window

### ISSUE THREAD

**Issue by kswem** [atom/atom#8222]
Hi, I just installed & used Atom for the first time and noticed a feature that is a must-have for me.

Repro steps:
1.) navigate to folder with multiple files
2.) select two or more files, then right-click and select "Open with Atom"
3.) Multiple windows of Atom opens, one window per file

Expected: only one window of Atom should open with one tab per selected file (just like Notepad++ and Sublime Text)

NOTE: I am using Atom 1.0.3 on Windows 7 Pro.

Thanks,
Keith

**Comment by damieng** [comment]
This has been fixed since it was filed.

**Comment by kswem** [comment]
In which build will this be fixed? I have 1.8.0-beta3 build and this issue
is not fixed.

**Comment by kswem** [comment]
I also installed build 1.7.3 and the issue is still not fixed there either.

**Comment by damieng** [comment]
I'm trying this on my machine and it is opening them in the same Window...
Let me check the code to see if there is something that might cause this
difference.

**Comment by damieng** [comment]
Ah, I misread the repro steps. If you open one file with the right mouse-button, then go and do the same on a second they open in the same window.

If however you multi-select a bunch of files and chose open they do not.

**Comment by kswem** [comment]
Yes, that's the same experience I get too.

**Comment by damieng** [comment]
One workaround that might work for you:

1. Navigate to `%appdata%\Roaming\Microsoft\Windows\SendTo` in Windows File Explorer
2. Right mouse button and chose 'New > Shortcut'
3. Chose the atom.cmd file in `%localappdata%\atom\bin\`
4. Change the name to 'Atom' and hit Finish

Now if you select multiple files you can chose 'Send To > Atom' from the context menu and they will open in a tab.

Enabling the regular 'Open in Atom' to load all in one hit requires interfacing with the Windows Shell (DDE or IDropTarget support) which is a non-trivial effort :(

**Comment by kswem** [comment]
Worked like a charm. Thank you Damien, you are a genius! :)

**Comment by damieng** [comment]
Given the workaround is good and we'll try and add 'Send To' automatically with the improved shell integration I'm going to go ahead and close this issue.
