### ISSUE TITLE
Can take up to 10s for initial window to appear

### ISSUE THREAD

**Issue by walles** [atom/atom#8918]
I'm using Atom 1.0.15 on OS X 10.10.4.

Sometimes when I start Atom from the command line as `atom .`, it is fast, as in that the initial window pops up inside of a second of me pressing return.

Sometimes, it takes about 10s from when I press return until the initial window pops up on screen.

I don't know how to repro this reliably, but my findings so far are that:
* This seems to happen when I already have an Atom running. First start of the process always seems fast.
* The launch can be slow even if the `mdfind` part of the `atom` shell script returns immediately, so it's not `mdfind`.
* I have a feeling the time until the window appears is *exactly* 10s when this happens, maybe something needs to time out for the startup to proceed?
* Running with `--profile-startup` doesn't show anything being slow; it seems like the profiling starts after the 10 seconds of inactivity.
* CPU load is (close to) zero during the 10 no-window seconds.
* For me this has been an issue since pre-1.0, so this is not a regression.

What can I do to figure out what Atom does between I press return and that the window appears?

**Comment by walles** [comment]
@50Wliu, if I want to track this down myself, since I can repro it (albeit intermittently), what would be a reasonable next step?

**Comment by benogle** [comment]
I see this too occasionally (but havent in a week or so). I dont know a good way to consistently reproduce. 

As far as digging in, make sure you are building from source and that you can reproduce from the current version of master. Then you need to narrow it down to a line or two of code. 

1. Figure out if it's happening in the renderer process or the browser process. It is likely in the browser process as the window doesnt show at all, but who knows
1. If it were me I would insert a bunch of log messages around the [code the opens a window](https://github.com/atom/atom/blob/7d2e32efb1c6375a4c42b112317b0b7eff8ef763/src/browser/atom-application.coffee#L372) and see where it's hanging

Once you have it narrowed down to a line or two of code, it will be a lot more likely someone will be able to dig into it.

**Comment by walles** [comment]
The built in logging gives me the below output from the server process during a slow startup.

The hang is before `Window load time` is printed, but after `Renderer process started`.
```
Okt 06 14:10:53 [47409:1006/141053:INFO:renderer_main.cc(200)] Renderer process started
Okt 06 14:11:04 [43827:1006/141104:INFO:CONSOLE(47)] "activate linter-eslint", source: /Users/walles/.atom/packages/linter-eslint/lib/linter-eslint.coffee (47)
Okt 06 14:11:04 [43827:1006/141104:INFO:CONSOLE(18)] "activate linter-htmlhint", source: /Users/walles/.atom/packages/linter-htmlhint/lib/init.coffee (18)
Okt 06 14:11:05 [43827:1006/141105:INFO:CONSOLE(46)] "Window load time: 1116ms", source: file:///Users/walles/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js (46)
```

**Comment by walles** [comment]
Now I actually managed to get a log message both from the "server" part and the "client" part.

Client (where I did `/tmp/AtomJohan.app/Contents/MacOS/Atom .`):
```
2015-10-06 15:41:06.617 Atom[50772:1266872] App load time: 153ms
```

Server (a process started earlier but with all windows closed, this is the where the actual on-screen window comes from IIUC):
```
2015-10-06 15:41:06.622 Atom[49717:1260253] Johan: In openPaths()
[49717:1006/154116:INFO:CONSOLE(2)] "Johan: Just started", source: file:///private/tmp/AtomJohan.app/Contents/Resources/app.asar/static/index.js (2)
[49717:1006/154117:INFO:CONSOLE(47)] "activate linter-eslint", source: /Users/walles/.atom/packages/linter-eslint/lib/linter-eslint.coffee (47)
[49717:1006/154117:INFO:CONSOLE(18)] "activate linter-htmlhint", source: /Users/walles/.atom/packages/linter-htmlhint/lib/init.coffee (18)
[49717:1006/154117:INFO:CONSOLE(48)] "Window load time: 1089ms", source: file:///private/tmp/AtomJohan.app/Contents/Resources/app.asar/static/index.js (48)
```

The `Just started` printout is on the second line of `static/index.js`.

The `In openPaths()` printout is in src/browser/atom-application.coffee as [you suggested above](https://github.com/atom/atom/blob/7d2e32efb1c6375a4c42b112317b0b7eff8ef763/src/browser/atom-application.coffee#L372).

**Comment by benogle** [comment]
So are you seeing on which line it hangs?

**Comment by walles** [comment]
@benogle, it's the call to `@browserWindow.loadUrl` in `atom-window.coffee`:
https://github.com/atom/atom/blob/7229d1a4295dd0fcb644b7c891a64e6836b2c3b2/src/browser/atom-window.coffee#L80

And it's that actual call, I've ruled out the calls to `@resourcePath` and `encodeURIComponent(JSON.stringify(loadSettings))` done as part of that call; those two are fast.

Not sure how to proceed from here; what's the easiest way to modify the Electron that's running underneath my home built Atom?

Also I have (admittedly not optimal) repro steps:
1. Start your server process, close its window.
2. Wait for 13 minutes. If your computer falls asleep during this time, it's fine.
3. Start a client process.

The 13 minutes number may need tweaking, what it really means is that on my system waiting 13 minutes help, but waiting a shorter amount could do the trick as well.

Almost every time I follow these steps I get a slow startup however.

**Comment by walles** [comment]
Also, I verified that `@browserWindow.loadUrl` can be either slow or fast with the same set of parameters:
```json
{  
   "locationsToOpen":[  
      {  
         "pathToOpen":"/Users/walles/src/merges",
         "initialLine":null,
         "initialColumn":null
      }
   ],
   "bootstrapScript":"/private/tmp/AtomJohan.app/Contents/Resources/app.asar/src/window-bootstrap.js",
   "resourcePath":"/private/tmp/AtomJohan.app/Contents/Resources/app.asar",
   "devMode":false,
   "safeMode":false,
   "profileStartup":false,
   "appVersion":"1.0.20-7229d1a",
   "initialPaths":[  
      "/Users/walles/src/merges"
   ]
}
```

**Comment by walles** [comment]
@benogle, @50Wliu, what would be the next steps for me if I'd like to continue tracking this down inside of Electron?

**Comment by benogle** [comment]
cc @zcbenz worth investigation? Could apply to other electron apps.

**Comment by walles** [comment]
@benogle, @zcbenz what would be the easiest way for me to tell Atom to use an Electron build of my choosing?

Building Electron shouldn't be a problem, but once I've done that, how can I get Atom to use my new build?

**Comment by benogle** [comment]
In the package.json. See this for more info: https://github.com/atom/atom/pull/9184/files

Also, beta-1.2.0 now uses 0.34.0. Is this still an issue?

**Comment by walles** [comment]
I still see this with Atom 1.2.4.

**Comment by walles** [comment]
It's this line that is slow in Electron:
https://github.com/atom/electron/blob/22e9c2f4ebbf3f4990afd27cea650cc652e0d1b8/atom/browser/api/atom_api_web_contents.cc#L624

```c++
  web_contents()->GetController().LoadURLWithParams(params);
```

So this is a Chromium problem.

**Comment by walles** [comment]
If we could programmatically tell Chromium to start collecting trace events...
https://www.chromium.org/developers/how-tos/trace-event-profiling-tool
... before we call `LoadURLWithParams()` we might be able to isolate the problem that way.

**Comment by walles** [comment]
Maybe we can do this?
https://github.com/atom/electron/blob/master/docs/api/content-tracing.md#contenttracingstartrecordingoptions-callback

**Comment by walles** [comment]
@benogle, @zcbenz, can you tell me how to apply the [start-tracing instructions](https://github.com/atom/electron/blob/master/docs/api/content-tracing.md#contenttracing) around [the slow `@browserWindow.loadUrl` call](https://github.com/atom/atom/blob/7229d1a4295dd0fcb644b7c891a64e6836b2c3b2/src/browser/atom-window.coffee#L80)?

I don't understand how to `require 'electron'` from within `src/browser/atom-window.coffee`.

**Comment by benogle** [comment]
I'm not sure. This is @zcbenz territory

**Comment by walles** [comment]
@zcbenz ping?

Is it possible to tell Chromium to collect trace events...
https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/recording-tracing-runs
... without recompiling it? While running underneath Atom and Electron? Using environment variables or something similar? A config file?

**Comment by zcbenz** [comment]
There is [contentTracing](http://electron.atom.io/docs/v0.36.4/api/content-tracing/) module that can be used to capture the trace events.

**Comment by walles** [comment]
@zcbenz, here are two trace files, one from a quick startup and the other from a slow startup:
[quick.trace.gz](https://github.com/atom/atom/files/124778/quick.trace.gz)
[slow.trace.gz](https://github.com/atom/atom/files/124780/slow.trace.gz)

It seems as if the slow case spends 10s inside of `WaitForSurface::WaitForSingleTaskToRun`, whereas the quick case only does 13ms in there.

This is with Atom 1.5.0.

@zcbenz: What would be the next step to get rid of the intermittent 10s startup pause?

**Comment by walles** [comment]
@zcbenz, any idea on how to get `WaitForSurface::WaitForSingleTaskToRun` not to pause for 10s during startup?

**Comment by brntbeer** [comment]
bump @zcbenz, any thoughts about this or where what we may be able to do to minimize this?

**Comment by walles** [comment]
In #3673 people worry about milliseconds, I call [luxury](https://www.youtube.com/watch?v=Xe1a1wHxTyo) :)

**Comment by walles** [comment]
@as-cii, in #3673 @benogle said that "Startup speed is @as-cii's full time focus right now".

Is it still?

And if so, is this 10s startup pause in `WaitForSurface::WaitForSingleTaskToRun` on your radar?

**Comment by walles** [comment]
@50Wliu, you added the `needs-reproduction` tag to this ticket.

Since it's now been tracked down to a particular method in Chromium, should that tag still be there?

**Comment by 50Wliu** [comment]
Actually I'm going to keep it as it's more of a "no one from the Atom team has reproduced this yet" label.

**Comment by 50Wliu** [comment]
I think this has been solved with #12540.

**Comment by walles** [comment]
@50Wliu, what would be the easiest way for me to find out which release #12540 will be in?

This problem is still alive and kicking in 1.10.2.

**Comment by thomasjo** [comment]
@walles That fix will be released in the upcoming 1.11.0 release which is currently being tested on the [beta channel](https://atom.io/beta).

**Comment by walles** [comment]
Thanks @thomasjo!

**Comment by walles** [comment]
I can confirm 1.11.x doesn't  seem to suffer from this.
