### ISSUE TITLE
[Windows] bash: /dev/tty: No such a device or address

### ISSUE THREAD

**Issue by cfv1984** [atom/atom#8984]
Hi! I developed a package for atom, and when trying to publish it from windows I get this error:

```
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
````

After running ```apm publish minor``` from the repo I'm storing the package into. 

Why is this happening?

**Comment by thomasjo** [comment]
Looks like you're using Cygwin? Try using a *normal* Windows shell such as CMD or PowerShell.

**Comment by cfv1984** [comment]
I'm running that from cmd.exe, with git installed overriding windows tools like find and such so everything should in principle be as git wants. It's puzzling.

**Comment by gavynriebau** [comment]
Same problem but I worked around it by changing the git remote url to include my git username and password.

List your remote URL using:
```bash
git remote -v
```

Update the remote URL to include username and password just before github.com:
```bash
git remote set-url https://<username>:<password>@github.com/<username>/<repo_name>.git
```

Not sure why this was necessary,  I thought I'd be prompted for my credentials if git didn't know them.

More details, hopefully relevant:

1. OS Windows 10
2. Git version is 2.6.0 from http://git-scm.com/
3. Recently done a Windows re-install

**Comment by cfv1984** [comment]
How does one report an issue to git itself?

**Comment by 50Wliu** [comment]
Just ran into this after updating Git to v2.6.0.  I have allowed Git to be used from cmd, but not to override the default cmd commands.
```
C:\Users\user\Documents\GitHub\notifications>apm publish minor
Preparing and tagging a new version done
Pushing v0.60.0 tag failed
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
```

```
> git --version
git version 2.6.1.windows.1
```

**Comment by robinson96** [comment]
I maintain another git-wrapping tool, and my Window's users at git 2.5 and higher are experiencing the same issue.

**Comment by MaybeS** [comment]
same issue,

i think cygwin or other bash tool interupt shell for git@sublime,

.. ㅠㅠ

**Comment by PaoloOranges** [comment]
I had the same error and maybe the way I fixed it could help you too.
I'm using GitExtension 2.48.05. From settings I'm using openSSH (configured via Cygwin). 
I changed the following things:
* Go to Tools->Settings and in "Git"/ "Path to linux" put the bin forlder of your cygwin install
* In SSH panel, set openSSH (openSSH must be installed from Cygwin and configured to run from command line
* use ssh instead of HTTPS links. (I configured "config" file in .ssh on my home directory to use my own private rsa key ) 

Everything works

**Comment by blowsie** [comment]
Try adding this into your git config

```
[credential]
	helper = wincred
```

**Comment by liqiang3** [comment]
@blowsie 

it does not work

**Comment by d0x2f** [comment]
Thanks @blowsie, worked for me.

**Comment by JeyKeu** [comment]
I got this error when I changed my CygWIn home to my windows home by adding the `HOME` environment variable and setting it to `%UserProfile%`

**Comment by Hiroaki-Kubota** [comment]
I think that install winpty may help you.
And run apm this like below:
`winpty apm publish minor`

**Comment by KamranShahid** [comment]
What i did was opened the C:\Users\logedinuser\.gitconfig file and replace triple slahes  \\\ to single
slash \  e.i.
helper = !\\\"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe\\\"

into

helper = !\"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe\"

**Comment by damieng** [comment]
It looks like there are some workarounds here and that the problem is either in Git or in APM. You can report issues with the latter at https://github.com/atom/apm/issues

**Comment by dscho** [comment]
@damieng yep, this is https://github.com/git-for-windows/git/issues/327. The atom bug tracker is definitely the wrong one.

**Comment by caglartoklu** [comment]
Is is possible to check the error level on Windows? If the files cannot be uploaded with the error, the package is still posted. Then, all we have is an empty post on atom.io/packages. It would be great it the the upload were atomic, not posted if it is not successful.

**Comment by bphamous** [comment]
Thanks @blowsie, worked for me! 

> [credential]
    helper = wincred

**Comment by dscho** [comment]
@bphamous please note that the Git Credential Manager is shipped with Git for Windows as of March 15th. It would configure your credential helper automatically, but of course, if you edited your `$HOME/.gitconfig`, the latter would override Git for Windows' setting.

**Comment by wzr1337** [comment]
setting the credential helper was the key to success on my side!

Thanks all!

**Comment by blowsie** [comment]
For people having issue with the credential helper in general, I would recommend using SSH, it can solve a lot of issues.

**Comment by KV-VadimGusev** [comment]
I use GitExtensions as my git wrapper and have been having this issue with new repositories ever since upgrading my local git client to 2.8.4. For some reason the wrapper did not offer to enter the username and password while trying to fetch the data from the repo. Configuring wincred has solved the problem once and for all.

P.S. 

I did not have any issues using the native git client regardless of the credential helper setting.

**Comment by dscho** [comment]
@KV-VadimGusev something tells me that you did not upgrade your local Git client to 2.8.4...

**Comment by KV-VadimGusev** [comment]
@dscho, no I did not. The latest version on the Git download page is 2.8.3, released 4 days ago

**Comment by dscho** [comment]
> The latest version on the Git download page is 2.8.3, released 4 days ago

I know. I released it :smile:

**Comment by deqing** [comment]
@gavynriebau you missed the remote name, it should be:

    git remote set-url remote-name https://<username>:<password>@github.com/<username>/<repo_name>.git

**Comment by Alynva** [comment]
@blowsie tks so much

**Comment by markers16123** [comment]
@blowsie it works for me in MobaXterm

**Comment by jrgitau** [comment]
@blowsie  youre the man worked instantly

**Comment by sungwonida** [comment]
@blowsie Nice, now it works!
`git config --global credential.helper wincred`

**Comment by maddy027** [comment]
@blowsie  it worked. Thanks

**Comment by himanshusoni93** [comment]
HP@HP-PC MINGW64 /f/data science project (master)
$ git push -u origin master
Username for 'https://github.com': h
HP@HP-PC MINGW64 /f/data science project (master)
$ herror: failed to execute prompt script (exit code 1)

how to fix it
