### ISSUE TITLE
Multiple applications running simultaneously

### ISSUE THREAD

**Issue by iconara** [atom/atom#9117]
Every now an again when I use the `atom` command line tool to open a directory in Atom it starts a new process instead of opening it in the already running process.

I don't see any pattern to it, more than that the first time it happens Atom has been running for hours, maybe days. If I just do `atom .` in two different directories after each other it opens in the same process, just as expected. Maybe it's just that I notice it more often when I get back to the computer in the morning or after I haven't used it for a long time, but it seems to happen more frequently in those cases.

Here's two Atom processes in my Dock just now, one of them contains the projects I was working in yesterday, and one of them contains a project that I just opened through `atom .`.

<img width="178" alt="screen shot 2015-10-12 at 08 23 03" src="https://cloud.githubusercontent.com/assets/73330/10422429/88e58bbc-70ba-11e5-9fd9-939ef3a768b4.png">

**Comment by iconara** [comment]
I should add that this is in Mac OS X 10.11.1, and Atom 10.0.19 but I've seen it happen in just about all Atom versions and OS X versions I've used. It feels like it's been more frequent since OS X 10.11, but that could just be that I've noticed it more.

**Comment by izuzak** [comment]
@iconara Strange, I don't remember seeing that myself on OSX. Can you confirm that both of those processes are running the same version of Atom?

**Comment by benogle** [comment]
I see this when the running version's node_modules differs from the node_modules in the repo it was built from. I can repro consistently by 

1. `atom .`
1. `git pull`
1. `script/bootstrap`
1. cd somethwere else, `atom .`
1. :boom: 2 different atoms open

**Comment by iconara** [comment]
@izuzak now it happened again, and it's the same version of Atom, see screenshot.

<img width="433" alt="screen shot 2015-10-14 at 16 41 20" src="https://cloud.githubusercontent.com/assets/73330/10487116/b855e278-7292-11e5-81e1-3c1524228aa0.png">

**Comment by iconara** [comment]
This is what `grep` says:

```
$ ps ax | grep /Applications/Atom.app/Contents/MacOS/Atom | grep -v grep
17265   ??  S      6:47.43 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/theo/Documents/Code/my_project --pid=17261 --path-environment=(redacted) .
96812   ??  S      0:00.96 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/theo/Documents/Code/my_project --pid=96808 --path-environment=(redacted) .
```

I had to remove `--path-environment` value, there was too much information there. I also changed the last path component in the `--executed-from` value, but it was the same in both cases. The two lines were identical except for pid before I changed them.

**Comment by iconara** [comment]
If it helps the path where I executed `atom .` is a Ruby project and RVM was involved (you never know what it interferes with).

**Comment by maxbrunsfeld** [comment]
This means that the second Atom instance is not seeing the socket file created by the first Atom instance. Could you report the output of this command?

```sh
find /var/folders -name 'atom*.sock' 2>/dev/null
```

**Comment by maxbrunsfeld** [comment]
Also, a related issue was recently fixed via https://github.com/atom/atom/pull/8571, but that had to do with running tests within Atom, so it's probably not the same issue you're seeing @iconara.

**Comment by iconara** [comment]
@maxbrunsfeld I'll report back with the output of that command the next time it happens, I've unfortunately quit both processes since my last comment. It might take a day or two, that seems to be the frequency.

**Comment by iconara** [comment]
Now I've got two processes again, and it looks like there's only one socket:

```
$ find /var/folders -name 'atom*.sock' 2>/dev/null
/var/folders/jg/f_1fnft15hb17vtcys41t6vr0000gn/T/atom-theo.sock
```

it was created just now (I ran `atom .` at 09:25):

```
$ stat /var/folders/jg/f_1fnft15hb17vtcys41t6vr0000gn/T/atom-theo.sock
16777220 103272057 srwxr-xr-x 1 theo staff 0 0 "Oct 16 09:25:03 2015" "Oct 16 09:25:03 2015" "Oct 16 09:25:03 2015" "Oct 16 09:24:58 2015" 4096 0 0 /var/folders/jg/f_1fnft15hb17vtcys41t6vr0000gn/T/atom-theo.sock
```

I ran `lsof` to see where the socket of the older process had gone

```
$ ps ax | grep /Applications/Atom.app/Contents/MacOS/Atom | grep -v grep
 1222   ??  S      2:27.28 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=same/path/as/the/other --pid=1218 --path-environment=long/path:identical:to/the/other .
20173   ??  S      0:03.13 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=same/path/as/the/other --pid=20169 --path-environment=long/path:identical:to/the/other .
$ lsof -p 1222 | grep sock
Atom    1222 theo   47u    unix 0xedf62732aa74cd1b       0t0           /var/folders/jg/f_1fnft15hb17vtcys41t6vr0000gn/T/atom-theo.sock
$ lsof -p 20173 | grep sock
Atom    20173 theo   47u    unix 0xedf62732aa74d293       0t0           /var/folders/jg/f_1fnft15hb17vtcys41t6vr0000gn/T/atom-theo.sock
```

but it looks like both processes think they have a socket in that directory.

**Comment by iconara** [comment]
Another thing I discovered now is that it's not sufficient to quit one of the processes, you must quit both, otherwise the next time you run `atom .` you get another one. I guess that since both processes think they have a socket, and it has the same path, the process I quit will remove the socket.

**Comment by dcalhoun** [comment]
I'm experiencing this issue as well. It happens fairly frequently and requires me to quit all Atom processes to exit the state.

I almost always launch Atom using `atom .` and I am also using `rvm` if that has any weight. I'm running Atom 1.0.19 on Mac OS X 10.11.1 (15B42).

Below is the outcome of running all the commands @iconara posted above. All very similar results.

```
% ps ax | grep /Applications/Atom.app/Contents/MacOS/Atom | grep -v grep
51260   ??  S      0:20.38 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/davidcalhoun/Sites/rails/gonoodle --pid=51256 --path-environment=[redacted]
55611   ??  S      0:02.52 /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/davidcalhoun/Sites/rails/gonoodle --pid=55607 --path-environment=[redacted]
```

```
% find /var/folders -name 'atom*.sock' 2>/dev/null
/var/folders/25/cx5kwy_j56s8cd6ktwgv5qn80000gn/T/atom-davidcalhoun.sock
```

```
% stat /var/folders/25/cx5kwy_j56s8cd6ktwgv5qn80000gn/T/atom-davidcalhoun.sock
16777220 65099978 srwxr-xr-x 1 davidcalhoun staff 0 0 "Oct 29 08:16:13 2015" "Oct 29 08:16:13 2015" "Oct 29 08:16:13 2015" "Oct 29 08:16:08 2015" 4096 0 0 /var/folders/25/cx5kwy_j56s8cd6ktwgv5qn80000gn/T/atom-davidcalhoun.sock
```

```
% lsof -p 51260 | grep sock
Atom    51260 davidcalhoun   45u    unix 0xa586f81867314885       0t0          /var/folders/25/cx5kwy_j56s8cd6ktwgv5qn80000gn/T/atom-davidcalhoun.sock
% lsof -p 55611 | grep sock
Atom    55611 davidcalhoun   45u    unix 0xa586f8187e9f0695       0t0          /var/folders/25/cx5kwy_j56s8cd6ktwgv5qn80000gn/T/atom-davidcalhoun.sock
```

**Comment by iconara** [comment]
Since 1.2 it's started happening more frequently, it's up to multiple times per day.

**Comment by maxbrunsfeld** [comment]
@zcbenz Do you have any ideas about what's going on here? In @dcalhoun's comment above, there are two main Atom processes connected to the same socket file.

**Comment by zcbenz** [comment]
@maxbrunsfeld There is probably some race conditions when using the socket way, I think we can switch to use the new `app.makeSingleInstance` API, which is much faster and more reliable:
http://electron.atom.io/docs/v0.35.0/api/app/#app-makesingleinstance-callback

**Comment by iconara** [comment]
Just a periodic reminder that this is still very much an issue in v1.6.2.

**Comment by Zireael07** [comment]
@iconara: Atom 1.7.1 is out now!

**Comment by iconara** [comment]
Still an issue in v1.7.2

**Comment by davidcelis** [comment]
This happens to be too; in my case, it seems to happen after Atom upgrades:

1. Upgrade/restart Atom
2. Use `atom` to open a directory
3. Open new terminal session
4. Change directory, use `atom` to open it
5. Two instances in Dock

**Comment by iconara** [comment]
This is still an issue in v1.7.4

**Comment by palant** [comment]
Note that I just created #11933 which is similar but IMHO caused by an update being ready to install. I didn't see this issue *after* an update.

**Comment by dhrrgn** [comment]
I can confirm this is still happening in v1.8.0.  I actually never had it happen until after the update, but that is probably just a coincidence, or I never noticed it before.

**Comment by stve** [comment]
I've had this problem for quite some time but only when opening a specific project. All of my other projects open in a singular atom process. Here is a before/after account of what happened:

```
› find /var/folders -name 'atom*.sock' 2>/dev/null
/var/folders/cs/xgqgtk2n4d37j9jrsfn1mkf00000gn/T/atom-1.8.0-stve.sock

› atom .

› find /var/folders -name 'atom*.sock' 2>/dev/null
/var/folders/cs/xgqgtk2n4d37j9jrsfn1mkf00000gn/T/atom-1.8.0-root.sock
/var/folders/cs/xgqgtk2n4d37j9jrsfn1mkf00000gn/T/atom-1.8.0-stve.sock
```

The `-root` is perhaps an additional nuance as I don't see anyone else reporting that to this point.

**Comment by rickydazla** [comment]
A similar issue occurs for me sporadically, enough to be annoying, when hitting `⌘⇧A` in Github Desktop app. In this case a second instance launches but does not resolve to show the repo / folder desired. If I quit the new instance and repeat the keystrokes it usually works fine the second time...

**Comment by iconara** [comment]
This is still an issue in 1.9.8.

**Comment by iconara** [comment]
This is still an issue in 1.10.0.

**Comment by iconara** [comment]
This hasn't happened for a while now for me. Hopefully it's was fixed somewhere between 1.10.0 and 1.12.4.

**Comment by palant** [comment]
No, I have just seen #11933 again on 1.12.0-beta4. This happens every time an update is waiting to be installed.

**Comment by dcalhoun** [comment]
This issue still exists. Happened to me today.

<img width="240" alt="atom-duplicate" src="https://user-images.githubusercontent.com/438664/33131872-83d7fda4-cf5d-11e7-9576-c75f7155b55f.png">

### Environment
- Atom 1.22.1
- macOS 10.13.1

### Reproducing
I don't have explicit steps to produce this issue. However, I will say that I always use the `atom` CLI to open files/projects within Atom. At one point it seemed this issue arose around the time I upgraded Atom and/or plugins.

**Comment by iconara** [comment]
It still happens for me every time there is a new Atom release. It seems to happen when a new version has been downloaded, but I haven't restarted, and I use the command line tools.

**Comment by Cremz** [comment]
it happens for me as well.. years later. MacOS 10.14.2, atom 1.34.0.
I have 2 icons, the initial one plus two that i constantly have to remove from dock.
Happens even after restarting or closing atom completely. 
I only open atom using atom .

**Comment by RonnieOnRails** [comment]
still an issue here with Atom  1.58.0, macOS 11.6.1

dunno how to reproduce
