### ISSUE TITLE
Gigantic and blurred fonts

### ISSUE THREAD

**Issue by dappiu** [atom/atom#9454]
Under **Linux**, using new **Atom 1.2.0-beta1** (didn't try -beta0) with Atom Dark UI+Syntax styles, I experience very big font size on File Tree, status bar, file tabs. Editor's font can be adjusted under settings but the font size X appears much bigger (approximately 5pt) than the regular X size of other editors (and previous Atom's versions), and the font is blurred. The font is blurred also in status bar and file tabs, the only place where is not is on file tree explorer (but gigantic anyway). Even MiniMap preview is much larger and blurred.
My styles.less is empty, and Atom produces no errors on startup. Using Atom Material UI+Syntax styles, editor's font is not blurred, but other fonts around are still gigantic and blurred.

Building and installing back versions 1.1.0 or 1.1.0-beta1, solves the issue and everything is back to normal.

Perhaps a bug with new Electron's version?

**Comment by benogle** [comment]
Do you have a high-dpi or retina screen?

**Comment by dappiu** [comment]
It's a 15.6" FHD (1920x1080) laptop screen

**Comment by martinb3** [comment]
I'm also seeing really blurry fonts after having upgraded to 1.2.0 on Ubuntu 15.10.

**Comment by NikoUY** [comment]
Same here, everything is bigger in general, not only the fonts, here are some screenshots:

[1.1.0](http://niko.uy/share/atom2.png)
[1.2.0](http://niko.uy/share/atom.png)

The blur is worst than in the screenshots, I can't work for half an hour without getting a headcache.

**Comment by paulcbetts** [comment]
We've been having blurred fonts in the Slack app on Windows too, we think it has to do with Chrome 45. Hopefully Electron will jump to Chrome 47 soon and that will fix it

**Comment by fiws** [comment]
Same for me, `atom --force-device-scale-factor=1` "fixes" it.
Could you make the scale factor adjustable? Themes already scale well with my monitor imo, I don't need/want chrome scaling.

**Comment by klaszlo** [comment]
@fiws It does not fix the issue. The fonts are still blurry, although smaller.

here is a screenshot (atom 1.2.0):
http://i.imgur.com/7TXfymY.png

I have reverted back to previous stable version (v1.1.0), which does not have this issue.
My system is ubuntu 15.04.

**Comment by martinb3** [comment]
For Ubuntu 15.10, `atom --force-device-scale-factor=1` fixed it for me. Making that the default now! :+1:

**Comment by klaszlo** [comment]
@fiws, @martinb3: could you please post a screenshot (in .png), so we can also check? Because for me it is still blurred with that command line option.

**Comment by martinb3** [comment]
Here's one example -- blurred first:
![screenshot from 2015-11-16 05-05-56](https://cloud.githubusercontent.com/assets/103033/11180530/fb4a620a-8c20-11e5-9bb9-153aeb68b5f2.png)

Then after using `--force-device-scale-factor=1`:
![screenshot from 2015-11-16 05-05-38](https://cloud.githubusercontent.com/assets/103033/11180531/fc81fa0c-8c20-11e5-84af-7cc31b600cf2.png)

**Comment by as-cii** [comment]
It seems like this is a Chromium bug which landed in version 45 and it's hence due to our recent electron upgrade. We're truly sorry that this is causing headaches to you: please, have a look at https://github.com/atom/electron/issues/3349 for more information.

We're looking at this and we'll be posting updates here as well. Thanks everyone! :bow:

**Comment by anywhim** [comment]
Same problem, --force-device-scale-factor=1 fix works.

**Comment by fiws** [comment]
@anywhim nice. But that won't work if i start it from the terminal right? A checkbox in Atom to turn off scaling would be optimal imo. (Even if the blurry fonts get fixed, the UI is still way to huge for me)

**Comment by anywhim** [comment]
@fiws yes, you're right. But you can add an alias to your shell like  ```alias atom='atom --force-device-scale-factor=1'``` and it will works. But in any case it's a hack and we should have a checkbox in the settings just like Chrome have an appropriate flag in chrome://flags.  BTW, you can try ```atom --high-dpi-support=1 --force-device-scale-factor=1```. Maybe it will fix your problem with UI.

**Comment by fiws** [comment]
@anywhim thanks for the hint! `--high-dpi-support=1` changes nothing for me, but `--force-device-scale-factor=1` already fixes the huge UI. (That's why I want a setting for it)

**Comment by montyanderson** [comment]
@anywhim I was hoping this would be fixed with Ubuntu 15.10, but it hasn't. It seems Chromium + Atom have blurry fonts for me, but this fixed it! The tree view is a little small now, but all is well! Thanks so much!

**Comment by GeertJohan** [comment]
F.Y.I. in case anyone else hits this too.

Text was blurry for me on a machine that has a 21:9 1440x3440 screen attached. Not only editor, also configuration screens, menu, etc. Two other machines that run almost exactly the same setup (ubuntu minimal 15.10, lightdm, xmonad) didn't have the issue. The issue was solved by using `atom --force-device-scale-factor=1`.

**Comment by jodyfanning** [comment]
Of course, using the force scaling flag is entirely the wrong way to "fix" the problem, especially in Windows.

The correct thing to do is that Atom (or Chromium) is following the system scaling factor (DPI setting in Windows) so that it actually draws at the correct size and sharply.

**Comment by GeertJohan** [comment]
Yes thia is just a workarround until.its fixed in chromium/electron.

**Comment by acch** [comment]
As this issue has been closed, how to track the problem? Is there a roadmap for a final fix in chromium/electron?

Without `--force-device-scale-factor=1` I'm still experiencing blurry fonts on Arch Linux with Atom 1.3.2...

**Comment by montyanderson** [comment]
I'm on Atom 1.4.0-beta3 on Ubuntu 15.04, and it appears to be fixed.

**Comment by aneophyte** [comment]
Important to check the dpi entries in .Xresources/.Xdefaults also.

**Comment by Sarithis** [comment]
Arch Linux 4.3.3-3, Atom 1.4.1-1 - I'm still experiencing this issue (blurriness). I'm using i3 WM without any extra compositing manager.
Three Monitor setup - 1336x768, 1680x1050, 1440x900. 
xdpyinfo:
dimensions:    4486x1050 pixels (1183x277 millimeters)
resolution:    96x96 dots per inch
What I've already tried:
- modifying stylesheet:
    * {
        font-size: @font-size !important;
        text-rendering: optimizeSpeed !important;
        -webkit-font-smoothing: antialiased !important;
     }
- using --force-device-scale-factor=1

**Comment by aneophyte** [comment]
Fixed the issue on a Linux box by setting the correct DPI of the monitor in ~/.Xresources file.
`Xft.dpi : 100`
That was the actual entry in the file.

**Comment by Sarithis** [comment]
Playing with the Xft.dpi option also didn't solve the problem. I disabled the direct-write in `/usr/share/atom-beta/resources/app.asar` by using a hex editor. After that I can't even run atom, probably it can't run with this option disabled.
I also noticed that on other monitors the text renders just fine. It is blurry only on the laptop's monitor (1336x768). I didn't have this problem before - it appeared after an update from version 1.0 to 1.4
