### ISSUE TITLE
Files with large extremely long lines cause hangs

### ISSUE THREAD

**Issue by bnferguson** [atom/atom#979]
May be a known issue, but files with large embedded images such as github's public/enterprise/maintenance.html will often cause Atom to freeze (MacVim actually struggles as well). 

Seems some of them (github's public/maintenance.html for instance) work fine when in soft wrap mode, or until you move your cursor to the long line when out of soft wrap.

**Comment by benogle** [comment]
Via @tdegrunt in #5270 

> The following file will not open with Atom, but Brackets (and SublimeText, etc) will open the file instantly.
It's likely due to the very long line (with strange characters), but still ...

https://gist.github.com/tdegrunt/1404dc0c35be458bdb59

**Comment by ilanbiala** [comment]
@benogle even the web editor renders it very quickly.

**Comment by hokein** [comment]
I have done some investigations on this issue. Below are some details.

The benchmark runs with two test [files](https://gist.github.com/hokein/48a9ed680d69fbf25305)(test-oneline.js, test-multiple.js), which are the same except line organization. The test-oneline.js is a line containing about 150000 characters.

**Environment**

* Matchine: MacBook Pro on OS X 10.9.4 with 2.4GHz Intel Core i5, 8GB RAM, 256G SSD.
* Atom version: 0.179.0

**Steps**

1. Open Atom's dev-tools, switch to Profiles tab and click `Start` button to start profiling.
2. Open the test file in Atom, wait until finishing.
3. Click `Stop` button to stop profiling.

**Result**

File | Parser Time | Total Time
----- | -----------------|----------------
test-oneline.js |21s | 22.7s
test-multiple.js | 1.8s | 2.7s

I also run the same benchmark in [first-mate](https://github.com/atom/first-mate) directly under nodejs v0.11.13, it gave similar results:

![image](https://cloud.githubusercontent.com/assets/2557445/6526123/39971738-c449-11e4-9cad-75a220f7650e.png)

Below are the detailed profile charts in dev-tools.

test-oneline.js:
![image](https://cloud.githubusercontent.com/assets/2557445/6526114/1b2c1ce4-c449-11e4-9cac-3258ff12509e.png)

test-multipleline.js

![image](https://cloud.githubusercontent.com/assets/2557445/6526132/66ccc00e-c449-11e4-9a58-7c8c5cf7e572.png)

From above charts, we can easily find that the function `OnigScanner.findNextMatchSync`, a JS wrapper for native C++ [`_findNextMatchSync`](https://github.com/atom/node-oniguruma/blob/master/src/onig-scanner.cc#L32-L36) function, takes most of time during parsing period.
It’s probably the major reason causing parser slowly with long-line statements since we pass a long string to `_findNextMatchSync` each time.

BTW, I also find performance issue about `joinLine`, see #5882.

**Comment by prasoon2211** [comment]
I replicated tests done by @hokein and I can confirm his findings. So far as I can see, `OnigScanner` interfaces with the [`Oniguruma`](http://www.geocities.jp/kosako3/oniguruma/) regex library to perform some sort of matching on the input, line by line. The line, however, is very large in this case. And, [regular expressions can be quite slow](http://blog.codinghorror.com/regex-performance/), mostly achieving O(n^2) for [backtracking based algorithms](http://blog.codinghorror.com/regex-performance/) which is pretty bad for 150k char line.

Now, the Oniguruma engine seems to be using a backtracking algorithm ([Link 1](http://patshaughnessy.net/2012/4/3/exploring-rubys-regular-expression-algorithm) [Link 2](http://swtch.com/~rsc/regexp/regexp1.html)) which is the commonly used approach on Ruby, Perl, PHP etc. However, backtracking algorithms can have ['potentially exponential worse cases'](http://google-opensource.blogspot.in/2010/03/re2-principled-approach-to-regular.html) as compared to the finite-state automata regex engines.

According to [this post by Google](http://google-opensource.blogspot.in/2010/03/re2-principled-approach-to-regular.html), the [RE2 engine](https://code.google.com/p/re2/) works under a linear time cap:

>  we've built a new regular expression engine, called RE2, which is based on automata theory and guarantees that searches complete in linear time with respect to the size of the input and in a fixed amount of stack space

Also, tried and tested programs such as GNU grep and awk also use the FSA based regex engines which can [perform much better](http://swtch.com/~rsc/regexp/regexp1.html). See also [these results](https://github.com/ellzey/libevhtp/issues/31#issuecomment-3555744) that confirm what I'm saying in favour of RE2.

So, my point is, perhaps we should switch from the Oniguruma engine to the RE2 engine. All evidence points to the fact the even though RE2 can be a tad slower than Oniguruma in a few specific cases, it is still linear in the worst case as compared to Oniguruma which can be exponential in the worst case.

**Comment by hokein** [comment]
@prasoon2211, Changing to a faster regex engine is one of possible solutions. But as @excaliburHisSheath pointed out, Oniguruma supports more than 30 types of character encodings which is a feature for Atom.

Parsing long line is aslo a performance issue in other editors(Vim, SublimeText). One of the common ways to improve performance is limiting the length of line or disabling parsing long line.

* Vim provides a setting `synmaxcol` allowing user to specify the largest highlight length, see `help synmaxcol`

 > synmaxcol' 'smc'       number  (default 3000)
 >                                   local to buffer
 >                                  {not in Vi}
 >                                  {not available when compiled without the +syntax
 >                                   feature}
 >        Maximum column in which to search for syntax items.  In long lines the
 >        text after this column is not highlighted and following lines may not
 >        be highlighted correctly, because the syntax state is cleared.
 >        This helps to avoid very slow redrawing for an XML file that is one long line.
 >        Set to zero to remove the limit.

* Sublime Text 3 disables highlight if the line is too long for performance, see http://www.sublimetext.com/forum/viewtopic.php?f=3&t=15019

So, I think Atom can follow the processing way of Vim/Sublime. Now Atom limits the maximum highlighted tokens to 100 per line for performance. To go further, we might add the maximum highlighted characters per line, by providing a setting option(like `{maxCharactersPerline:100}`) in [node-oniguruma](https://github.com/atom/node-oniguruma) APIs. @kevinsawicki what's your idea here?

**Comment by excaliburHisSheath** [comment]
Is there a reason why Atom couldn't break parsed lines into smaller chunks for parsing? If the issue is that really long lines cause problems it seems like you could internally represent long lines as several smaller segments for the purposes of parsing and editing. I can see the potential for issues if you were to split a token along segment boundaries, but I think that could be fairly easily avoided for the majority of use cases.

**Comment by prasoon2211** [comment]
@hokein I checked on emacs - it highlights the whole line, at least without any configuration changes. It does get a little slow, however. So, I suppose it is entirely possible to achieve highlighting long lines. Emacs does it with Elisp/C so atom should be able to do it with JS/C++

@excaliburHisSheath I thought of that but since well established editors like vim and emacs have this same problem with highlighting long lines, I suspect that there might be a deppeer problem with this approach that we're not seeing yet. Otherwise, I'm sure *someone* would have added this feature to those editors in the last 30 years :smile:

**Comment by zcbenz** [comment]
In Atom text are converted to UTF-8 before doing the syntax highlighting, so we are not benefiting from Oniguruma's multiple encoding support, and I don't think we will because JavaScript strings in V8 are represented in UTF-8/UTF-16.

Oniguruma was chosen because we need to be compatible with TextMate syntax bundles, so changing to another regex engine will break most Atom's syntax packages.

**Comment by prasoon2211** [comment]
Oh, I didn't know that. But it is worth investigating, IMHO, broken syntax packages or no. Right now, the only major problem I can see people having with atom are related to its performance. So, if using re2 does indeed boost up perf significantly, then I believe it should be done, since it will be helpful in the long run. Syntax highlighting can be made to work later. But that's just my opinion :smile:

**Comment by maxbrunsfeld** [comment]
@prasoon2211, @excaliburHisSheath, @hokein -
Oniguruma may not be as fast as other regexp engines, but I think the root of the problem is the overall tokenization strategy that Atom (and many other text-editors) employ: matching a sequence of regexps to each line, one regexp at a time. This approach will always lead to performance problems for sufficiently long lines.

I think a better solution would be to tokenize buffers using a full-fledged *scanner* (a program that combines all the token patterns into a single state machine). This would completely eliminate the long lines problem. A `flex`-style scanner wouldn't be a complete substitute for a TextMate-grammar though, because TextMate grammars also provide some approximate syntactic information (classes, function definitions, function calls, etc). To fill that roll, we would need an actual parser. This parser would need to be able to efficiently re-parse buffers after edits.

I've been working on an experimental C library, [tree-sitter](https://github.com/maxbrunsfeld/tree-sitter) for generating these types of incremental parsers and scanners. I have made [node bindings](https://github.com/maxbrunsfeld/node-tree-sitter) for it, and an Atom package that uses it - [syntax-tree](https://github.com/maxbrunsfeld/atom-syntax-tree).

Currently, the Atom package does not do anything about syntax highlighting. It just maintains a syntax tree for the buffer as you edit it, and allows you to quickly select structural units of text. The system is very much a work in progress. If you're interested in this sort of thing though, I'd love to hear your feedback on it.

**Comment by excaliburHisSheath** [comment]
@maxbrunsfeld What are the implications of combining all the regexps into a single scanner? If I understand correctly the point would be to combine all the regexps from the different plugins and systems interested in parse data, so are you still able to separate the resulting parse data out the interested parties?

Also, I'm guessing there are still other problems with representing long lines as single strings. Beyond slow parsing I'm guessing editing slows down when you have single lines that contain megabytes of text, though I haven't been able to test this yet. It's probably not as pressing an issue as the parsing since parsing is what is causing the hangs immediately.

**Comment by maxbrunsfeld** [comment]
@excaliburHisSheath all of the tokens for a given language (e.g. javascript, coffee-script, etc) are incorporated into one scanner. Each language has its own scanner. The output of parsing is a syntax tree that can be queried by any package. Are you asking about nested grammars like javascript within HTML, or code within markdown documents? I haven't implemented that capability in my library, but I believe I know how it could be done.

**Comment by excaliburHisSheath** [comment]
@maxbrunsfeld No, I was just curious how you'd get the parsed information to the packages, creating a syntax tree makes a lot of sense. How does that compare to how the information is being passed currently? Is atom already creating a syntax tree? As for nested grammars, how well does atom's existing parsing handle this? In my experience other editors like sublimetext don't handle it very well, so if you have a way to do that through a scanner then that's another feature that atom can boast.

Personally I think the bigger issue is with how atom represents text internally. Representing each line as a single string works fine for most documents, but when you've got documents with single long lines it's no better than just representing the whole document as single strings. That makes me think that there's a better way of handling the content of the document that scales better with both long lines and long files. Doing something to break up the lines into segments seems like the most obvious thing to do, and I imagine it could be done in a way that's (mostly) transparent to other systems.

**Comment by hokein** [comment]
> Oniguruma may not be as fast as other regexp engines, but I think the root of the problem is the overall tokenization strategy that Atom (and many other text-editors) employ: matching a sequence of regexps  to each line, one regexp at a time. This approach will always lead to performance problems for 
 sufficiently long lines.

@maxbrunsfeld Agree.  Atom will iterate all the regexps to find a best match token, which will cost a lot of time.

> I think a better solution would be to tokenize buffers using a full-fledged scanner (a program that > combines all the token patterns into a single state machine). This would completely eliminate the long lines problem. A flex-style scanner wouldn't be a complete substitute for a TextMate-grammar though, because TextMate grammars also provide some approximate syntactic information (classes, function definitions, function calls, etc). To fill that roll, we would need an actual parser. This parser would need to be able to efficiently re-parse buffers after edits.

>I've been working on an experimental C library, tree-sitter for generating these types of incremental parsers and scanners. I have made node bindings for it, and an Atom package that uses it - syntax-tree.

Sounds great. With syntax-tree, we can also support "jump to function" feature without ctags([symbols-view](https://github.com/atom/symbols-view)).

In this solution, should we write a grammar manaully for every programming language? If so, it may require a lot of work. Besides, the tree-sitter generates LR(1) parser. But due to LR(1)'s limitation(only looks ahead one token at a time), it cannot handle all kinds of  programming languages(such as C++).

**Comment by maxbrunsfeld** [comment]
@hokein Yes, we'd have to write a grammar for every programming language. I don't think they're that difficult to write though (see [the javascript grammar](https://github.com/maxbrunsfeld/node-tree-sitter-javascript/blob/master/grammar.coffee)).

I know that a few languages such as C++ can't be fully described by LR(1) grammars, but remember that our main goal is to allow syntax highlighting; we're not trying to compile or interpret the program, so it's ok if statements are occasionally parsed incorrectly. As long as we fully *tokenize* the buffer, and the majority of the program is parsed correctly, an LR(1) parser will be a vast improvement over TextMate grammars.

Also, as grammar formalisms go, LR(1) is pretty powerful. Any LR(k) grammar can be converted to LR(1), and most programming languages grammars are designed to be efficiently parseable, usually by a **less** powerful formalism, like LALR(1).

**Comment by ponychicken** [comment]
This sounds like a very good idea. I don't think Textmate compatibility is something important, it was only helpful to get an initial set of language plugins. And since we wouldn't want to break all plugins in on stroke, plugins would probably opt-in to using LR(1) instead of regex parsers. For something like javascript the regexes are an unmaintainable mess with a lot of subtle problems and a proper grammar would help greatly.

**Comment by tribou** [comment]
Does anyone have a workaround to view large files in Atom until this issue is resolved?

**Comment by 50Wliu** [comment]
@tribou If your file is "large" (>2MB) you can use @mark-hahn's [view-tail-large-files](https://atom.io/packages/view-tail-large-files) package.  I can't guarantee that will work for the bug described here though.

**Comment by octref** [comment]
view-tail-large-files also hangs up on long lines.

**Comment by mark-hahn** [comment]
> view-tail-large-files also hangs up on long lines.

The limit is somewhat artificial.  It is just there because the file read
input buffer has to be that big.  It is currently set at 10 KB.  How long
would you need?

**Comment by octref** [comment]
@mark-hahn 
Do you mean 10**MB**?

Sorry the culprit turns out to be a small package I wrote myself just for large file testing. Your package works great for long lines.

**Comment by mark-hahn** [comment]
> Do you mean 10*MB*?

Nope.  I just checked the readme and it is actually 16 KB.  I can bump it
up if anyone has a use case.  Lines that long would be impossible to read.
 :-)

**Comment by tribou** [comment]
[view-tail-large-files](https://atom.io/packages/view-tail-large-files) worked for me.  Thanks!

**Comment by sundaywork** [comment]
issue still exists

**Comment by doxigo** [comment]
have the same issue with latest version on mac

**Comment by shanalikhan1** [comment]
Issue is still there on latest version on Windows 7 64 bit
Even it shows error to close the atom or keep waiting i keep waiting and it shows again and again. Took about 4 minutes to load the file containing just about < 20K lines.
Migrating towards Visual Studio Code  , will shift back once done :-1:

**Comment by 50Wliu** [comment]
This issue is already on the 1.0 roadmap and currently being addressed.
Many improvements from [text-document](https://github.com/atom/text-document) are making their way into [text-buffer](https://github.com/atom/text-buffer), which is the package Atom uses to handle files.  In addition, @as-cii, @nathansobo, and @maxbrunsfeld have been hard at work trying to optimize Atom and decrease its memory usage so that situations like this no longer happen (for example, #5931 aims to partially solve this issue while #6757 reduces memory usage by ~70%).

In the meantime, a package by @mark-hahn is also available ([view-tail-large-files](https://atom.io/packages/view-tail-large-files)) that may act as a temporary workaround to this issue.

In light of all this, I'm going to lock this issue for now.

**Comment by mcanas** [comment]
Related issue #8345

Timeline:
![screen shot 2015-08-12 at 11 59 37 am](https://cloud.githubusercontent.com/assets/1584732/9229815/00102c9a-40ed-11e5-99a9-3b4692baf085.png)

**Comment by derwaldgeist** [comment]
Bump. I'm using a database prefiller skript that uses base64-coded images to store them in the database. It's only 3 images, but Atom editor hangs on loading. Even worse, after "killing" the editor using the "hang" dialog, the tree-view is missing.

**Comment by doug-orchard** [comment]
Loading a uglified react.js file created by browserify... it hangs. on MacAir, 4Gb RAM.

**Comment by Dbuggerx** [comment]
Same here, long lined "uglified" file makes Atom freeze.

**Comment by Dinuka2013513** [comment]
Hi , I would like to contribute to github atom. Please help me how can I join with the discussion groups. It'l be a good experience for me to join with Github also while studying since I have experience in Opensource for some time.

**Comment by timdp** [comment]
I fully realize that this is not an easy one to fix, but at the same time, it's quite awkward when I convince another colleague to use Atom and then it hangs indefinitely when they open a random file.

From the looks of it, an intermediate solution would be to limit the line length at which the RE parser kicks in. After all, disabling syntax highlighting and linting is a lot better than going completely unresponsive. My gut feeling says that this would be a relatively straightforward patch. Any chance of getting it in for the time being?

**Comment by shanalikhan1** [comment]
I agree with @timdp
I convinced many programmers to atom but really ashamed off when they randomly opened some file and it hanged every single time.
They all moved to visual studio code
I love atom therefore always looking discussion witha hope that they will make it faster else i will move to visual studio code.

**Comment by doug-orchard** [comment]
A solution I just discovered currently involves adding a .jshintignore to the app root with 'public/jquery.js' (or whatever the file is causing you issues) if you are running the jsHint package. Still a small hint of delay but good to say no more messages asking to close the window or wait.

**Comment by timdp** [comment]
Also, @hokein did some great work profiling typical invocations earlier in this thread. Below the `_findNextMatchSync` function that he identified as the culprit, there's a [`_findNextMatch`](https://github.com/atom/node-oniguruma/blob/master/src/onig-scanner.cc#L40-L45) that is presumably async. Wouldn't it also be possible to use that one? Or would that just slow down linting like crazy and become a nightmare to maintain?

**Comment by CrazyPython** [comment]
Works on OSX and in the browser too. I don't know why long lines cause such a problem.

**Comment by derwaldgeist** [comment]
@timdp Yes, I'd also prefer having no linting over having to kill the whole editor...

**Comment by CrazyPython** [comment]
@derwaldgeist I'd prefer having no listing than having to kill my entire browser... (with not-exactly-restorable data)

**Comment by skyrpex** [comment]
:+1: for no linting in this case

**Comment by CrazyPython** [comment]
I think there should be a disable lint functionality in web Atom; or perhaps a persistent setting in HTML5 web storage.

**Comment by maxbrunsfeld** [comment]
I don't think 'linting' has anything to do with this. Atom does not provide linting; it is provided by a third party package: https://github.com/atomlinter/linter. If you want to disable syntax highlighting, select `Plain Text` from the Grammar Selector.

**Comment by CrazyPython** [comment]
I hope this is fixed soon. I pretty much can't edit HTML files on GitHub. On slow computers, it freezes me for 5 seconds every time I type a character. On my MBA, it freezes when I type a few characters I type, and then I have to close the browser. Is there a way to change atom into a raw text editor?

**Comment by james-portman-mf** [comment]
Just to add,
working with large JSON files this is also causing me issues,
currently cannot open atom at all,
have deleted the file which caused this and still cannot open atom.

**Comment by yihaa5** [comment]
I'm already switched to Notepad++ . Didn't see much progression for this commonly required fix. Kinda dissappointed.
Thanks afterall for the Effort of building this editor.

**Comment by skyrpex** [comment]
I hate to recognize it, but I switched back to Sublime Text again...

**Comment by shanalikhan1** [comment]
Well i have switched to visual studio code ! Already
Thanks developers afterall for atom !

**Comment by thomasjo** [comment]
I'm locking this thread for the time being — there's no value in notifying 35+ people about switching to another editor. Yes, this is definitely something that should be addressed (and it has to a certain extent), and is being worked on indirectly even though it might not be apparent. Increasing the performance of Atom is one of the top priorities.

**Comment by 50Wliu** [comment]
Atom should be able to open files with very large lines starting with Atom 1.16.0.

**Comment by maxbrunsfeld** [comment]
We decided to backport this fix to the current beta release, so it's available today in Atom 1.15.0-beta3.
